/home/servermtsn2kolut/mtsn2kolut-super-app/logs/*.log /home/servermtsn2kolut/mtsn2kolut-super-app/services/logs/*.log /home/servermtsn2kolut/mtsn2kolut-super-app/apps/logs/*.log {
    daily
    rotate 14
    size 20M
    missingok
    notifempty
    compress
    delaycompress
    copytruncate
    create 0640 servermtsn2kolut servermtsn2kolut
}
