/home/servermtsn2kolut/logs/mtsn2kolut-super-app/*.log {
    daily
    rotate 14
    size 20M
    missingok
    notifempty
    compress
    delaycompress
    copytruncate
    create 0640 servermtsn2kolut servermtsn2kolut
}
