// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimJob = `-- name: ClaimJob :one
WITH candidate AS (
  SELECT id FROM jobs
  WHERE (status = 'queued')
     OR (status = 'failed' AND attempts < max_attempts AND next_retry_at <= NOW())
  ORDER BY created_at ASC
  FOR UPDATE SKIP LOCKED
  LIMIT 1
),
updated AS (
  UPDATE jobs
  SET status     = 'running',
      claimed_by = $1,
      claimed_at = NOW(),
      attempts   = attempts + 1,
      updated_at = NOW()
  FROM candidate
  WHERE jobs.id = candidate.id
  RETURNING jobs.id, jobs.employee_id, jobs.run_type, jobs.attempts, jobs.max_attempts
)
SELECT u.id, u.employee_id, u.run_type, u.attempts, u.max_attempts,
       e.pusaka_username, e.pusaka_password
FROM updated u
JOIN employees e ON e.id = u.employee_id
`

type ClaimJobRow struct {
	ID             pgtype.UUID `json:"id"`
	EmployeeID     pgtype.UUID `json:"employee_id"`
	RunType        RunTypeEnum `json:"run_type"`
	Attempts       int32       `json:"attempts"`
	MaxAttempts    int32       `json:"max_attempts"`
	PusakaUsername string      `json:"pusaka_username"`
	PusakaPassword string      `json:"pusaka_password"`
}

func (q *Queries) ClaimJob(ctx context.Context, claimedBy string) (ClaimJobRow, error) {
	row := q.db.QueryRow(ctx, claimJob, claimedBy)
	var i ClaimJobRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.RunType,
		&i.Attempts,
		&i.MaxAttempts,
		&i.PusakaUsername,
		&i.PusakaPassword,
	)
	return i, err
}

const completeJob = `-- name: CompleteJob :exec
UPDATE jobs
SET status        = 'success',
    error_message = '',
    updated_at    = NOW()
WHERE id = $1
`

func (q *Queries) CompleteJob(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, completeJob, id)
	return err
}

const countJobs = `-- name: CountJobs :one
SELECT COUNT(*) FROM jobs
`

func (q *Queries) CountJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countJobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countJobsByStatus = `-- name: CountJobsByStatus :one
SELECT COUNT(*) FROM jobs WHERE status = $1
`

func (q *Queries) CountJobsByStatus(ctx context.Context, status JobStatusEnum) (int64, error) {
	row := q.db.QueryRow(ctx, countJobsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (id, employee_id, run_type, status, max_attempts)
VALUES (gen_random_uuid(), $1, $2, 'queued', $3)
RETURNING id, employee_id, run_type, status, error_message, claimed_by, claimed_at, attempts, max_attempts, next_retry_at, created_at, updated_at
`

type CreateJobParams struct {
	EmployeeID  pgtype.UUID `json:"employee_id"`
	RunType     RunTypeEnum `json:"run_type"`
	MaxAttempts int32       `json:"max_attempts"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob, arg.EmployeeID, arg.RunType, arg.MaxAttempts)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.RunType,
		&i.Status,
		&i.ErrorMessage,
		&i.ClaimedBy,
		&i.ClaimedAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.NextRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failJob = `-- name: FailJob :exec
UPDATE jobs
SET status        = 'failed',
    error_message = $2,
    claimed_by    = '',
    next_retry_at = CASE
      WHEN attempts < max_attempts THEN NOW() + ($3 || ' seconds')::INTERVAL
      ELSE NULL
    END,
    updated_at    = NOW()
WHERE id = $1
`

type FailJobParams struct {
	ID           pgtype.UUID `json:"id"`
	ErrorMessage string      `json:"error_message"`
	Column3      pgtype.Text `json:"column_3"`
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) error {
	_, err := q.db.Exec(ctx, failJob, arg.ID, arg.ErrorMessage, arg.Column3)
	return err
}

const getJobStats = `-- name: GetJobStats :one
SELECT
  COUNT(*) FILTER (WHERE status = 'queued')  AS queued,
  COUNT(*) FILTER (WHERE status = 'running') AS running,
  COUNT(*) FILTER (WHERE status = 'success') AS success,
  COUNT(*) FILTER (WHERE status = 'failed')  AS failed
FROM jobs
`

type GetJobStatsRow struct {
	Queued  int64 `json:"queued"`
	Running int64 `json:"running"`
	Success int64 `json:"success"`
	Failed  int64 `json:"failed"`
}

func (q *Queries) GetJobStats(ctx context.Context) (GetJobStatsRow, error) {
	row := q.db.QueryRow(ctx, getJobStats)
	var i GetJobStatsRow
	err := row.Scan(
		&i.Queued,
		&i.Running,
		&i.Success,
		&i.Failed,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT j.id, j.employee_id, e.nama AS employee_nama, e.nip AS employee_nip,
       j.run_type, j.status, j.error_message,
       j.claimed_by, j.claimed_at, j.attempts, j.max_attempts,
       j.next_retry_at, j.created_at, j.updated_at
FROM jobs j
JOIN employees e ON e.id = j.employee_id
ORDER BY j.created_at DESC
LIMIT $1 OFFSET $2
`

type ListJobsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListJobsRow struct {
	ID           pgtype.UUID        `json:"id"`
	EmployeeID   pgtype.UUID        `json:"employee_id"`
	EmployeeNama string             `json:"employee_nama"`
	EmployeeNip  string             `json:"employee_nip"`
	RunType      RunTypeEnum        `json:"run_type"`
	Status       JobStatusEnum      `json:"status"`
	ErrorMessage string             `json:"error_message"`
	ClaimedBy    string             `json:"claimed_by"`
	ClaimedAt    pgtype.Timestamptz `json:"claimed_at"`
	Attempts     int32              `json:"attempts"`
	MaxAttempts  int32              `json:"max_attempts"`
	NextRetryAt  pgtype.Timestamptz `json:"next_retry_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]ListJobsRow, error) {
	rows, err := q.db.Query(ctx, listJobs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobsRow{}
	for rows.Next() {
		var i ListJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.EmployeeNama,
			&i.EmployeeNip,
			&i.RunType,
			&i.Status,
			&i.ErrorMessage,
			&i.ClaimedBy,
			&i.ClaimedAt,
			&i.Attempts,
			&i.MaxAttempts,
			&i.NextRetryAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByStatus = `-- name: ListJobsByStatus :many
SELECT j.id, j.employee_id, e.nama AS employee_nama, e.nip AS employee_nip,
       j.run_type, j.status, j.error_message,
       j.claimed_by, j.claimed_at, j.attempts, j.max_attempts,
       j.next_retry_at, j.created_at, j.updated_at
FROM jobs j
JOIN employees e ON e.id = j.employee_id
WHERE j.status = $1
ORDER BY j.created_at DESC
LIMIT $2 OFFSET $3
`

type ListJobsByStatusParams struct {
	Status JobStatusEnum `json:"status"`
	Limit  int32         `json:"limit"`
	Offset int32         `json:"offset"`
}

type ListJobsByStatusRow struct {
	ID           pgtype.UUID        `json:"id"`
	EmployeeID   pgtype.UUID        `json:"employee_id"`
	EmployeeNama string             `json:"employee_nama"`
	EmployeeNip  string             `json:"employee_nip"`
	RunType      RunTypeEnum        `json:"run_type"`
	Status       JobStatusEnum      `json:"status"`
	ErrorMessage string             `json:"error_message"`
	ClaimedBy    string             `json:"claimed_by"`
	ClaimedAt    pgtype.Timestamptz `json:"claimed_at"`
	Attempts     int32              `json:"attempts"`
	MaxAttempts  int32              `json:"max_attempts"`
	NextRetryAt  pgtype.Timestamptz `json:"next_retry_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListJobsByStatus(ctx context.Context, arg ListJobsByStatusParams) ([]ListJobsByStatusRow, error) {
	rows, err := q.db.Query(ctx, listJobsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobsByStatusRow{}
	for rows.Next() {
		var i ListJobsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.EmployeeNama,
			&i.EmployeeNip,
			&i.RunType,
			&i.Status,
			&i.ErrorMessage,
			&i.ClaimedBy,
			&i.ClaimedAt,
			&i.Attempts,
			&i.MaxAttempts,
			&i.NextRetryAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
