// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schedules.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSchedule = `-- name: GetSchedule :one
SELECT id, label, run_time, run_type, is_enabled, created_at, updated_at
FROM schedules
WHERE id = $1
`

func (q *Queries) GetSchedule(ctx context.Context, id pgtype.UUID) (Schedule, error) {
	row := q.db.QueryRow(ctx, getSchedule, id)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.RunTime,
		&i.RunType,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSchedules = `-- name: ListSchedules :many
SELECT id, label, run_time, run_type, is_enabled, created_at, updated_at
FROM schedules
ORDER BY run_type ASC
`

func (q *Queries) ListSchedules(ctx context.Context) ([]Schedule, error) {
	rows, err := q.db.Query(ctx, listSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Schedule{}
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.RunTime,
			&i.RunType,
			&i.IsEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSchedule = `-- name: UpsertSchedule :one
INSERT INTO schedules (id, label, run_time, run_type, is_enabled)
VALUES (gen_random_uuid(), $1, $2, $3, $4)
ON CONFLICT (run_type) DO UPDATE
  SET label      = EXCLUDED.label,
      run_time   = EXCLUDED.run_time,
      is_enabled = EXCLUDED.is_enabled,
      updated_at = NOW()
RETURNING id, label, run_time, run_type, is_enabled, created_at, updated_at
`

type UpsertScheduleParams struct {
	Label     string      `json:"label"`
	RunTime   string      `json:"run_time"`
	RunType   RunTypeEnum `json:"run_type"`
	IsEnabled bool        `json:"is_enabled"`
}

func (q *Queries) UpsertSchedule(ctx context.Context, arg UpsertScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, upsertSchedule,
		arg.Label,
		arg.RunTime,
		arg.RunType,
		arg.IsEnabled,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.RunTime,
		&i.RunType,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
