// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: archives.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createArchiveCategory = `-- name: CreateArchiveCategory :one
INSERT INTO archive_categories (
    code, name, classification_code, description, retention_years, is_active
) VALUES (
    $1,
    $2,
    NULLIF($3::TEXT, ''),
    $4,
    $5,
    $6
)
RETURNING id, code, name, classification_code, description, retention_years, is_active, created_at, updated_at
`

type CreateArchiveCategoryParams struct {
	Code               string `json:"code"`
	Name               string `json:"name"`
	ClassificationCode string `json:"classification_code"`
	Description        string `json:"description"`
	RetentionYears     int32  `json:"retention_years"`
	IsActive           bool   `json:"is_active"`
}

func (q *Queries) CreateArchiveCategory(ctx context.Context, arg CreateArchiveCategoryParams) (ArchiveCategory, error) {
	row := q.db.QueryRow(ctx, createArchiveCategory,
		arg.Code,
		arg.Name,
		arg.ClassificationCode,
		arg.Description,
		arg.RetentionYears,
		arg.IsActive,
	)
	var i ArchiveCategory
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.ClassificationCode,
		&i.Description,
		&i.RetentionYears,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createArchiveDocument = `-- name: CreateArchiveDocument :one
INSERT INTO archive_documents (
    category_id,
    title,
    archive_number,
    document_date,
    received_date,
    summary,
    tags,
    status,
    storage_location,
    retention_until,
    original_name,
    stored_name,
    file_path,
    mime_type,
    file_size,
    checksum_sha256,
    uploaded_by_user_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
RETURNING id, category_id, title, archive_number, document_date, received_date, summary, tags, status, storage_location, retention_until, original_name, stored_name, file_path, mime_type, file_size, checksum_sha256, uploaded_by_user_id, created_at, updated_at
`

type CreateArchiveDocumentParams struct {
	CategoryID       pgtype.UUID `json:"category_id"`
	Title            string      `json:"title"`
	ArchiveNumber    string      `json:"archive_number"`
	DocumentDate     pgtype.Date `json:"document_date"`
	ReceivedDate     pgtype.Date `json:"received_date"`
	Summary          string      `json:"summary"`
	Tags             string      `json:"tags"`
	Status           string      `json:"status"`
	StorageLocation  string      `json:"storage_location"`
	RetentionUntil   pgtype.Date `json:"retention_until"`
	OriginalName     string      `json:"original_name"`
	StoredName       string      `json:"stored_name"`
	FilePath         string      `json:"file_path"`
	MimeType         string      `json:"mime_type"`
	FileSize         int64       `json:"file_size"`
	ChecksumSha256   string      `json:"checksum_sha256"`
	UploadedByUserID pgtype.UUID `json:"uploaded_by_user_id"`
}

func (q *Queries) CreateArchiveDocument(ctx context.Context, arg CreateArchiveDocumentParams) (ArchiveDocument, error) {
	row := q.db.QueryRow(ctx, createArchiveDocument,
		arg.CategoryID,
		arg.Title,
		arg.ArchiveNumber,
		arg.DocumentDate,
		arg.ReceivedDate,
		arg.Summary,
		arg.Tags,
		arg.Status,
		arg.StorageLocation,
		arg.RetentionUntil,
		arg.OriginalName,
		arg.StoredName,
		arg.FilePath,
		arg.MimeType,
		arg.FileSize,
		arg.ChecksumSha256,
		arg.UploadedByUserID,
	)
	var i ArchiveDocument
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Title,
		&i.ArchiveNumber,
		&i.DocumentDate,
		&i.ReceivedDate,
		&i.Summary,
		&i.Tags,
		&i.Status,
		&i.StorageLocation,
		&i.RetentionUntil,
		&i.OriginalName,
		&i.StoredName,
		&i.FilePath,
		&i.MimeType,
		&i.FileSize,
		&i.ChecksumSha256,
		&i.UploadedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteArchiveCategory = `-- name: DeleteArchiveCategory :exec
DELETE FROM archive_categories WHERE id = $1
`

func (q *Queries) DeleteArchiveCategory(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteArchiveCategory, id)
	return err
}

const deleteArchiveDocument = `-- name: DeleteArchiveDocument :exec
DELETE FROM archive_documents WHERE id = $1
`

func (q *Queries) DeleteArchiveDocument(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteArchiveDocument, id)
	return err
}

const getArchiveCategory = `-- name: GetArchiveCategory :one
SELECT id, code, name, classification_code, description, retention_years, is_active, created_at, updated_at
FROM archive_categories
WHERE id = $1
`

func (q *Queries) GetArchiveCategory(ctx context.Context, id pgtype.UUID) (ArchiveCategory, error) {
	row := q.db.QueryRow(ctx, getArchiveCategory, id)
	var i ArchiveCategory
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.ClassificationCode,
		&i.Description,
		&i.RetentionYears,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArchiveDocument = `-- name: GetArchiveDocument :one
SELECT id, category_id, title, archive_number, document_date, received_date, summary, tags, status, storage_location, retention_until, original_name, stored_name, file_path, mime_type, file_size, checksum_sha256, uploaded_by_user_id, created_at, updated_at
FROM archive_documents
WHERE id = $1
`

func (q *Queries) GetArchiveDocument(ctx context.Context, id pgtype.UUID) (ArchiveDocument, error) {
	row := q.db.QueryRow(ctx, getArchiveDocument, id)
	var i ArchiveDocument
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Title,
		&i.ArchiveNumber,
		&i.DocumentDate,
		&i.ReceivedDate,
		&i.Summary,
		&i.Tags,
		&i.Status,
		&i.StorageLocation,
		&i.RetentionUntil,
		&i.OriginalName,
		&i.StoredName,
		&i.FilePath,
		&i.MimeType,
		&i.FileSize,
		&i.ChecksumSha256,
		&i.UploadedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArchiveDocumentDetail = `-- name: GetArchiveDocumentDetail :one
SELECT
    ad.id,
    ad.category_id,
    ac.code AS category_code,
    ac.name AS category_name,
    COALESCE(ac.classification_code, '')::TEXT AS classification_code,
    ad.title,
    ad.archive_number,
    ad.document_date,
    ad.received_date,
    ad.summary,
    ad.tags,
    ad.status,
    ad.storage_location,
    ad.retention_until,
    ad.original_name,
    ad.stored_name,
    ad.mime_type,
    ad.file_size,
    ad.checksum_sha256,
    ad.uploaded_by_user_id,
    COALESCE(u.username, '')::TEXT AS uploaded_by_username,
    ad.created_at,
    ad.updated_at
FROM archive_documents ad
JOIN archive_categories ac ON ac.id = ad.category_id
LEFT JOIN users u ON u.id = ad.uploaded_by_user_id
WHERE ad.id = $1
`

type GetArchiveDocumentDetailRow struct {
	ID                 pgtype.UUID        `json:"id"`
	CategoryID         pgtype.UUID        `json:"category_id"`
	CategoryCode       string             `json:"category_code"`
	CategoryName       string             `json:"category_name"`
	ClassificationCode string             `json:"classification_code"`
	Title              string             `json:"title"`
	ArchiveNumber      string             `json:"archive_number"`
	DocumentDate       pgtype.Date        `json:"document_date"`
	ReceivedDate       pgtype.Date        `json:"received_date"`
	Summary            string             `json:"summary"`
	Tags               string             `json:"tags"`
	Status             string             `json:"status"`
	StorageLocation    string             `json:"storage_location"`
	RetentionUntil     pgtype.Date        `json:"retention_until"`
	OriginalName       string             `json:"original_name"`
	StoredName         string             `json:"stored_name"`
	MimeType           string             `json:"mime_type"`
	FileSize           int64              `json:"file_size"`
	ChecksumSha256     string             `json:"checksum_sha256"`
	UploadedByUserID   pgtype.UUID        `json:"uploaded_by_user_id"`
	UploadedByUsername string             `json:"uploaded_by_username"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetArchiveDocumentDetail(ctx context.Context, id pgtype.UUID) (GetArchiveDocumentDetailRow, error) {
	row := q.db.QueryRow(ctx, getArchiveDocumentDetail, id)
	var i GetArchiveDocumentDetailRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.CategoryCode,
		&i.CategoryName,
		&i.ClassificationCode,
		&i.Title,
		&i.ArchiveNumber,
		&i.DocumentDate,
		&i.ReceivedDate,
		&i.Summary,
		&i.Tags,
		&i.Status,
		&i.StorageLocation,
		&i.RetentionUntil,
		&i.OriginalName,
		&i.StoredName,
		&i.MimeType,
		&i.FileSize,
		&i.ChecksumSha256,
		&i.UploadedByUserID,
		&i.UploadedByUsername,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArchiveStats = `-- name: GetArchiveStats :one
SELECT
    (SELECT COUNT(*) FROM archive_categories WHERE is_active)::BIGINT AS active_categories,
    (SELECT COUNT(*) FROM archive_documents)::BIGINT AS total_documents,
    (SELECT COUNT(*) FROM archive_documents WHERE status = 'active')::BIGINT AS active_documents,
    (SELECT COUNT(*) FROM archive_documents WHERE status = 'borrowed')::BIGINT AS borrowed_documents,
    (SELECT COUNT(*) FROM archive_documents WHERE status = 'disposed')::BIGINT AS disposed_documents,
    (SELECT COUNT(*) FROM archive_documents WHERE EXTRACT(YEAR FROM received_date) = EXTRACT(YEAR FROM NOW()))::BIGINT AS documents_this_year,
    (SELECT COALESCE(SUM(file_size), 0) FROM archive_documents)::BIGINT AS total_file_size
`

type GetArchiveStatsRow struct {
	ActiveCategories  int64 `json:"active_categories"`
	TotalDocuments    int64 `json:"total_documents"`
	ActiveDocuments   int64 `json:"active_documents"`
	BorrowedDocuments int64 `json:"borrowed_documents"`
	DisposedDocuments int64 `json:"disposed_documents"`
	DocumentsThisYear int64 `json:"documents_this_year"`
	TotalFileSize     int64 `json:"total_file_size"`
}

func (q *Queries) GetArchiveStats(ctx context.Context) (GetArchiveStatsRow, error) {
	row := q.db.QueryRow(ctx, getArchiveStats)
	var i GetArchiveStatsRow
	err := row.Scan(
		&i.ActiveCategories,
		&i.TotalDocuments,
		&i.ActiveDocuments,
		&i.BorrowedDocuments,
		&i.DisposedDocuments,
		&i.DocumentsThisYear,
		&i.TotalFileSize,
	)
	return i, err
}

const listArchiveCategories = `-- name: ListArchiveCategories :many
SELECT
    ac.id,
    ac.code,
    ac.name,
    COALESCE(ac.classification_code, '')::TEXT AS classification_code,
    COALESCE(lc.name, '')::TEXT AS classification_name,
    ac.description,
    ac.retention_years,
    ac.is_active,
    ac.created_at,
    ac.updated_at,
    COALESCE(doc.document_count, 0)::BIGINT AS document_count
FROM archive_categories ac
LEFT JOIN letter_classifications lc ON lc.code = ac.classification_code
LEFT JOIN LATERAL (
    SELECT COUNT(*) AS document_count
    FROM archive_documents ad
    WHERE ad.category_id = ac.id
) doc ON TRUE
WHERE (
    $1::TEXT = '' OR
    ac.code ILIKE '%' || $1 || '%' OR
    ac.name ILIKE '%' || $1 || '%' OR
    ac.description ILIKE '%' || $1 || '%' OR
    ac.classification_code ILIKE '%' || $1 || '%'
) AND (
    $2::BOOLEAN = FALSE OR ac.is_active = TRUE
)
ORDER BY ac.is_active DESC, ac.code
`

type ListArchiveCategoriesParams struct {
	Search     string `json:"search"`
	ActiveOnly bool   `json:"active_only"`
}

type ListArchiveCategoriesRow struct {
	ID                 pgtype.UUID        `json:"id"`
	Code               string             `json:"code"`
	Name               string             `json:"name"`
	ClassificationCode string             `json:"classification_code"`
	ClassificationName string             `json:"classification_name"`
	Description        string             `json:"description"`
	RetentionYears     int32              `json:"retention_years"`
	IsActive           bool               `json:"is_active"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DocumentCount      int64              `json:"document_count"`
}

func (q *Queries) ListArchiveCategories(ctx context.Context, arg ListArchiveCategoriesParams) ([]ListArchiveCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listArchiveCategories, arg.Search, arg.ActiveOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArchiveCategoriesRow{}
	for rows.Next() {
		var i ListArchiveCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.ClassificationCode,
			&i.ClassificationName,
			&i.Description,
			&i.RetentionYears,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DocumentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchiveDocuments = `-- name: ListArchiveDocuments :many
SELECT
    ad.id,
    ad.category_id,
    ac.code AS category_code,
    ac.name AS category_name,
    COALESCE(ac.classification_code, '')::TEXT AS classification_code,
    ad.title,
    ad.archive_number,
    ad.document_date,
    ad.received_date,
    ad.summary,
    ad.tags,
    ad.status,
    ad.storage_location,
    ad.retention_until,
    ad.original_name,
    ad.stored_name,
    ad.mime_type,
    ad.file_size,
    ad.checksum_sha256,
    ad.uploaded_by_user_id,
    COALESCE(u.username, '')::TEXT AS uploaded_by_username,
    ad.created_at,
    ad.updated_at
FROM archive_documents ad
JOIN archive_categories ac ON ac.id = ad.category_id
LEFT JOIN users u ON u.id = ad.uploaded_by_user_id
WHERE (
    $1::TEXT = '' OR
    ad.title ILIKE '%' || $1 || '%' OR
    ad.archive_number ILIKE '%' || $1 || '%' OR
    ad.summary ILIKE '%' || $1 || '%' OR
    ad.tags ILIKE '%' || $1 || '%' OR
    ad.original_name ILIKE '%' || $1 || '%' OR
    ac.code ILIKE '%' || $1 || '%' OR
    ac.name ILIKE '%' || $1 || '%'
) AND (
    $2::UUID IS NULL OR ad.category_id = $2::UUID
) AND (
    $3::TEXT = '' OR ad.status = $3
) AND (
    $4::TEXT = '' OR ac.classification_code = $4
)
ORDER BY ad.received_date DESC, ad.created_at DESC
`

type ListArchiveDocumentsParams struct {
	Search             string      `json:"search"`
	CategoryID         pgtype.UUID `json:"category_id"`
	Status             string      `json:"status"`
	ClassificationCode string      `json:"classification_code"`
}

type ListArchiveDocumentsRow struct {
	ID                 pgtype.UUID        `json:"id"`
	CategoryID         pgtype.UUID        `json:"category_id"`
	CategoryCode       string             `json:"category_code"`
	CategoryName       string             `json:"category_name"`
	ClassificationCode string             `json:"classification_code"`
	Title              string             `json:"title"`
	ArchiveNumber      string             `json:"archive_number"`
	DocumentDate       pgtype.Date        `json:"document_date"`
	ReceivedDate       pgtype.Date        `json:"received_date"`
	Summary            string             `json:"summary"`
	Tags               string             `json:"tags"`
	Status             string             `json:"status"`
	StorageLocation    string             `json:"storage_location"`
	RetentionUntil     pgtype.Date        `json:"retention_until"`
	OriginalName       string             `json:"original_name"`
	StoredName         string             `json:"stored_name"`
	MimeType           string             `json:"mime_type"`
	FileSize           int64              `json:"file_size"`
	ChecksumSha256     string             `json:"checksum_sha256"`
	UploadedByUserID   pgtype.UUID        `json:"uploaded_by_user_id"`
	UploadedByUsername string             `json:"uploaded_by_username"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListArchiveDocuments(ctx context.Context, arg ListArchiveDocumentsParams) ([]ListArchiveDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listArchiveDocuments,
		arg.Search,
		arg.CategoryID,
		arg.Status,
		arg.ClassificationCode,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArchiveDocumentsRow{}
	for rows.Next() {
		var i ListArchiveDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.CategoryCode,
			&i.CategoryName,
			&i.ClassificationCode,
			&i.Title,
			&i.ArchiveNumber,
			&i.DocumentDate,
			&i.ReceivedDate,
			&i.Summary,
			&i.Tags,
			&i.Status,
			&i.StorageLocation,
			&i.RetentionUntil,
			&i.OriginalName,
			&i.StoredName,
			&i.MimeType,
			&i.FileSize,
			&i.ChecksumSha256,
			&i.UploadedByUserID,
			&i.UploadedByUsername,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArchiveCategory = `-- name: UpdateArchiveCategory :one
UPDATE archive_categories
SET code = $1,
    name = $2,
    classification_code = NULLIF($3::TEXT, ''),
    description = $4,
    retention_years = $5,
    is_active = $6,
    updated_at = NOW()
WHERE id = $7
RETURNING id, code, name, classification_code, description, retention_years, is_active, created_at, updated_at
`

type UpdateArchiveCategoryParams struct {
	Code               string      `json:"code"`
	Name               string      `json:"name"`
	ClassificationCode string      `json:"classification_code"`
	Description        string      `json:"description"`
	RetentionYears     int32       `json:"retention_years"`
	IsActive           bool        `json:"is_active"`
	ID                 pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateArchiveCategory(ctx context.Context, arg UpdateArchiveCategoryParams) (ArchiveCategory, error) {
	row := q.db.QueryRow(ctx, updateArchiveCategory,
		arg.Code,
		arg.Name,
		arg.ClassificationCode,
		arg.Description,
		arg.RetentionYears,
		arg.IsActive,
		arg.ID,
	)
	var i ArchiveCategory
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.ClassificationCode,
		&i.Description,
		&i.RetentionYears,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateArchiveDocument = `-- name: UpdateArchiveDocument :one
UPDATE archive_documents
SET category_id = $2,
    title = $3,
    archive_number = $4,
    document_date = $5,
    received_date = $6,
    summary = $7,
    tags = $8,
    status = $9,
    storage_location = $10,
    retention_until = $11,
    updated_at = NOW()
WHERE id = $1
RETURNING id, category_id, title, archive_number, document_date, received_date, summary, tags, status, storage_location, retention_until, original_name, stored_name, file_path, mime_type, file_size, checksum_sha256, uploaded_by_user_id, created_at, updated_at
`

type UpdateArchiveDocumentParams struct {
	ID              pgtype.UUID `json:"id"`
	CategoryID      pgtype.UUID `json:"category_id"`
	Title           string      `json:"title"`
	ArchiveNumber   string      `json:"archive_number"`
	DocumentDate    pgtype.Date `json:"document_date"`
	ReceivedDate    pgtype.Date `json:"received_date"`
	Summary         string      `json:"summary"`
	Tags            string      `json:"tags"`
	Status          string      `json:"status"`
	StorageLocation string      `json:"storage_location"`
	RetentionUntil  pgtype.Date `json:"retention_until"`
}

func (q *Queries) UpdateArchiveDocument(ctx context.Context, arg UpdateArchiveDocumentParams) (ArchiveDocument, error) {
	row := q.db.QueryRow(ctx, updateArchiveDocument,
		arg.ID,
		arg.CategoryID,
		arg.Title,
		arg.ArchiveNumber,
		arg.DocumentDate,
		arg.ReceivedDate,
		arg.Summary,
		arg.Tags,
		arg.Status,
		arg.StorageLocation,
		arg.RetentionUntil,
	)
	var i ArchiveDocument
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Title,
		&i.ArchiveNumber,
		&i.DocumentDate,
		&i.ReceivedDate,
		&i.Summary,
		&i.Tags,
		&i.Status,
		&i.StorageLocation,
		&i.RetentionUntil,
		&i.OriginalName,
		&i.StoredName,
		&i.FilePath,
		&i.MimeType,
		&i.FileSize,
		&i.ChecksumSha256,
		&i.UploadedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
