// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cbt_questions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCbtQuestionsFiltered = `-- name: CountCbtQuestionsFiltered :one
SELECT COUNT(*)::bigint
FROM cbt_questions q
WHERE (
    ($1::text = 'global' AND q.event_id IS NULL)
    OR (
      $1::text = 'event_pool'
      AND (q.event_id IS NULL OR ($2::uuid IS NOT NULL AND q.event_id = $2::uuid))
    )
    OR (
      $1::text NOT IN ('global', 'event_pool')
      AND ($2::uuid IS NULL OR q.event_id = $2::uuid)
    )
  )
  AND ($3::uuid IS NULL OR q.subject_id = $3::uuid)
  AND ($4::text = '' OR q.author_username = $4::text)
  AND ($5::text = '' OR q.workflow_status = $5::text)
  AND ($6::text = '' OR q.status = $6::cbt_question_status_enum)
  AND ($7::text = '' OR q.question_type = $7::text)
  AND ($8::text = '' OR ($8::text = 'yes' AND q.hots_flag = TRUE) OR ($8::text = 'no' AND q.hots_flag = FALSE))
  AND (
    $9::bool
    OR q.status = 'published'
    OR q.author_username = $10::text
    OR EXISTS (
      SELECT 1 FROM cbt_event_members m
      WHERE m.event_id = q.event_id
        AND m.user_id = $11::uuid
        AND m.role IN ('reviewer', 'panitia')
        AND (m.subject_id IS NULL OR m.subject_id = q.subject_id)
    )
  )
  AND (
    $12::text = ''
    OR (
      $12::text = 'item_analysis'
      AND q.workflow_status = 'rejected'
      AND q.review_notes ILIKE '%analisis butir%'
    )
    OR (
      $12::text = 'reviewer'
      AND q.workflow_status = 'rejected'
      AND q.review_notes NOT ILIKE '%analisis butir%'
      AND btrim(q.reviewer_username) <> ''
    )
    OR (
      $12::text = 'workflow'
      AND q.workflow_status = 'rejected'
      AND q.review_notes NOT ILIKE '%analisis butir%'
      AND btrim(q.reviewer_username) = ''
    )
  )
  AND (
    $13::text = ''
    OR q.code ILIKE '%' || $13::text || '%'
    OR q.question_text ILIKE '%' || $13::text || '%'
    OR q.material_topic ILIKE '%' || $13::text || '%'
    OR q.cp_ref ILIKE '%' || $13::text || '%'
    OR q.kd_ref ILIKE '%' || $13::text || '%'
  )
`

type CountCbtQuestionsFilteredParams struct {
	ScopeFilter    string      `json:"scope_filter"`
	EventID        pgtype.UUID `json:"event_id"`
	SubjectID      pgtype.UUID `json:"subject_id"`
	AuthorUsername string      `json:"author_username"`
	WorkflowStatus string      `json:"workflow_status"`
	StatusFilter   string      `json:"status_filter"`
	QuestionType   string      `json:"question_type"`
	HotsFilter     string      `json:"hots_filter"`
	IsAdmin        bool        `json:"is_admin"`
	ActorUsername  string      `json:"actor_username"`
	ActorUserID    pgtype.UUID `json:"actor_user_id"`
	RevisionSource string      `json:"revision_source"`
	SearchQuery    string      `json:"search_query"`
}

func (q *Queries) CountCbtQuestionsFiltered(ctx context.Context, arg CountCbtQuestionsFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCbtQuestionsFiltered,
		arg.ScopeFilter,
		arg.EventID,
		arg.SubjectID,
		arg.AuthorUsername,
		arg.WorkflowStatus,
		arg.StatusFilter,
		arg.QuestionType,
		arg.HotsFilter,
		arg.IsAdmin,
		arg.ActorUsername,
		arg.ActorUserID,
		arg.RevisionSource,
		arg.SearchQuery,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createCbtQuestion = `-- name: CreateCbtQuestion :one
INSERT INTO cbt_questions (
  id, event_id, subject_id, code, question_text, question_type, options,
  option_a, option_b, option_c, option_d, option_e,
  answer_key, explanation, difficulty, status,
  stem_html, stem_latex, stimulus_html, stimulus_latex,
  explanation_html, rubric_html,
  academic_phase, grade_level,
  cp_ref, tp_ref, kd_ref, indicator_ref,
  material_topic, cognitive_level, hots_flag,
  media_asset_ids, workflow_status, version,
  author_username, reviewer_username, reviewed_at,
  approver_username, approved_at, writer_notes, review_notes
)
VALUES (
  gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15,
  $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31,
  $32, $33, $34, $35, $36, $37, $38, $39, $40
)
RETURNING id, subject_id, code, question_text, option_a, option_b, option_c, option_d, option_e, answer_key, explanation, difficulty, status, created_at, updated_at, question_type, options, stem_html, stem_latex, stimulus_html, stimulus_latex, explanation_html, rubric_html, academic_phase, grade_level, cp_ref, tp_ref, kd_ref, indicator_ref, material_topic, cognitive_level, hots_flag, media_asset_ids, workflow_status, version, author_username, reviewer_username, reviewed_at, approver_username, approved_at, writer_notes, review_notes, event_id
`

type CreateCbtQuestionParams struct {
	EventID          pgtype.UUID               `json:"event_id"`
	SubjectID        pgtype.UUID               `json:"subject_id"`
	Code             string                    `json:"code"`
	QuestionText     string                    `json:"question_text"`
	QuestionType     string                    `json:"question_type"`
	Options          []byte                    `json:"options"`
	OptionA          string                    `json:"option_a"`
	OptionB          string                    `json:"option_b"`
	OptionC          string                    `json:"option_c"`
	OptionD          string                    `json:"option_d"`
	OptionE          string                    `json:"option_e"`
	AnswerKey        string                    `json:"answer_key"`
	Explanation      string                    `json:"explanation"`
	Difficulty       CbtQuestionDifficultyEnum `json:"difficulty"`
	Status           CbtQuestionStatusEnum     `json:"status"`
	StemHtml         string                    `json:"stem_html"`
	StemLatex        string                    `json:"stem_latex"`
	StimulusHtml     string                    `json:"stimulus_html"`
	StimulusLatex    string                    `json:"stimulus_latex"`
	ExplanationHtml  string                    `json:"explanation_html"`
	RubricHtml       string                    `json:"rubric_html"`
	AcademicPhase    string                    `json:"academic_phase"`
	GradeLevel       pgtype.Int2               `json:"grade_level"`
	CpRef            string                    `json:"cp_ref"`
	TpRef            string                    `json:"tp_ref"`
	KdRef            string                    `json:"kd_ref"`
	IndicatorRef     string                    `json:"indicator_ref"`
	MaterialTopic    string                    `json:"material_topic"`
	CognitiveLevel   string                    `json:"cognitive_level"`
	HotsFlag         bool                      `json:"hots_flag"`
	MediaAssetIds    []byte                    `json:"media_asset_ids"`
	WorkflowStatus   string                    `json:"workflow_status"`
	Version          int32                     `json:"version"`
	AuthorUsername   string                    `json:"author_username"`
	ReviewerUsername string                    `json:"reviewer_username"`
	ReviewedAt       pgtype.Timestamptz        `json:"reviewed_at"`
	ApproverUsername string                    `json:"approver_username"`
	ApprovedAt       pgtype.Timestamptz        `json:"approved_at"`
	WriterNotes      string                    `json:"writer_notes"`
	ReviewNotes      string                    `json:"review_notes"`
}

func (q *Queries) CreateCbtQuestion(ctx context.Context, arg CreateCbtQuestionParams) (CbtQuestion, error) {
	row := q.db.QueryRow(ctx, createCbtQuestion,
		arg.EventID,
		arg.SubjectID,
		arg.Code,
		arg.QuestionText,
		arg.QuestionType,
		arg.Options,
		arg.OptionA,
		arg.OptionB,
		arg.OptionC,
		arg.OptionD,
		arg.OptionE,
		arg.AnswerKey,
		arg.Explanation,
		arg.Difficulty,
		arg.Status,
		arg.StemHtml,
		arg.StemLatex,
		arg.StimulusHtml,
		arg.StimulusLatex,
		arg.ExplanationHtml,
		arg.RubricHtml,
		arg.AcademicPhase,
		arg.GradeLevel,
		arg.CpRef,
		arg.TpRef,
		arg.KdRef,
		arg.IndicatorRef,
		arg.MaterialTopic,
		arg.CognitiveLevel,
		arg.HotsFlag,
		arg.MediaAssetIds,
		arg.WorkflowStatus,
		arg.Version,
		arg.AuthorUsername,
		arg.ReviewerUsername,
		arg.ReviewedAt,
		arg.ApproverUsername,
		arg.ApprovedAt,
		arg.WriterNotes,
		arg.ReviewNotes,
	)
	var i CbtQuestion
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Code,
		&i.QuestionText,
		&i.OptionA,
		&i.OptionB,
		&i.OptionC,
		&i.OptionD,
		&i.OptionE,
		&i.AnswerKey,
		&i.Explanation,
		&i.Difficulty,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QuestionType,
		&i.Options,
		&i.StemHtml,
		&i.StemLatex,
		&i.StimulusHtml,
		&i.StimulusLatex,
		&i.ExplanationHtml,
		&i.RubricHtml,
		&i.AcademicPhase,
		&i.GradeLevel,
		&i.CpRef,
		&i.TpRef,
		&i.KdRef,
		&i.IndicatorRef,
		&i.MaterialTopic,
		&i.CognitiveLevel,
		&i.HotsFlag,
		&i.MediaAssetIds,
		&i.WorkflowStatus,
		&i.Version,
		&i.AuthorUsername,
		&i.ReviewerUsername,
		&i.ReviewedAt,
		&i.ApproverUsername,
		&i.ApprovedAt,
		&i.WriterNotes,
		&i.ReviewNotes,
		&i.EventID,
	)
	return i, err
}

const createCbtQuestionAuditLog = `-- name: CreateCbtQuestionAuditLog :one
INSERT INTO cbt_question_audit_logs (question_id, actor_username, action, note, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, question_id, actor_username, action, note, metadata, created_at
`

type CreateCbtQuestionAuditLogParams struct {
	QuestionID    pgtype.UUID `json:"question_id"`
	ActorUsername string      `json:"actor_username"`
	Action        string      `json:"action"`
	Note          string      `json:"note"`
	Metadata      []byte      `json:"metadata"`
}

func (q *Queries) CreateCbtQuestionAuditLog(ctx context.Context, arg CreateCbtQuestionAuditLogParams) (CbtQuestionAuditLog, error) {
	row := q.db.QueryRow(ctx, createCbtQuestionAuditLog,
		arg.QuestionID,
		arg.ActorUsername,
		arg.Action,
		arg.Note,
		arg.Metadata,
	)
	var i CbtQuestionAuditLog
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.ActorUsername,
		&i.Action,
		&i.Note,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCbtQuestion = `-- name: DeleteCbtQuestion :exec
DELETE FROM cbt_questions WHERE id = $1
`

func (q *Queries) DeleteCbtQuestion(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCbtQuestion, id)
	return err
}

const getCbtQuestion = `-- name: GetCbtQuestion :one
SELECT q.id, q.event_id, q.subject_id, q.code, q.question_text, q.question_type, q.options,
       q.option_a, q.option_b, q.option_c, q.option_d, q.option_e,
       q.answer_key, q.explanation, q.difficulty, q.status, q.created_at, q.updated_at,
       q.stem_html, q.stem_latex, q.stimulus_html, q.stimulus_latex,
       q.explanation_html, q.rubric_html,
       q.academic_phase, q.grade_level,
       q.cp_ref, q.tp_ref, q.kd_ref, q.indicator_ref,
       q.material_topic, q.cognitive_level, q.hots_flag,
       q.media_asset_ids, q.workflow_status, q.version,
       q.author_username, q.reviewer_username, q.reviewed_at,
       q.approver_username, q.approved_at, q.writer_notes, q.review_notes,
       COALESCE(pkg_usage.package_count, 0)::int AS package_count,
       COALESCE(answer_usage.answer_count, 0)::int AS answer_count
FROM cbt_questions q
LEFT JOIN LATERAL (
  SELECT COUNT(*)::int AS package_count
  FROM cbt_package_questions pq
  WHERE pq.question_id = q.id
) pkg_usage ON TRUE
LEFT JOIN LATERAL (
  SELECT COUNT(*)::int AS answer_count
  FROM cbt_student_answers sa
  WHERE sa.question_id = q.id
) answer_usage ON TRUE
WHERE q.id = $1
`

type GetCbtQuestionRow struct {
	ID               pgtype.UUID               `json:"id"`
	EventID          pgtype.UUID               `json:"event_id"`
	SubjectID        pgtype.UUID               `json:"subject_id"`
	Code             string                    `json:"code"`
	QuestionText     string                    `json:"question_text"`
	QuestionType     string                    `json:"question_type"`
	Options          []byte                    `json:"options"`
	OptionA          string                    `json:"option_a"`
	OptionB          string                    `json:"option_b"`
	OptionC          string                    `json:"option_c"`
	OptionD          string                    `json:"option_d"`
	OptionE          string                    `json:"option_e"`
	AnswerKey        string                    `json:"answer_key"`
	Explanation      string                    `json:"explanation"`
	Difficulty       CbtQuestionDifficultyEnum `json:"difficulty"`
	Status           CbtQuestionStatusEnum     `json:"status"`
	CreatedAt        pgtype.Timestamptz        `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz        `json:"updated_at"`
	StemHtml         string                    `json:"stem_html"`
	StemLatex        string                    `json:"stem_latex"`
	StimulusHtml     string                    `json:"stimulus_html"`
	StimulusLatex    string                    `json:"stimulus_latex"`
	ExplanationHtml  string                    `json:"explanation_html"`
	RubricHtml       string                    `json:"rubric_html"`
	AcademicPhase    string                    `json:"academic_phase"`
	GradeLevel       pgtype.Int2               `json:"grade_level"`
	CpRef            string                    `json:"cp_ref"`
	TpRef            string                    `json:"tp_ref"`
	KdRef            string                    `json:"kd_ref"`
	IndicatorRef     string                    `json:"indicator_ref"`
	MaterialTopic    string                    `json:"material_topic"`
	CognitiveLevel   string                    `json:"cognitive_level"`
	HotsFlag         bool                      `json:"hots_flag"`
	MediaAssetIds    []byte                    `json:"media_asset_ids"`
	WorkflowStatus   string                    `json:"workflow_status"`
	Version          int32                     `json:"version"`
	AuthorUsername   string                    `json:"author_username"`
	ReviewerUsername string                    `json:"reviewer_username"`
	ReviewedAt       pgtype.Timestamptz        `json:"reviewed_at"`
	ApproverUsername string                    `json:"approver_username"`
	ApprovedAt       pgtype.Timestamptz        `json:"approved_at"`
	WriterNotes      string                    `json:"writer_notes"`
	ReviewNotes      string                    `json:"review_notes"`
	PackageCount     int32                     `json:"package_count"`
	AnswerCount      int32                     `json:"answer_count"`
}

func (q *Queries) GetCbtQuestion(ctx context.Context, id pgtype.UUID) (GetCbtQuestionRow, error) {
	row := q.db.QueryRow(ctx, getCbtQuestion, id)
	var i GetCbtQuestionRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.SubjectID,
		&i.Code,
		&i.QuestionText,
		&i.QuestionType,
		&i.Options,
		&i.OptionA,
		&i.OptionB,
		&i.OptionC,
		&i.OptionD,
		&i.OptionE,
		&i.AnswerKey,
		&i.Explanation,
		&i.Difficulty,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StemHtml,
		&i.StemLatex,
		&i.StimulusHtml,
		&i.StimulusLatex,
		&i.ExplanationHtml,
		&i.RubricHtml,
		&i.AcademicPhase,
		&i.GradeLevel,
		&i.CpRef,
		&i.TpRef,
		&i.KdRef,
		&i.IndicatorRef,
		&i.MaterialTopic,
		&i.CognitiveLevel,
		&i.HotsFlag,
		&i.MediaAssetIds,
		&i.WorkflowStatus,
		&i.Version,
		&i.AuthorUsername,
		&i.ReviewerUsername,
		&i.ReviewedAt,
		&i.ApproverUsername,
		&i.ApprovedAt,
		&i.WriterNotes,
		&i.ReviewNotes,
		&i.PackageCount,
		&i.AnswerCount,
	)
	return i, err
}

const getCbtQuestionDetail = `-- name: GetCbtQuestionDetail :one
SELECT q.id, q.event_id, q.subject_id, s.name AS subject_name, s.code AS subject_code,
       q.code, q.question_text, q.question_type, q.options,
       q.option_a, q.option_b, q.option_c, q.option_d, q.option_e,
       q.answer_key, q.explanation, q.difficulty, q.status, q.created_at, q.updated_at,
       q.stem_html, q.stem_latex, q.stimulus_html, q.stimulus_latex,
       q.explanation_html, q.rubric_html,
       q.academic_phase, q.grade_level,
       q.cp_ref, q.tp_ref, q.kd_ref, q.indicator_ref,
       q.material_topic, q.cognitive_level, q.hots_flag,
       q.media_asset_ids, q.workflow_status, q.version,
       q.author_username, q.reviewer_username, q.reviewed_at,
       q.approver_username, q.approved_at, q.writer_notes, q.review_notes,
       COALESCE(pkg_usage.package_count, 0)::int AS package_count,
       COALESCE(answer_usage.answer_count, 0)::int AS answer_count
FROM cbt_questions q
JOIN subjects s ON s.id = q.subject_id
LEFT JOIN LATERAL (
  SELECT COUNT(*)::int AS package_count
  FROM cbt_package_questions pq
  WHERE pq.question_id = q.id
) pkg_usage ON TRUE
LEFT JOIN LATERAL (
  SELECT COUNT(*)::int AS answer_count
  FROM cbt_student_answers sa
  WHERE sa.question_id = q.id
) answer_usage ON TRUE
WHERE q.id = $1
`

type GetCbtQuestionDetailRow struct {
	ID               pgtype.UUID               `json:"id"`
	EventID          pgtype.UUID               `json:"event_id"`
	SubjectID        pgtype.UUID               `json:"subject_id"`
	SubjectName      string                    `json:"subject_name"`
	SubjectCode      string                    `json:"subject_code"`
	Code             string                    `json:"code"`
	QuestionText     string                    `json:"question_text"`
	QuestionType     string                    `json:"question_type"`
	Options          []byte                    `json:"options"`
	OptionA          string                    `json:"option_a"`
	OptionB          string                    `json:"option_b"`
	OptionC          string                    `json:"option_c"`
	OptionD          string                    `json:"option_d"`
	OptionE          string                    `json:"option_e"`
	AnswerKey        string                    `json:"answer_key"`
	Explanation      string                    `json:"explanation"`
	Difficulty       CbtQuestionDifficultyEnum `json:"difficulty"`
	Status           CbtQuestionStatusEnum     `json:"status"`
	CreatedAt        pgtype.Timestamptz        `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz        `json:"updated_at"`
	StemHtml         string                    `json:"stem_html"`
	StemLatex        string                    `json:"stem_latex"`
	StimulusHtml     string                    `json:"stimulus_html"`
	StimulusLatex    string                    `json:"stimulus_latex"`
	ExplanationHtml  string                    `json:"explanation_html"`
	RubricHtml       string                    `json:"rubric_html"`
	AcademicPhase    string                    `json:"academic_phase"`
	GradeLevel       pgtype.Int2               `json:"grade_level"`
	CpRef            string                    `json:"cp_ref"`
	TpRef            string                    `json:"tp_ref"`
	KdRef            string                    `json:"kd_ref"`
	IndicatorRef     string                    `json:"indicator_ref"`
	MaterialTopic    string                    `json:"material_topic"`
	CognitiveLevel   string                    `json:"cognitive_level"`
	HotsFlag         bool                      `json:"hots_flag"`
	MediaAssetIds    []byte                    `json:"media_asset_ids"`
	WorkflowStatus   string                    `json:"workflow_status"`
	Version          int32                     `json:"version"`
	AuthorUsername   string                    `json:"author_username"`
	ReviewerUsername string                    `json:"reviewer_username"`
	ReviewedAt       pgtype.Timestamptz        `json:"reviewed_at"`
	ApproverUsername string                    `json:"approver_username"`
	ApprovedAt       pgtype.Timestamptz        `json:"approved_at"`
	WriterNotes      string                    `json:"writer_notes"`
	ReviewNotes      string                    `json:"review_notes"`
	PackageCount     int32                     `json:"package_count"`
	AnswerCount      int32                     `json:"answer_count"`
}

func (q *Queries) GetCbtQuestionDetail(ctx context.Context, id pgtype.UUID) (GetCbtQuestionDetailRow, error) {
	row := q.db.QueryRow(ctx, getCbtQuestionDetail, id)
	var i GetCbtQuestionDetailRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.SubjectID,
		&i.SubjectName,
		&i.SubjectCode,
		&i.Code,
		&i.QuestionText,
		&i.QuestionType,
		&i.Options,
		&i.OptionA,
		&i.OptionB,
		&i.OptionC,
		&i.OptionD,
		&i.OptionE,
		&i.AnswerKey,
		&i.Explanation,
		&i.Difficulty,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StemHtml,
		&i.StemLatex,
		&i.StimulusHtml,
		&i.StimulusLatex,
		&i.ExplanationHtml,
		&i.RubricHtml,
		&i.AcademicPhase,
		&i.GradeLevel,
		&i.CpRef,
		&i.TpRef,
		&i.KdRef,
		&i.IndicatorRef,
		&i.MaterialTopic,
		&i.CognitiveLevel,
		&i.HotsFlag,
		&i.MediaAssetIds,
		&i.WorkflowStatus,
		&i.Version,
		&i.AuthorUsername,
		&i.ReviewerUsername,
		&i.ReviewedAt,
		&i.ApproverUsername,
		&i.ApprovedAt,
		&i.WriterNotes,
		&i.ReviewNotes,
		&i.PackageCount,
		&i.AnswerCount,
	)
	return i, err
}

const listCbtQuestionStemTextsBySubject = `-- name: ListCbtQuestionStemTextsBySubject :many
SELECT question_text, stem_html
FROM cbt_questions
WHERE subject_id = $1
`

type ListCbtQuestionStemTextsBySubjectRow struct {
	QuestionText string `json:"question_text"`
	StemHtml     string `json:"stem_html"`
}

func (q *Queries) ListCbtQuestionStemTextsBySubject(ctx context.Context, subjectID pgtype.UUID) ([]ListCbtQuestionStemTextsBySubjectRow, error) {
	rows, err := q.db.Query(ctx, listCbtQuestionStemTextsBySubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCbtQuestionStemTextsBySubjectRow{}
	for rows.Next() {
		var i ListCbtQuestionStemTextsBySubjectRow
		if err := rows.Scan(&i.QuestionText, &i.StemHtml); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCbtQuestionTimeline = `-- name: ListCbtQuestionTimeline :many
SELECT id, question_id, actor_username, action, note, metadata, created_at
FROM cbt_question_audit_logs
WHERE question_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListCbtQuestionTimeline(ctx context.Context, questionID pgtype.UUID) ([]CbtQuestionAuditLog, error) {
	rows, err := q.db.Query(ctx, listCbtQuestionTimeline, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CbtQuestionAuditLog{}
	for rows.Next() {
		var i CbtQuestionAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.ActorUsername,
			&i.Action,
			&i.Note,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCbtQuestions = `-- name: ListCbtQuestions :many
SELECT q.id, q.event_id, q.subject_id, s.name AS subject_name, s.code AS subject_code,
       q.code, q.question_text, q.question_type, q.options,
       q.option_a, q.option_b, q.option_c, q.option_d, q.option_e,
       CASE
         WHEN $1::bool
           OR q.author_username = $2::text
           OR EXISTS (
             SELECT 1 FROM cbt_event_members m
             WHERE m.event_id = q.event_id
               AND m.user_id = $3::uuid
               AND m.role IN ('reviewer', 'panitia')
               AND (m.subject_id IS NULL OR m.subject_id = q.subject_id)
           )
         THEN q.answer_key ELSE '' END AS answer_key,
       q.explanation, q.difficulty, q.status, q.created_at, q.updated_at,
       q.stem_html, q.stem_latex, q.stimulus_html, q.stimulus_latex,
       q.explanation_html, q.rubric_html,
       q.academic_phase, q.grade_level,
       q.cp_ref, q.tp_ref, q.kd_ref, q.indicator_ref,
       q.material_topic, q.cognitive_level, q.hots_flag,
       q.media_asset_ids, q.workflow_status, q.version,
       q.author_username, q.reviewer_username, q.reviewed_at,
       q.approver_username, q.approved_at, q.writer_notes, q.review_notes,
       COALESCE(pkg_usage.package_count, 0)::int AS package_count,
       COALESCE(answer_usage.answer_count, 0)::int AS answer_count
FROM cbt_questions q
JOIN subjects s ON s.id = q.subject_id
LEFT JOIN LATERAL (
  SELECT COUNT(*)::int AS package_count
  FROM cbt_package_questions pq
  WHERE pq.question_id = q.id
) pkg_usage ON TRUE
LEFT JOIN LATERAL (
  SELECT COUNT(*)::int AS answer_count
  FROM cbt_student_answers sa
  WHERE sa.question_id = q.id
) answer_usage ON TRUE
ORDER BY q.created_at DESC
`

type ListCbtQuestionsParams struct {
	IsAdmin       bool        `json:"is_admin"`
	ActorUsername string      `json:"actor_username"`
	ActorUserID   pgtype.UUID `json:"actor_user_id"`
}

type ListCbtQuestionsRow struct {
	ID               pgtype.UUID               `json:"id"`
	EventID          pgtype.UUID               `json:"event_id"`
	SubjectID        pgtype.UUID               `json:"subject_id"`
	SubjectName      string                    `json:"subject_name"`
	SubjectCode      string                    `json:"subject_code"`
	Code             string                    `json:"code"`
	QuestionText     string                    `json:"question_text"`
	QuestionType     string                    `json:"question_type"`
	Options          []byte                    `json:"options"`
	OptionA          string                    `json:"option_a"`
	OptionB          string                    `json:"option_b"`
	OptionC          string                    `json:"option_c"`
	OptionD          string                    `json:"option_d"`
	OptionE          string                    `json:"option_e"`
	AnswerKey        string                    `json:"answer_key"`
	Explanation      string                    `json:"explanation"`
	Difficulty       CbtQuestionDifficultyEnum `json:"difficulty"`
	Status           CbtQuestionStatusEnum     `json:"status"`
	CreatedAt        pgtype.Timestamptz        `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz        `json:"updated_at"`
	StemHtml         string                    `json:"stem_html"`
	StemLatex        string                    `json:"stem_latex"`
	StimulusHtml     string                    `json:"stimulus_html"`
	StimulusLatex    string                    `json:"stimulus_latex"`
	ExplanationHtml  string                    `json:"explanation_html"`
	RubricHtml       string                    `json:"rubric_html"`
	AcademicPhase    string                    `json:"academic_phase"`
	GradeLevel       pgtype.Int2               `json:"grade_level"`
	CpRef            string                    `json:"cp_ref"`
	TpRef            string                    `json:"tp_ref"`
	KdRef            string                    `json:"kd_ref"`
	IndicatorRef     string                    `json:"indicator_ref"`
	MaterialTopic    string                    `json:"material_topic"`
	CognitiveLevel   string                    `json:"cognitive_level"`
	HotsFlag         bool                      `json:"hots_flag"`
	MediaAssetIds    []byte                    `json:"media_asset_ids"`
	WorkflowStatus   string                    `json:"workflow_status"`
	Version          int32                     `json:"version"`
	AuthorUsername   string                    `json:"author_username"`
	ReviewerUsername string                    `json:"reviewer_username"`
	ReviewedAt       pgtype.Timestamptz        `json:"reviewed_at"`
	ApproverUsername string                    `json:"approver_username"`
	ApprovedAt       pgtype.Timestamptz        `json:"approved_at"`
	WriterNotes      string                    `json:"writer_notes"`
	ReviewNotes      string                    `json:"review_notes"`
	PackageCount     int32                     `json:"package_count"`
	AnswerCount      int32                     `json:"answer_count"`
}

func (q *Queries) ListCbtQuestions(ctx context.Context, arg ListCbtQuestionsParams) ([]ListCbtQuestionsRow, error) {
	rows, err := q.db.Query(ctx, listCbtQuestions, arg.IsAdmin, arg.ActorUsername, arg.ActorUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCbtQuestionsRow{}
	for rows.Next() {
		var i ListCbtQuestionsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.SubjectID,
			&i.SubjectName,
			&i.SubjectCode,
			&i.Code,
			&i.QuestionText,
			&i.QuestionType,
			&i.Options,
			&i.OptionA,
			&i.OptionB,
			&i.OptionC,
			&i.OptionD,
			&i.OptionE,
			&i.AnswerKey,
			&i.Explanation,
			&i.Difficulty,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StemHtml,
			&i.StemLatex,
			&i.StimulusHtml,
			&i.StimulusLatex,
			&i.ExplanationHtml,
			&i.RubricHtml,
			&i.AcademicPhase,
			&i.GradeLevel,
			&i.CpRef,
			&i.TpRef,
			&i.KdRef,
			&i.IndicatorRef,
			&i.MaterialTopic,
			&i.CognitiveLevel,
			&i.HotsFlag,
			&i.MediaAssetIds,
			&i.WorkflowStatus,
			&i.Version,
			&i.AuthorUsername,
			&i.ReviewerUsername,
			&i.ReviewedAt,
			&i.ApproverUsername,
			&i.ApprovedAt,
			&i.WriterNotes,
			&i.ReviewNotes,
			&i.PackageCount,
			&i.AnswerCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCbtQuestionsFiltered = `-- name: ListCbtQuestionsFiltered :many
SELECT q.id, q.event_id, q.subject_id, s.name AS subject_name, s.code AS subject_code,
       q.code, q.question_text, q.question_type, q.options,
       q.option_a, q.option_b, q.option_c, q.option_d, q.option_e,
       CASE
         WHEN $1::bool
           OR q.author_username = $2::text
           OR EXISTS (
             SELECT 1 FROM cbt_event_members m
             WHERE m.event_id = q.event_id
               AND m.user_id = $3::uuid
               AND m.role IN ('reviewer', 'panitia')
               AND (m.subject_id IS NULL OR m.subject_id = q.subject_id)
           )
         THEN q.answer_key ELSE '' END AS answer_key,
       q.explanation, q.difficulty, q.status, q.created_at, q.updated_at,
       q.stem_html, q.stem_latex, q.stimulus_html, q.stimulus_latex,
       q.explanation_html, q.rubric_html,
       q.academic_phase, q.grade_level,
       q.cp_ref, q.tp_ref, q.kd_ref, q.indicator_ref,
       q.material_topic, q.cognitive_level, q.hots_flag,
       q.media_asset_ids, q.workflow_status, q.version,
       q.author_username, q.reviewer_username, q.reviewed_at,
       q.approver_username, q.approved_at, q.writer_notes, q.review_notes,
       COALESCE(pkg_usage.package_count, 0)::int AS package_count,
       COALESCE(answer_usage.answer_count, 0)::int AS answer_count
FROM cbt_questions q
JOIN subjects s ON s.id = q.subject_id
LEFT JOIN LATERAL (
  SELECT COUNT(*)::int AS package_count
  FROM cbt_package_questions pq
  WHERE pq.question_id = q.id
) pkg_usage ON TRUE
LEFT JOIN LATERAL (
  SELECT COUNT(*)::int AS answer_count
  FROM cbt_student_answers sa
  WHERE sa.question_id = q.id
) answer_usage ON TRUE
WHERE (
    ($4::text = 'global' AND q.event_id IS NULL)
    OR (
      $4::text = 'event_pool'
      AND (q.event_id IS NULL OR ($5::uuid IS NOT NULL AND q.event_id = $5::uuid))
    )
    OR (
      $4::text NOT IN ('global', 'event_pool')
      AND ($5::uuid IS NULL OR q.event_id = $5::uuid)
    )
  )
  AND ($6::uuid IS NULL OR q.subject_id = $6::uuid)
  AND ($7::text = '' OR q.author_username = $7::text)
  AND ($8::text = '' OR q.workflow_status = $8::text)
  AND ($9::text = '' OR q.status = $9::cbt_question_status_enum)
  AND ($10::text = '' OR q.question_type = $10::text)
  AND ($11::text = '' OR ($11::text = 'yes' AND q.hots_flag = TRUE) OR ($11::text = 'no' AND q.hots_flag = FALSE))
  AND (
    $1::bool
    OR q.status = 'published'
    OR q.author_username = $2::text
    OR EXISTS (
      SELECT 1 FROM cbt_event_members m
      WHERE m.event_id = q.event_id
        AND m.user_id = $3::uuid
        AND m.role IN ('reviewer', 'panitia')
        AND (m.subject_id IS NULL OR m.subject_id = q.subject_id)
    )
  )
  AND (
    $12::text = ''
    OR (
      $12::text = 'item_analysis'
      AND q.workflow_status = 'rejected'
      AND q.review_notes ILIKE '%analisis butir%'
    )
    OR (
      $12::text = 'reviewer'
      AND q.workflow_status = 'rejected'
      AND q.review_notes NOT ILIKE '%analisis butir%'
      AND btrim(q.reviewer_username) <> ''
    )
    OR (
      $12::text = 'workflow'
      AND q.workflow_status = 'rejected'
      AND q.review_notes NOT ILIKE '%analisis butir%'
      AND btrim(q.reviewer_username) = ''
    )
  )
  AND (
    $13::text = ''
    OR q.code ILIKE '%' || $13::text || '%'
    OR q.question_text ILIKE '%' || $13::text || '%'
    OR q.material_topic ILIKE '%' || $13::text || '%'
    OR q.cp_ref ILIKE '%' || $13::text || '%'
    OR q.kd_ref ILIKE '%' || $13::text || '%'
  )
ORDER BY q.created_at DESC
LIMIT $15 OFFSET $14
`

type ListCbtQuestionsFilteredParams struct {
	IsAdmin        bool        `json:"is_admin"`
	ActorUsername  string      `json:"actor_username"`
	ActorUserID    pgtype.UUID `json:"actor_user_id"`
	ScopeFilter    string      `json:"scope_filter"`
	EventID        pgtype.UUID `json:"event_id"`
	SubjectID      pgtype.UUID `json:"subject_id"`
	AuthorUsername string      `json:"author_username"`
	WorkflowStatus string      `json:"workflow_status"`
	StatusFilter   string      `json:"status_filter"`
	QuestionType   string      `json:"question_type"`
	HotsFilter     string      `json:"hots_filter"`
	RevisionSource string      `json:"revision_source"`
	SearchQuery    string      `json:"search_query"`
	OffsetCount    int32       `json:"offset_count"`
	LimitCount     int32       `json:"limit_count"`
}

type ListCbtQuestionsFilteredRow struct {
	ID               pgtype.UUID               `json:"id"`
	EventID          pgtype.UUID               `json:"event_id"`
	SubjectID        pgtype.UUID               `json:"subject_id"`
	SubjectName      string                    `json:"subject_name"`
	SubjectCode      string                    `json:"subject_code"`
	Code             string                    `json:"code"`
	QuestionText     string                    `json:"question_text"`
	QuestionType     string                    `json:"question_type"`
	Options          []byte                    `json:"options"`
	OptionA          string                    `json:"option_a"`
	OptionB          string                    `json:"option_b"`
	OptionC          string                    `json:"option_c"`
	OptionD          string                    `json:"option_d"`
	OptionE          string                    `json:"option_e"`
	AnswerKey        string                    `json:"answer_key"`
	Explanation      string                    `json:"explanation"`
	Difficulty       CbtQuestionDifficultyEnum `json:"difficulty"`
	Status           CbtQuestionStatusEnum     `json:"status"`
	CreatedAt        pgtype.Timestamptz        `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz        `json:"updated_at"`
	StemHtml         string                    `json:"stem_html"`
	StemLatex        string                    `json:"stem_latex"`
	StimulusHtml     string                    `json:"stimulus_html"`
	StimulusLatex    string                    `json:"stimulus_latex"`
	ExplanationHtml  string                    `json:"explanation_html"`
	RubricHtml       string                    `json:"rubric_html"`
	AcademicPhase    string                    `json:"academic_phase"`
	GradeLevel       pgtype.Int2               `json:"grade_level"`
	CpRef            string                    `json:"cp_ref"`
	TpRef            string                    `json:"tp_ref"`
	KdRef            string                    `json:"kd_ref"`
	IndicatorRef     string                    `json:"indicator_ref"`
	MaterialTopic    string                    `json:"material_topic"`
	CognitiveLevel   string                    `json:"cognitive_level"`
	HotsFlag         bool                      `json:"hots_flag"`
	MediaAssetIds    []byte                    `json:"media_asset_ids"`
	WorkflowStatus   string                    `json:"workflow_status"`
	Version          int32                     `json:"version"`
	AuthorUsername   string                    `json:"author_username"`
	ReviewerUsername string                    `json:"reviewer_username"`
	ReviewedAt       pgtype.Timestamptz        `json:"reviewed_at"`
	ApproverUsername string                    `json:"approver_username"`
	ApprovedAt       pgtype.Timestamptz        `json:"approved_at"`
	WriterNotes      string                    `json:"writer_notes"`
	ReviewNotes      string                    `json:"review_notes"`
	PackageCount     int32                     `json:"package_count"`
	AnswerCount      int32                     `json:"answer_count"`
}

func (q *Queries) ListCbtQuestionsFiltered(ctx context.Context, arg ListCbtQuestionsFilteredParams) ([]ListCbtQuestionsFilteredRow, error) {
	rows, err := q.db.Query(ctx, listCbtQuestionsFiltered,
		arg.IsAdmin,
		arg.ActorUsername,
		arg.ActorUserID,
		arg.ScopeFilter,
		arg.EventID,
		arg.SubjectID,
		arg.AuthorUsername,
		arg.WorkflowStatus,
		arg.StatusFilter,
		arg.QuestionType,
		arg.HotsFilter,
		arg.RevisionSource,
		arg.SearchQuery,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCbtQuestionsFilteredRow{}
	for rows.Next() {
		var i ListCbtQuestionsFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.SubjectID,
			&i.SubjectName,
			&i.SubjectCode,
			&i.Code,
			&i.QuestionText,
			&i.QuestionType,
			&i.Options,
			&i.OptionA,
			&i.OptionB,
			&i.OptionC,
			&i.OptionD,
			&i.OptionE,
			&i.AnswerKey,
			&i.Explanation,
			&i.Difficulty,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StemHtml,
			&i.StemLatex,
			&i.StimulusHtml,
			&i.StimulusLatex,
			&i.ExplanationHtml,
			&i.RubricHtml,
			&i.AcademicPhase,
			&i.GradeLevel,
			&i.CpRef,
			&i.TpRef,
			&i.KdRef,
			&i.IndicatorRef,
			&i.MaterialTopic,
			&i.CognitiveLevel,
			&i.HotsFlag,
			&i.MediaAssetIds,
			&i.WorkflowStatus,
			&i.Version,
			&i.AuthorUsername,
			&i.ReviewerUsername,
			&i.ReviewedAt,
			&i.ApproverUsername,
			&i.ApprovedAt,
			&i.WriterNotes,
			&i.ReviewNotes,
			&i.PackageCount,
			&i.AnswerCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCbtQuestionsScoped = `-- name: ListCbtQuestionsScoped :many
SELECT q.id, q.event_id, q.subject_id, s.name AS subject_name, s.code AS subject_code,
       q.code, q.question_text, q.question_type, q.options,
       q.option_a, q.option_b, q.option_c, q.option_d, q.option_e,
       CASE
         WHEN $1::bool
           OR q.author_username = $2::text
           OR EXISTS (
             SELECT 1 FROM cbt_event_members m
             WHERE m.event_id = q.event_id
               AND m.user_id = $3::uuid
               AND m.role IN ('reviewer', 'panitia')
               AND (m.subject_id IS NULL OR m.subject_id = q.subject_id)
           )
         THEN q.answer_key ELSE '' END AS answer_key,
       q.explanation, q.difficulty, q.status, q.created_at, q.updated_at,
       q.stem_html, q.stem_latex, q.stimulus_html, q.stimulus_latex,
       q.explanation_html, q.rubric_html,
       q.academic_phase, q.grade_level,
       q.cp_ref, q.tp_ref, q.kd_ref, q.indicator_ref,
       q.material_topic, q.cognitive_level, q.hots_flag,
       q.media_asset_ids, q.workflow_status, q.version,
       q.author_username, q.reviewer_username, q.reviewed_at,
       q.approver_username, q.approved_at, q.writer_notes, q.review_notes,
       COALESCE(pkg_usage.package_count, 0)::int AS package_count,
       COALESCE(answer_usage.answer_count, 0)::int AS answer_count
FROM cbt_questions q
JOIN subjects s ON s.id = q.subject_id
LEFT JOIN LATERAL (
  SELECT COUNT(*)::int AS package_count
  FROM cbt_package_questions pq
  WHERE pq.question_id = q.id
) pkg_usage ON TRUE
LEFT JOIN LATERAL (
  SELECT COUNT(*)::int AS answer_count
  FROM cbt_student_answers sa
  WHERE sa.question_id = q.id
) answer_usage ON TRUE
WHERE (
    ($4::text = 'global' AND q.event_id IS NULL)
    OR (
      $4::text = 'event_pool'
      AND (q.event_id IS NULL OR ($5::uuid IS NOT NULL AND q.event_id = $5::uuid))
    )
    OR (
      $4::text NOT IN ('global', 'event_pool')
      AND ($5::uuid IS NULL OR q.event_id = $5::uuid)
    )
  )
  AND ($6::uuid IS NULL OR q.subject_id = $6::uuid)
  AND ($7::text = '' OR q.author_username = $7::text)
  AND ($8::text = '' OR q.workflow_status = $8::text)
  AND ($9::text = '' OR q.status = $9::cbt_question_status_enum)
  AND ($10::text = '' OR q.question_type = $10::text)
  AND ($11::text = '' OR ($11::text = 'yes' AND q.hots_flag = TRUE) OR ($11::text = 'no' AND q.hots_flag = FALSE))
  AND (
    $1::bool
    OR q.status = 'published'
    OR q.author_username = $2::text
    OR EXISTS (
      SELECT 1 FROM cbt_event_members m
      WHERE m.event_id = q.event_id
        AND m.user_id = $3::uuid
        AND m.role IN ('reviewer', 'panitia')
        AND (m.subject_id IS NULL OR m.subject_id = q.subject_id)
    )
  )
  AND (
    $12::text = ''
    OR (
      $12::text = 'item_analysis'
      AND q.workflow_status = 'rejected'
      AND q.review_notes ILIKE '%analisis butir%'
    )
    OR (
      $12::text = 'reviewer'
      AND q.workflow_status = 'rejected'
      AND q.review_notes NOT ILIKE '%analisis butir%'
      AND btrim(q.reviewer_username) <> ''
    )
    OR (
      $12::text = 'workflow'
      AND q.workflow_status = 'rejected'
      AND q.review_notes NOT ILIKE '%analisis butir%'
      AND btrim(q.reviewer_username) = ''
    )
  )
  AND (
    $13::text = ''
    OR q.code ILIKE '%' || $13::text || '%'
    OR q.question_text ILIKE '%' || $13::text || '%'
    OR q.material_topic ILIKE '%' || $13::text || '%'
    OR q.cp_ref ILIKE '%' || $13::text || '%'
    OR q.kd_ref ILIKE '%' || $13::text || '%'
  )
ORDER BY q.created_at DESC
LIMIT $15 OFFSET $14
`

type ListCbtQuestionsScopedParams struct {
	IsAdmin        bool        `json:"is_admin"`
	ActorUsername  string      `json:"actor_username"`
	ActorUserID    pgtype.UUID `json:"actor_user_id"`
	ScopeFilter    string      `json:"scope_filter"`
	EventID        pgtype.UUID `json:"event_id"`
	SubjectID      pgtype.UUID `json:"subject_id"`
	AuthorUsername string      `json:"author_username"`
	WorkflowStatus string      `json:"workflow_status"`
	StatusFilter   string      `json:"status_filter"`
	QuestionType   string      `json:"question_type"`
	HotsFilter     string      `json:"hots_filter"`
	RevisionSource string      `json:"revision_source"`
	SearchQuery    string      `json:"search_query"`
	OffsetCount    int32       `json:"offset_count"`
	LimitCount     int32       `json:"limit_count"`
}

type ListCbtQuestionsScopedRow struct {
	ID               pgtype.UUID               `json:"id"`
	EventID          pgtype.UUID               `json:"event_id"`
	SubjectID        pgtype.UUID               `json:"subject_id"`
	SubjectName      string                    `json:"subject_name"`
	SubjectCode      string                    `json:"subject_code"`
	Code             string                    `json:"code"`
	QuestionText     string                    `json:"question_text"`
	QuestionType     string                    `json:"question_type"`
	Options          []byte                    `json:"options"`
	OptionA          string                    `json:"option_a"`
	OptionB          string                    `json:"option_b"`
	OptionC          string                    `json:"option_c"`
	OptionD          string                    `json:"option_d"`
	OptionE          string                    `json:"option_e"`
	AnswerKey        string                    `json:"answer_key"`
	Explanation      string                    `json:"explanation"`
	Difficulty       CbtQuestionDifficultyEnum `json:"difficulty"`
	Status           CbtQuestionStatusEnum     `json:"status"`
	CreatedAt        pgtype.Timestamptz        `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz        `json:"updated_at"`
	StemHtml         string                    `json:"stem_html"`
	StemLatex        string                    `json:"stem_latex"`
	StimulusHtml     string                    `json:"stimulus_html"`
	StimulusLatex    string                    `json:"stimulus_latex"`
	ExplanationHtml  string                    `json:"explanation_html"`
	RubricHtml       string                    `json:"rubric_html"`
	AcademicPhase    string                    `json:"academic_phase"`
	GradeLevel       pgtype.Int2               `json:"grade_level"`
	CpRef            string                    `json:"cp_ref"`
	TpRef            string                    `json:"tp_ref"`
	KdRef            string                    `json:"kd_ref"`
	IndicatorRef     string                    `json:"indicator_ref"`
	MaterialTopic    string                    `json:"material_topic"`
	CognitiveLevel   string                    `json:"cognitive_level"`
	HotsFlag         bool                      `json:"hots_flag"`
	MediaAssetIds    []byte                    `json:"media_asset_ids"`
	WorkflowStatus   string                    `json:"workflow_status"`
	Version          int32                     `json:"version"`
	AuthorUsername   string                    `json:"author_username"`
	ReviewerUsername string                    `json:"reviewer_username"`
	ReviewedAt       pgtype.Timestamptz        `json:"reviewed_at"`
	ApproverUsername string                    `json:"approver_username"`
	ApprovedAt       pgtype.Timestamptz        `json:"approved_at"`
	WriterNotes      string                    `json:"writer_notes"`
	ReviewNotes      string                    `json:"review_notes"`
	PackageCount     int32                     `json:"package_count"`
	AnswerCount      int32                     `json:"answer_count"`
}

func (q *Queries) ListCbtQuestionsScoped(ctx context.Context, arg ListCbtQuestionsScopedParams) ([]ListCbtQuestionsScopedRow, error) {
	rows, err := q.db.Query(ctx, listCbtQuestionsScoped,
		arg.IsAdmin,
		arg.ActorUsername,
		arg.ActorUserID,
		arg.ScopeFilter,
		arg.EventID,
		arg.SubjectID,
		arg.AuthorUsername,
		arg.WorkflowStatus,
		arg.StatusFilter,
		arg.QuestionType,
		arg.HotsFilter,
		arg.RevisionSource,
		arg.SearchQuery,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCbtQuestionsScopedRow{}
	for rows.Next() {
		var i ListCbtQuestionsScopedRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.SubjectID,
			&i.SubjectName,
			&i.SubjectCode,
			&i.Code,
			&i.QuestionText,
			&i.QuestionType,
			&i.Options,
			&i.OptionA,
			&i.OptionB,
			&i.OptionC,
			&i.OptionD,
			&i.OptionE,
			&i.AnswerKey,
			&i.Explanation,
			&i.Difficulty,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StemHtml,
			&i.StemLatex,
			&i.StimulusHtml,
			&i.StimulusLatex,
			&i.ExplanationHtml,
			&i.RubricHtml,
			&i.AcademicPhase,
			&i.GradeLevel,
			&i.CpRef,
			&i.TpRef,
			&i.KdRef,
			&i.IndicatorRef,
			&i.MaterialTopic,
			&i.CognitiveLevel,
			&i.HotsFlag,
			&i.MediaAssetIds,
			&i.WorkflowStatus,
			&i.Version,
			&i.AuthorUsername,
			&i.ReviewerUsername,
			&i.ReviewedAt,
			&i.ApproverUsername,
			&i.ApprovedAt,
			&i.WriterNotes,
			&i.ReviewNotes,
			&i.PackageCount,
			&i.AnswerCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUngradedEssays = `-- name: ListUngradedEssays :many
SELECT
  sa.id AS answer_id,
  sa.participant_id,
  sa.question_id,
  sa.answer,
  sa.manual_score,
  sa.graded_at,
  q.code AS question_code,
  q.question_text,
  q.stem_html,
  q.stimulus_html,
  q.rubric_html,
  COALESCE(pq.points, 1)::numeric AS points,
  s.nis, s.nama,
  COALESCE(r.room_name, '') AS room_name
FROM cbt_student_answers sa
JOIN cbt_questions q ON q.id = sa.question_id
JOIN cbt_exam_participants ep ON ep.id = sa.participant_id
JOIN cbt_exam_sessions ses ON ses.id = ep.session_id
LEFT JOIN cbt_package_questions pq ON pq.package_id = ses.package_id AND pq.question_id = q.id
JOIN students s ON s.id = ep.student_id
LEFT JOIN cbt_exam_rooms r ON r.id = ep.room_id
WHERE ep.session_id = $1
  AND q.question_type = 'essay'
  AND sa.manual_score IS NULL
ORDER BY q.code, s.nama
`

type ListUngradedEssaysRow struct {
	AnswerID      pgtype.UUID        `json:"answer_id"`
	ParticipantID pgtype.UUID        `json:"participant_id"`
	QuestionID    pgtype.UUID        `json:"question_id"`
	Answer        string             `json:"answer"`
	ManualScore   pgtype.Numeric     `json:"manual_score"`
	GradedAt      pgtype.Timestamptz `json:"graded_at"`
	QuestionCode  string             `json:"question_code"`
	QuestionText  string             `json:"question_text"`
	StemHtml      string             `json:"stem_html"`
	StimulusHtml  string             `json:"stimulus_html"`
	RubricHtml    string             `json:"rubric_html"`
	Points        pgtype.Numeric     `json:"points"`
	Nis           string             `json:"nis"`
	Nama          string             `json:"nama"`
	RoomName      string             `json:"room_name"`
}

func (q *Queries) ListUngradedEssays(ctx context.Context, sessionID pgtype.UUID) ([]ListUngradedEssaysRow, error) {
	rows, err := q.db.Query(ctx, listUngradedEssays, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUngradedEssaysRow{}
	for rows.Next() {
		var i ListUngradedEssaysRow
		if err := rows.Scan(
			&i.AnswerID,
			&i.ParticipantID,
			&i.QuestionID,
			&i.Answer,
			&i.ManualScore,
			&i.GradedAt,
			&i.QuestionCode,
			&i.QuestionText,
			&i.StemHtml,
			&i.StimulusHtml,
			&i.RubricHtml,
			&i.Points,
			&i.Nis,
			&i.Nama,
			&i.RoomName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUngradedEssaysByTeacher = `-- name: ListUngradedEssaysByTeacher :many
SELECT
  sa.id AS answer_id,
  sa.participant_id,
  sa.question_id,
  sa.answer,
  sa.manual_score,
  sa.graded_at,
  q.code AS question_code,
  q.question_text,
  q.stem_html,
  q.stimulus_html,
  q.rubric_html,
  COALESCE(pq.points, 1)::numeric AS points,
  s.nis, s.nama,
  COALESCE(r.room_name, '') AS room_name
FROM cbt_student_answers sa
JOIN cbt_questions q ON q.id = sa.question_id
JOIN cbt_exam_participants ep ON ep.id = sa.participant_id
JOIN cbt_exam_sessions ses ON ses.id = ep.session_id
JOIN cbt_packages pkg ON pkg.id = ses.package_id
LEFT JOIN cbt_package_questions pq ON pq.package_id = ses.package_id AND pq.question_id = q.id
JOIN students s ON s.id = ep.student_id
JOIN class_subject_assignments csa
  ON csa.subject_id = pkg.subject_id
 AND csa.class_id = s.class_id
 AND csa.teacher_employee_id = $1
LEFT JOIN cbt_exam_rooms r ON r.id = ep.room_id
WHERE ep.session_id = $2
  AND q.question_type = 'essay'
  AND sa.manual_score IS NULL
ORDER BY q.code, s.nama
`

type ListUngradedEssaysByTeacherParams struct {
	TeacherEmployeeID pgtype.UUID `json:"teacher_employee_id"`
	SessionID         pgtype.UUID `json:"session_id"`
}

type ListUngradedEssaysByTeacherRow struct {
	AnswerID      pgtype.UUID        `json:"answer_id"`
	ParticipantID pgtype.UUID        `json:"participant_id"`
	QuestionID    pgtype.UUID        `json:"question_id"`
	Answer        string             `json:"answer"`
	ManualScore   pgtype.Numeric     `json:"manual_score"`
	GradedAt      pgtype.Timestamptz `json:"graded_at"`
	QuestionCode  string             `json:"question_code"`
	QuestionText  string             `json:"question_text"`
	StemHtml      string             `json:"stem_html"`
	StimulusHtml  string             `json:"stimulus_html"`
	RubricHtml    string             `json:"rubric_html"`
	Points        pgtype.Numeric     `json:"points"`
	Nis           string             `json:"nis"`
	Nama          string             `json:"nama"`
	RoomName      string             `json:"room_name"`
}

func (q *Queries) ListUngradedEssaysByTeacher(ctx context.Context, arg ListUngradedEssaysByTeacherParams) ([]ListUngradedEssaysByTeacherRow, error) {
	rows, err := q.db.Query(ctx, listUngradedEssaysByTeacher, arg.TeacherEmployeeID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUngradedEssaysByTeacherRow{}
	for rows.Next() {
		var i ListUngradedEssaysByTeacherRow
		if err := rows.Scan(
			&i.AnswerID,
			&i.ParticipantID,
			&i.QuestionID,
			&i.Answer,
			&i.ManualScore,
			&i.GradedAt,
			&i.QuestionCode,
			&i.QuestionText,
			&i.StemHtml,
			&i.StimulusHtml,
			&i.RubricHtml,
			&i.Points,
			&i.Nis,
			&i.Nama,
			&i.RoomName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCbtQuestion = `-- name: UpdateCbtQuestion :one
UPDATE cbt_questions
SET
  event_id           = $2,
  subject_id         = $3,
  code               = $4,
  question_text      = $5,
  question_type      = $6,
  options            = $7,
  option_a           = $8,
  option_b           = $9,
  option_c           = $10,
  option_d           = $11,
  option_e           = $12,
  answer_key         = $13,
  explanation        = $14,
  difficulty         = $15,
  status             = $16,
  stem_html          = $17,
  stem_latex         = $18,
  stimulus_html      = $19,
  stimulus_latex     = $20,
  explanation_html   = $21,
  rubric_html        = $22,
  academic_phase     = $23,
  grade_level        = $24,
  cp_ref             = $25,
  tp_ref             = $26,
  kd_ref             = $27,
  indicator_ref      = $28,
  material_topic     = $29,
  cognitive_level    = $30,
  hots_flag          = $31,
  media_asset_ids    = $32,
  workflow_status    = $33,
  version            = version + 1,
  reviewer_username  = $34,
  reviewed_at        = $35,
  approver_username  = $36,
  approved_at        = $37,
  writer_notes       = $38,
  review_notes       = $39,
  updated_at         = NOW()
WHERE id = $1
RETURNING id, subject_id, code, question_text, option_a, option_b, option_c, option_d, option_e, answer_key, explanation, difficulty, status, created_at, updated_at, question_type, options, stem_html, stem_latex, stimulus_html, stimulus_latex, explanation_html, rubric_html, academic_phase, grade_level, cp_ref, tp_ref, kd_ref, indicator_ref, material_topic, cognitive_level, hots_flag, media_asset_ids, workflow_status, version, author_username, reviewer_username, reviewed_at, approver_username, approved_at, writer_notes, review_notes, event_id
`

type UpdateCbtQuestionParams struct {
	ID               pgtype.UUID               `json:"id"`
	EventID          pgtype.UUID               `json:"event_id"`
	SubjectID        pgtype.UUID               `json:"subject_id"`
	Code             string                    `json:"code"`
	QuestionText     string                    `json:"question_text"`
	QuestionType     string                    `json:"question_type"`
	Options          []byte                    `json:"options"`
	OptionA          string                    `json:"option_a"`
	OptionB          string                    `json:"option_b"`
	OptionC          string                    `json:"option_c"`
	OptionD          string                    `json:"option_d"`
	OptionE          string                    `json:"option_e"`
	AnswerKey        string                    `json:"answer_key"`
	Explanation      string                    `json:"explanation"`
	Difficulty       CbtQuestionDifficultyEnum `json:"difficulty"`
	Status           CbtQuestionStatusEnum     `json:"status"`
	StemHtml         string                    `json:"stem_html"`
	StemLatex        string                    `json:"stem_latex"`
	StimulusHtml     string                    `json:"stimulus_html"`
	StimulusLatex    string                    `json:"stimulus_latex"`
	ExplanationHtml  string                    `json:"explanation_html"`
	RubricHtml       string                    `json:"rubric_html"`
	AcademicPhase    string                    `json:"academic_phase"`
	GradeLevel       pgtype.Int2               `json:"grade_level"`
	CpRef            string                    `json:"cp_ref"`
	TpRef            string                    `json:"tp_ref"`
	KdRef            string                    `json:"kd_ref"`
	IndicatorRef     string                    `json:"indicator_ref"`
	MaterialTopic    string                    `json:"material_topic"`
	CognitiveLevel   string                    `json:"cognitive_level"`
	HotsFlag         bool                      `json:"hots_flag"`
	MediaAssetIds    []byte                    `json:"media_asset_ids"`
	WorkflowStatus   string                    `json:"workflow_status"`
	ReviewerUsername string                    `json:"reviewer_username"`
	ReviewedAt       pgtype.Timestamptz        `json:"reviewed_at"`
	ApproverUsername string                    `json:"approver_username"`
	ApprovedAt       pgtype.Timestamptz        `json:"approved_at"`
	WriterNotes      string                    `json:"writer_notes"`
	ReviewNotes      string                    `json:"review_notes"`
}

func (q *Queries) UpdateCbtQuestion(ctx context.Context, arg UpdateCbtQuestionParams) (CbtQuestion, error) {
	row := q.db.QueryRow(ctx, updateCbtQuestion,
		arg.ID,
		arg.EventID,
		arg.SubjectID,
		arg.Code,
		arg.QuestionText,
		arg.QuestionType,
		arg.Options,
		arg.OptionA,
		arg.OptionB,
		arg.OptionC,
		arg.OptionD,
		arg.OptionE,
		arg.AnswerKey,
		arg.Explanation,
		arg.Difficulty,
		arg.Status,
		arg.StemHtml,
		arg.StemLatex,
		arg.StimulusHtml,
		arg.StimulusLatex,
		arg.ExplanationHtml,
		arg.RubricHtml,
		arg.AcademicPhase,
		arg.GradeLevel,
		arg.CpRef,
		arg.TpRef,
		arg.KdRef,
		arg.IndicatorRef,
		arg.MaterialTopic,
		arg.CognitiveLevel,
		arg.HotsFlag,
		arg.MediaAssetIds,
		arg.WorkflowStatus,
		arg.ReviewerUsername,
		arg.ReviewedAt,
		arg.ApproverUsername,
		arg.ApprovedAt,
		arg.WriterNotes,
		arg.ReviewNotes,
	)
	var i CbtQuestion
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Code,
		&i.QuestionText,
		&i.OptionA,
		&i.OptionB,
		&i.OptionC,
		&i.OptionD,
		&i.OptionE,
		&i.AnswerKey,
		&i.Explanation,
		&i.Difficulty,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QuestionType,
		&i.Options,
		&i.StemHtml,
		&i.StemLatex,
		&i.StimulusHtml,
		&i.StimulusLatex,
		&i.ExplanationHtml,
		&i.RubricHtml,
		&i.AcademicPhase,
		&i.GradeLevel,
		&i.CpRef,
		&i.TpRef,
		&i.KdRef,
		&i.IndicatorRef,
		&i.MaterialTopic,
		&i.CognitiveLevel,
		&i.HotsFlag,
		&i.MediaAssetIds,
		&i.WorkflowStatus,
		&i.Version,
		&i.AuthorUsername,
		&i.ReviewerUsername,
		&i.ReviewedAt,
		&i.ApproverUsername,
		&i.ApprovedAt,
		&i.WriterNotes,
		&i.ReviewNotes,
		&i.EventID,
	)
	return i, err
}

const getCbtQuestionSummaryCounts = `-- name: GetCbtQuestionSummaryCounts :one
SELECT
  COUNT(*)::bigint AS total,
  COUNT(*) FILTER (WHERE q.status = 'draft')::bigint AS draft,
  COUNT(*) FILTER (WHERE q.workflow_status = 'review')::bigint AS review,
  COUNT(*) FILTER (WHERE q.workflow_status = 'rejected')::bigint AS rejected,
  COUNT(*) FILTER (WHERE q.workflow_status = 'approved')::bigint AS approved,
  COUNT(*) FILTER (WHERE q.status = 'published')::bigint AS published,
  COALESCE(SUM(pkg_usage.package_count), 0)::bigint AS package_usage
FROM cbt_questions q
LEFT JOIN LATERAL (
  SELECT COUNT(*)::bigint AS package_count
  FROM cbt_package_questions pq
  WHERE pq.question_id = q.id
) pkg_usage ON TRUE
WHERE TRUE
  AND (
    $1::bool
    OR q.status = 'published'
    OR q.author_username = $2::text
    OR EXISTS (
      SELECT 1 FROM cbt_event_members m
      WHERE m.event_id = q.event_id
        AND m.user_id = $3::uuid
        AND m.role IN ('reviewer', 'panitia')
        AND (m.subject_id IS NULL OR m.subject_id = q.subject_id)
    )
  )
`

type GetCbtQuestionSummaryCountsParams struct {
	IsAdmin       bool        `json:"is_admin"`
	ActorUsername string      `json:"actor_username"`
	ActorUserID   pgtype.UUID `json:"actor_user_id"`
}

type GetCbtQuestionSummaryCountsRow struct {
	Total        int64 `json:"total"`
	Draft        int64 `json:"draft"`
	Review       int64 `json:"review"`
	Rejected     int64 `json:"rejected"`
	Approved     int64 `json:"approved"`
	Published    int64 `json:"published"`
	PackageUsage int64 `json:"package_usage"`
}

func (q *Queries) GetCbtQuestionSummaryCounts(ctx context.Context, arg GetCbtQuestionSummaryCountsParams) (GetCbtQuestionSummaryCountsRow, error) {
	row := q.db.QueryRow(ctx, getCbtQuestionSummaryCounts, arg.IsAdmin, arg.ActorUsername, arg.ActorUserID)
	var i GetCbtQuestionSummaryCountsRow
	err := row.Scan(&i.Total, &i.Draft, &i.Review, &i.Rejected, &i.Approved, &i.Published, &i.PackageUsage)
	return i, err
}

const listCbtQuestionSummaryBySubject = `-- name: ListCbtQuestionSummaryBySubject :many
SELECT q.subject_id, s.name AS subject_name, s.code AS subject_code, COUNT(*)::bigint AS total
FROM cbt_questions q
JOIN subjects s ON s.id = q.subject_id
WHERE TRUE
  AND (
    $1::bool
    OR q.status = 'published'
    OR q.author_username = $2::text
    OR EXISTS (
      SELECT 1 FROM cbt_event_members m
      WHERE m.event_id = q.event_id
        AND m.user_id = $3::uuid
        AND m.role IN ('reviewer', 'panitia')
        AND (m.subject_id IS NULL OR m.subject_id = q.subject_id)
    )
  )
GROUP BY q.subject_id, s.name, s.code
ORDER BY total DESC, s.name ASC
LIMIT 8
`

type ListCbtQuestionSummaryBySubjectParams struct {
	IsAdmin       bool        `json:"is_admin"`
	ActorUsername string      `json:"actor_username"`
	ActorUserID   pgtype.UUID `json:"actor_user_id"`
}

type ListCbtQuestionSummaryBySubjectRow struct {
	SubjectID   pgtype.UUID `json:"subject_id"`
	SubjectName string      `json:"subject_name"`
	SubjectCode string      `json:"subject_code"`
	Total       int64       `json:"total"`
}

func (q *Queries) ListCbtQuestionSummaryBySubject(ctx context.Context, arg ListCbtQuestionSummaryBySubjectParams) ([]ListCbtQuestionSummaryBySubjectRow, error) {
	rows, err := q.db.Query(ctx, listCbtQuestionSummaryBySubject, arg.IsAdmin, arg.ActorUsername, arg.ActorUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCbtQuestionSummaryBySubjectRow{}
	for rows.Next() {
		var i ListCbtQuestionSummaryBySubjectRow
		if err := rows.Scan(&i.SubjectID, &i.SubjectName, &i.SubjectCode, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const listCbtQuestionSummaryByCognitiveLevel = `-- name: ListCbtQuestionSummaryByCognitiveLevel :many
SELECT COALESCE(NULLIF(btrim(q.cognitive_level), ''), 'Belum diisi') AS cognitive_level, COUNT(*)::bigint AS total
FROM cbt_questions q
WHERE TRUE
  AND (
    $1::bool
    OR q.status = 'published'
    OR q.author_username = $2::text
    OR EXISTS (
      SELECT 1 FROM cbt_event_members m
      WHERE m.event_id = q.event_id
        AND m.user_id = $3::uuid
        AND m.role IN ('reviewer', 'panitia')
        AND (m.subject_id IS NULL OR m.subject_id = q.subject_id)
    )
  )
GROUP BY COALESCE(NULLIF(btrim(q.cognitive_level), ''), 'Belum diisi')
ORDER BY total DESC, cognitive_level ASC
`

type ListCbtQuestionSummaryByCognitiveLevelParams struct {
	IsAdmin       bool        `json:"is_admin"`
	ActorUsername string      `json:"actor_username"`
	ActorUserID   pgtype.UUID `json:"actor_user_id"`
}

type ListCbtQuestionSummaryByCognitiveLevelRow struct {
	CognitiveLevel string `json:"cognitive_level"`
	Total          int64  `json:"total"`
}

func (q *Queries) ListCbtQuestionSummaryByCognitiveLevel(ctx context.Context, arg ListCbtQuestionSummaryByCognitiveLevelParams) ([]ListCbtQuestionSummaryByCognitiveLevelRow, error) {
	rows, err := q.db.Query(ctx, listCbtQuestionSummaryByCognitiveLevel, arg.IsAdmin, arg.ActorUsername, arg.ActorUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCbtQuestionSummaryByCognitiveLevelRow{}
	for rows.Next() {
		var i ListCbtQuestionSummaryByCognitiveLevelRow
		if err := rows.Scan(&i.CognitiveLevel, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const listCbtQuestionSummaryRecent = `-- name: ListCbtQuestionSummaryRecent :many
SELECT q.id, q.code, q.subject_id, s.name AS subject_name, s.code AS subject_code,
       q.material_topic, q.workflow_status, q.status, q.author_username,
       q.reviewer_username, q.created_at, q.updated_at
FROM cbt_questions q
JOIN subjects s ON s.id = q.subject_id
WHERE TRUE
  AND (
    $1::bool
    OR q.status = 'published'
    OR q.author_username = $2::text
    OR EXISTS (
      SELECT 1 FROM cbt_event_members m
      WHERE m.event_id = q.event_id
        AND m.user_id = $3::uuid
        AND m.role IN ('reviewer', 'panitia')
        AND (m.subject_id IS NULL OR m.subject_id = q.subject_id)
    )
  )
ORDER BY q.updated_at DESC, q.created_at DESC
LIMIT 5
`

type ListCbtQuestionSummaryRecentParams struct {
	IsAdmin       bool        `json:"is_admin"`
	ActorUsername string      `json:"actor_username"`
	ActorUserID   pgtype.UUID `json:"actor_user_id"`
}

type ListCbtQuestionSummaryRecentRow struct {
	ID               pgtype.UUID           `json:"id"`
	Code             string                `json:"code"`
	SubjectID        pgtype.UUID           `json:"subject_id"`
	SubjectName      string                `json:"subject_name"`
	SubjectCode      string                `json:"subject_code"`
	MaterialTopic    string                `json:"material_topic"`
	WorkflowStatus   string                `json:"workflow_status"`
	Status           CbtQuestionStatusEnum `json:"status"`
	AuthorUsername   string                `json:"author_username"`
	ReviewerUsername string                `json:"reviewer_username"`
	CreatedAt        pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz    `json:"updated_at"`
}

func (q *Queries) ListCbtQuestionSummaryRecent(ctx context.Context, arg ListCbtQuestionSummaryRecentParams) ([]ListCbtQuestionSummaryRecentRow, error) {
	rows, err := q.db.Query(ctx, listCbtQuestionSummaryRecent, arg.IsAdmin, arg.ActorUsername, arg.ActorUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCbtQuestionSummaryRecentRow{}
	for rows.Next() {
		var i ListCbtQuestionSummaryRecentRow
		if err := rows.Scan(&i.ID, &i.Code, &i.SubjectID, &i.SubjectName, &i.SubjectCode, &i.MaterialTopic, &i.WorkflowStatus, &i.Status, &i.AuthorUsername, &i.ReviewerUsername, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}
