// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cbt_rooms.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCbtExamRoom = `-- name: CreateCbtExamRoom :one
INSERT INTO cbt_exam_rooms (
  session_id, school_room_id, room_name, room_name_snapshot, capacity
)
VALUES (
  $1, $2, $3,
  COALESCE(NULLIF($4::TEXT, ''), $3::TEXT),
  $5
)
RETURNING id, session_id, room_name, capacity, created_at, school_room_id, room_name_snapshot, capacity_override, room_token, status, is_locked, updated_at
`

type CreateCbtExamRoomParams struct {
	SessionID        pgtype.UUID `json:"session_id"`
	SchoolRoomID     pgtype.UUID `json:"school_room_id"`
	RoomName         string      `json:"room_name"`
	RoomNameSnapshot string      `json:"room_name_snapshot"`
	Capacity         int32       `json:"capacity"`
}

func (q *Queries) CreateCbtExamRoom(ctx context.Context, arg CreateCbtExamRoomParams) (CbtExamRoom, error) {
	row := q.db.QueryRow(ctx, createCbtExamRoom,
		arg.SessionID,
		arg.SchoolRoomID,
		arg.RoomName,
		arg.RoomNameSnapshot,
		arg.Capacity,
	)
	var i CbtExamRoom
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RoomName,
		&i.Capacity,
		&i.CreatedAt,
		&i.SchoolRoomID,
		&i.RoomNameSnapshot,
		&i.CapacityOverride,
		&i.RoomToken,
		&i.Status,
		&i.IsLocked,
		&i.UpdatedAt,
	)
	return i, err
}

const createCbtRoomProctor = `-- name: CreateCbtRoomProctor :one
INSERT INTO cbt_room_proctors (exam_room_id, employee_id, role, assigned_by)
VALUES ($1, $2, $3, $4)
RETURNING id, exam_room_id, employee_id, role, assigned_by, assigned_at
`

type CreateCbtRoomProctorParams struct {
	ExamRoomID pgtype.UUID `json:"exam_room_id"`
	EmployeeID pgtype.UUID `json:"employee_id"`
	Role       string      `json:"role"`
	AssignedBy pgtype.UUID `json:"assigned_by"`
}

func (q *Queries) CreateCbtRoomProctor(ctx context.Context, arg CreateCbtRoomProctorParams) (CbtRoomProctor, error) {
	row := q.db.QueryRow(ctx, createCbtRoomProctor,
		arg.ExamRoomID,
		arg.EmployeeID,
		arg.Role,
		arg.AssignedBy,
	)
	var i CbtRoomProctor
	err := row.Scan(
		&i.ID,
		&i.ExamRoomID,
		&i.EmployeeID,
		&i.Role,
		&i.AssignedBy,
		&i.AssignedAt,
	)
	return i, err
}

const deleteCbtExamRoom = `-- name: DeleteCbtExamRoom :exec
DELETE FROM cbt_exam_rooms WHERE id = $1
`

func (q *Queries) DeleteCbtExamRoom(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCbtExamRoom, id)
	return err
}

const deleteCbtRoomProctorsByRoom = `-- name: DeleteCbtRoomProctorsByRoom :exec
DELETE FROM cbt_room_proctors WHERE exam_room_id = $1
`

func (q *Queries) DeleteCbtRoomProctorsByRoom(ctx context.Context, examRoomID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCbtRoomProctorsByRoom, examRoomID)
	return err
}

const getCbtExamRoom = `-- name: GetCbtExamRoom :one
SELECT id, session_id, room_name, capacity, created_at, school_room_id, room_name_snapshot, capacity_override, room_token, status, is_locked, updated_at
FROM cbt_exam_rooms
WHERE id = $1
`

func (q *Queries) GetCbtExamRoom(ctx context.Context, id pgtype.UUID) (CbtExamRoom, error) {
	row := q.db.QueryRow(ctx, getCbtExamRoom, id)
	var i CbtExamRoom
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RoomName,
		&i.Capacity,
		&i.CreatedAt,
		&i.SchoolRoomID,
		&i.RoomNameSnapshot,
		&i.CapacityOverride,
		&i.RoomToken,
		&i.Status,
		&i.IsLocked,
		&i.UpdatedAt,
	)
	return i, err
}

const getCbtRoomHandover = `-- name: GetCbtRoomHandover :one
WITH room_stats AS (
  SELECT
    ep.room_id,
    COUNT(*)::int AS participant_count,
    COUNT(*) FILTER (WHERE ep.submitted_at IS NOT NULL)::int AS submitted_count,
    COUNT(*) FILTER (WHERE ep.suspicious_flag = TRUE)::int AS suspicious_count,
    COUNT(*) FILTER (WHERE ep.seat_no IS NULL)::int AS missing_seat_count
  FROM cbt_exam_participants ep
  WHERE ep.room_id = $1
  GROUP BY ep.room_id
)
SELECT
  r.id AS room_id,
  r.session_id,
  r.room_name,
  r.room_token,
  r.status AS room_status,
  r.is_locked AS room_is_locked,
  s.title AS session_title,
  s.status AS session_status,
  s.scheduled_start,
  s.scheduled_end,
  p.title AS package_title,
  COALESCE(rs.participant_count, 0)::int AS participant_count,
  COALESCE(rs.submitted_count, 0)::int AS submitted_count,
  COALESCE(rs.suspicious_count, 0)::int AS suspicious_count,
  COALESCE(rs.missing_seat_count, 0)::int AS missing_seat_count,
  h.id AS handover_id,
  COALESCE(h.attendance_checked, FALSE)::boolean AS attendance_checked,
  COALESCE(h.all_submitted_checked, FALSE)::boolean AS all_submitted_checked,
  COALESCE(h.device_issue_checked, FALSE)::boolean AS device_issue_checked,
  COALESCE(h.room_clean_checked, FALSE)::boolean AS room_clean_checked,
  COALESCE(h.token_returned_checked, FALSE)::boolean AS token_returned_checked,
  COALESCE(h.assets_returned_checked, FALSE)::boolean AS assets_returned_checked,
  COALESCE(h.incident_notes, '')::text AS incident_notes,
  COALESCE(h.operator_notes, '')::text AS operator_notes,
  COALESCE(h.handover_notes, '')::text AS handover_notes,
  h.locked_at,
  h.locked_by,
  h.updated_by,
  h.created_at AS handover_created_at,
  h.updated_at AS handover_updated_at
FROM cbt_exam_rooms r
JOIN cbt_exam_sessions s ON s.id = r.session_id
JOIN cbt_packages p ON p.id = s.package_id
LEFT JOIN room_stats rs ON rs.room_id = r.id
LEFT JOIN cbt_room_handovers h ON h.exam_room_id = r.id
WHERE r.id = $1
`

type GetCbtRoomHandoverRow struct {
	RoomID                pgtype.UUID          `json:"room_id"`
	SessionID             pgtype.UUID          `json:"session_id"`
	RoomName              string               `json:"room_name"`
	RoomToken             string               `json:"room_token"`
	RoomStatus            string               `json:"room_status"`
	RoomIsLocked          bool                 `json:"room_is_locked"`
	SessionTitle          string               `json:"session_title"`
	SessionStatus         CbtSessionStatusEnum `json:"session_status"`
	ScheduledStart        pgtype.Timestamptz   `json:"scheduled_start"`
	ScheduledEnd          pgtype.Timestamptz   `json:"scheduled_end"`
	PackageTitle          string               `json:"package_title"`
	ParticipantCount      int32                `json:"participant_count"`
	SubmittedCount        int32                `json:"submitted_count"`
	SuspiciousCount       int32                `json:"suspicious_count"`
	MissingSeatCount      int32                `json:"missing_seat_count"`
	HandoverID            pgtype.UUID          `json:"handover_id"`
	AttendanceChecked     bool                 `json:"attendance_checked"`
	AllSubmittedChecked   bool                 `json:"all_submitted_checked"`
	DeviceIssueChecked    bool                 `json:"device_issue_checked"`
	RoomCleanChecked      bool                 `json:"room_clean_checked"`
	TokenReturnedChecked  bool                 `json:"token_returned_checked"`
	AssetsReturnedChecked bool                 `json:"assets_returned_checked"`
	IncidentNotes         string               `json:"incident_notes"`
	OperatorNotes         string               `json:"operator_notes"`
	HandoverNotes         string               `json:"handover_notes"`
	LockedAt              pgtype.Timestamptz   `json:"locked_at"`
	LockedBy              pgtype.UUID          `json:"locked_by"`
	UpdatedBy             pgtype.UUID          `json:"updated_by"`
	HandoverCreatedAt     pgtype.Timestamptz   `json:"handover_created_at"`
	HandoverUpdatedAt     pgtype.Timestamptz   `json:"handover_updated_at"`
}

func (q *Queries) GetCbtRoomHandover(ctx context.Context, id pgtype.UUID) (GetCbtRoomHandoverRow, error) {
	row := q.db.QueryRow(ctx, getCbtRoomHandover, id)
	var i GetCbtRoomHandoverRow
	err := row.Scan(
		&i.RoomID,
		&i.SessionID,
		&i.RoomName,
		&i.RoomToken,
		&i.RoomStatus,
		&i.RoomIsLocked,
		&i.SessionTitle,
		&i.SessionStatus,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.PackageTitle,
		&i.ParticipantCount,
		&i.SubmittedCount,
		&i.SuspiciousCount,
		&i.MissingSeatCount,
		&i.HandoverID,
		&i.AttendanceChecked,
		&i.AllSubmittedChecked,
		&i.DeviceIssueChecked,
		&i.RoomCleanChecked,
		&i.TokenReturnedChecked,
		&i.AssetsReturnedChecked,
		&i.IncidentNotes,
		&i.OperatorNotes,
		&i.HandoverNotes,
		&i.LockedAt,
		&i.LockedBy,
		&i.UpdatedBy,
		&i.HandoverCreatedAt,
		&i.HandoverUpdatedAt,
	)
	return i, err
}

const getCbtRoomProctorDashboard = `-- name: GetCbtRoomProctorDashboard :one
SELECT
  r.id,
  r.session_id,
  r.school_room_id,
  r.room_name,
  r.room_name_snapshot,
  r.capacity,
  r.capacity_override,
  r.room_token,
  r.status,
  r.is_locked,
  r.created_at,
  r.updated_at,
  s.title AS session_title,
  s.status AS session_status,
  s.scheduled_start,
  s.scheduled_end,
  p.title AS package_title,
  p.duration_minutes,
  COALESCE(sr.code, '') AS school_room_code,
  COALESCE(sr.name, '') AS school_room_name,
  COALESCE(sr.building, '') AS school_room_building,
  COALESCE(sr.location_note, '') AS school_room_location_note,
  COUNT(ep.id)::int AS participant_count,
  COUNT(ep.id) FILTER (WHERE ep.submitted_at IS NOT NULL)::int AS submitted_count,
  COUNT(ep.id) FILTER (WHERE ep.last_heartbeat IS NOT NULL AND ep.last_heartbeat > NOW() - INTERVAL '2 minutes')::int AS online_count,
  COUNT(ep.id) FILTER (WHERE ep.suspicious_flag = TRUE)::int AS suspicious_count,
  COUNT(ep.id) FILTER (WHERE ep.seat_no IS NULL)::int AS missing_seat_count
FROM cbt_exam_rooms r
JOIN cbt_exam_sessions s ON s.id = r.session_id
JOIN cbt_packages p ON p.id = s.package_id
LEFT JOIN school_rooms sr ON sr.id = r.school_room_id
LEFT JOIN cbt_exam_participants ep ON ep.room_id = r.id AND ep.session_id = r.session_id
WHERE r.id = $1
GROUP BY r.id, s.title, s.status, s.scheduled_start, s.scheduled_end, p.title, p.duration_minutes,
         sr.code, sr.name, sr.building, sr.location_note
`

type GetCbtRoomProctorDashboardRow struct {
	ID                     pgtype.UUID          `json:"id"`
	SessionID              pgtype.UUID          `json:"session_id"`
	SchoolRoomID           pgtype.UUID          `json:"school_room_id"`
	RoomName               string               `json:"room_name"`
	RoomNameSnapshot       string               `json:"room_name_snapshot"`
	Capacity               int32                `json:"capacity"`
	CapacityOverride       pgtype.Int4          `json:"capacity_override"`
	RoomToken              string               `json:"room_token"`
	Status                 string               `json:"status"`
	IsLocked               bool                 `json:"is_locked"`
	CreatedAt              pgtype.Timestamptz   `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz   `json:"updated_at"`
	SessionTitle           string               `json:"session_title"`
	SessionStatus          CbtSessionStatusEnum `json:"session_status"`
	ScheduledStart         pgtype.Timestamptz   `json:"scheduled_start"`
	ScheduledEnd           pgtype.Timestamptz   `json:"scheduled_end"`
	PackageTitle           string               `json:"package_title"`
	DurationMinutes        int32                `json:"duration_minutes"`
	SchoolRoomCode         string               `json:"school_room_code"`
	SchoolRoomName         string               `json:"school_room_name"`
	SchoolRoomBuilding     string               `json:"school_room_building"`
	SchoolRoomLocationNote string               `json:"school_room_location_note"`
	ParticipantCount       int32                `json:"participant_count"`
	SubmittedCount         int32                `json:"submitted_count"`
	OnlineCount            int32                `json:"online_count"`
	SuspiciousCount        int32                `json:"suspicious_count"`
	MissingSeatCount       int32                `json:"missing_seat_count"`
}

func (q *Queries) GetCbtRoomProctorDashboard(ctx context.Context, id pgtype.UUID) (GetCbtRoomProctorDashboardRow, error) {
	row := q.db.QueryRow(ctx, getCbtRoomProctorDashboard, id)
	var i GetCbtRoomProctorDashboardRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.SchoolRoomID,
		&i.RoomName,
		&i.RoomNameSnapshot,
		&i.Capacity,
		&i.CapacityOverride,
		&i.RoomToken,
		&i.Status,
		&i.IsLocked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SessionTitle,
		&i.SessionStatus,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.PackageTitle,
		&i.DurationMinutes,
		&i.SchoolRoomCode,
		&i.SchoolRoomName,
		&i.SchoolRoomBuilding,
		&i.SchoolRoomLocationNote,
		&i.ParticipantCount,
		&i.SubmittedCount,
		&i.OnlineCount,
		&i.SuspiciousCount,
		&i.MissingSeatCount,
	)
	return i, err
}

const getCbtSessionOperationalRecap = `-- name: GetCbtSessionOperationalRecap :one
WITH participant_stats AS (
  SELECT
    ep.session_id,
    COUNT(*)::int AS participant_count,
    COUNT(*) FILTER (WHERE ep.room_id IS NULL)::int AS unassigned_participant_count,
    COUNT(*) FILTER (WHERE ep.joined_at IS NOT NULL)::int AS joined_count,
    COUNT(*) FILTER (WHERE ep.submitted_at IS NOT NULL)::int AS submitted_count,
    COUNT(*) FILTER (WHERE ep.joined_at IS NULL AND ep.submitted_at IS NULL)::int AS no_show_count,
    COUNT(*) FILTER (WHERE ep.suspicious_flag = TRUE)::int AS suspicious_count,
    COALESCE(SUM(ep.app_switch_count), 0)::int AS app_switch_count,
    COALESCE(SUM(ep.screenshot_attempt), 0)::int AS screenshot_attempt_count
  FROM cbt_exam_participants ep
  WHERE ep.session_id = $1
  GROUP BY ep.session_id
),
room_stats AS (
  SELECT
    r.session_id,
    COUNT(*)::int AS room_count,
    COUNT(*) FILTER (WHERE h.locked_at IS NOT NULL)::int AS handover_locked_count,
    COUNT(*) FILTER (WHERE h.id IS NOT NULL AND h.locked_at IS NULL)::int AS handover_draft_count,
    COUNT(*) FILTER (WHERE h.id IS NULL)::int AS handover_missing_count,
    COUNT(*) FILTER (
      WHERE NULLIF(TRIM(COALESCE(h.incident_notes, '')), '') IS NOT NULL
         OR NULLIF(TRIM(COALESCE(h.operator_notes, '')), '') IS NOT NULL
    )::int AS incident_room_count
  FROM cbt_exam_rooms r
  LEFT JOIN cbt_room_handovers h ON h.exam_room_id = r.id
  WHERE r.session_id = $1
  GROUP BY r.session_id
),
event_stats AS (
  SELECT
    ep.session_id,
    COUNT(ev.id) FILTER (
      WHERE ev.event_type IN ('app_switch', 'screenshot_attempt', 'proctor_force_submit', 'proctor_reset_access', 'warning')
    )::int AS incident_event_count,
    COUNT(ev.id) FILTER (WHERE ev.event_type = 'proctor_force_submit')::int AS force_submit_count,
    COUNT(ev.id) FILTER (WHERE ev.event_type = 'proctor_reset_access')::int AS reset_access_count,
    COUNT(ev.id) FILTER (WHERE ev.event_type = 'app_switch')::int AS app_switch_event_count,
    COUNT(ev.id) FILTER (WHERE ev.event_type = 'screenshot_attempt')::int AS screenshot_event_count
  FROM cbt_exam_participants ep
  LEFT JOIN cbt_participant_events ev ON ev.participant_id = ep.id
  WHERE ep.session_id = $1
  GROUP BY ep.session_id
)
SELECT
  s.id AS session_id,
  s.title AS session_title,
  s.status AS session_status,
  s.scheduled_start,
  s.scheduled_end,
  COALESCE(rs.room_count, 0)::int AS room_count,
  COALESCE(rs.handover_locked_count, 0)::int AS handover_locked_count,
  COALESCE(rs.handover_draft_count, 0)::int AS handover_draft_count,
  COALESCE(rs.handover_missing_count, 0)::int AS handover_missing_count,
  COALESCE(rs.incident_room_count, 0)::int AS incident_room_count,
  COALESCE(ps.participant_count, 0)::int AS participant_count,
  COALESCE(ps.unassigned_participant_count, 0)::int AS unassigned_participant_count,
  COALESCE(ps.joined_count, 0)::int AS joined_count,
  COALESCE(ps.submitted_count, 0)::int AS submitted_count,
  COALESCE(ps.no_show_count, 0)::int AS no_show_count,
  COALESCE(ps.suspicious_count, 0)::int AS suspicious_count,
  COALESCE(ps.app_switch_count, 0)::int AS app_switch_count,
  COALESCE(ps.screenshot_attempt_count, 0)::int AS screenshot_attempt_count,
  COALESCE(es.incident_event_count, 0)::int AS incident_event_count,
  COALESCE(es.force_submit_count, 0)::int AS force_submit_count,
  COALESCE(es.reset_access_count, 0)::int AS reset_access_count,
  COALESCE(es.app_switch_event_count, 0)::int AS app_switch_event_count,
  COALESCE(es.screenshot_event_count, 0)::int AS screenshot_event_count
FROM cbt_exam_sessions s
LEFT JOIN participant_stats ps ON ps.session_id = s.id
LEFT JOIN room_stats rs ON rs.session_id = s.id
LEFT JOIN event_stats es ON es.session_id = s.id
WHERE s.id = $1
`

type GetCbtSessionOperationalRecapRow struct {
	SessionID                  pgtype.UUID          `json:"session_id"`
	SessionTitle               string               `json:"session_title"`
	SessionStatus              CbtSessionStatusEnum `json:"session_status"`
	ScheduledStart             pgtype.Timestamptz   `json:"scheduled_start"`
	ScheduledEnd               pgtype.Timestamptz   `json:"scheduled_end"`
	RoomCount                  int32                `json:"room_count"`
	HandoverLockedCount        int32                `json:"handover_locked_count"`
	HandoverDraftCount         int32                `json:"handover_draft_count"`
	HandoverMissingCount       int32                `json:"handover_missing_count"`
	IncidentRoomCount          int32                `json:"incident_room_count"`
	ParticipantCount           int32                `json:"participant_count"`
	UnassignedParticipantCount int32                `json:"unassigned_participant_count"`
	JoinedCount                int32                `json:"joined_count"`
	SubmittedCount             int32                `json:"submitted_count"`
	NoShowCount                int32                `json:"no_show_count"`
	SuspiciousCount            int32                `json:"suspicious_count"`
	AppSwitchCount             int32                `json:"app_switch_count"`
	ScreenshotAttemptCount     int32                `json:"screenshot_attempt_count"`
	IncidentEventCount         int32                `json:"incident_event_count"`
	ForceSubmitCount           int32                `json:"force_submit_count"`
	ResetAccessCount           int32                `json:"reset_access_count"`
	AppSwitchEventCount        int32                `json:"app_switch_event_count"`
	ScreenshotEventCount       int32                `json:"screenshot_event_count"`
}

func (q *Queries) GetCbtSessionOperationalRecap(ctx context.Context, id pgtype.UUID) (GetCbtSessionOperationalRecapRow, error) {
	row := q.db.QueryRow(ctx, getCbtSessionOperationalRecap, id)
	var i GetCbtSessionOperationalRecapRow
	err := row.Scan(
		&i.SessionID,
		&i.SessionTitle,
		&i.SessionStatus,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.RoomCount,
		&i.HandoverLockedCount,
		&i.HandoverDraftCount,
		&i.HandoverMissingCount,
		&i.IncidentRoomCount,
		&i.ParticipantCount,
		&i.UnassignedParticipantCount,
		&i.JoinedCount,
		&i.SubmittedCount,
		&i.NoShowCount,
		&i.SuspiciousCount,
		&i.AppSwitchCount,
		&i.ScreenshotAttemptCount,
		&i.IncidentEventCount,
		&i.ForceSubmitCount,
		&i.ResetAccessCount,
		&i.AppSwitchEventCount,
		&i.ScreenshotEventCount,
	)
	return i, err
}

const getCbtSessionRoomReadiness = `-- name: GetCbtSessionRoomReadiness :one
WITH room_stats AS (
  SELECT
    COUNT(*)::int AS room_count,
    COALESCE(SUM(capacity), 0)::int AS total_capacity
  FROM cbt_exam_rooms er
  WHERE er.session_id = $1
),
participant_stats AS (
  SELECT
    COUNT(*)::int AS participant_count,
    COUNT(*) FILTER (WHERE room_id IS NOT NULL)::int AS assigned_participant_count,
    COUNT(*) FILTER (WHERE room_id IS NULL)::int AS unassigned_participant_count,
    COUNT(*) FILTER (WHERE room_id IS NOT NULL AND seat_no IS NULL)::int AS missing_seat_count
  FROM cbt_exam_participants ep
  WHERE ep.session_id = $1
),
room_proctor_counts AS (
  SELECT r.id, COUNT(rp.id)::int AS proctor_count
  FROM cbt_exam_rooms r
  LEFT JOIN cbt_room_proctors rp ON rp.exam_room_id = r.id
  WHERE r.session_id = $1
  GROUP BY r.id
),
proctor_stats AS (
  SELECT
    COUNT(*) FILTER (WHERE proctor_count = 0)::int AS rooms_without_proctor,
    COALESCE(SUM(proctor_count), 0)::int AS proctor_assignment_count
  FROM room_proctor_counts
)
SELECT
  rs.room_count,
  rs.total_capacity,
  ps.participant_count,
  ps.assigned_participant_count,
  ps.unassigned_participant_count,
  ps.missing_seat_count,
  COALESCE(prs.rooms_without_proctor, 0)::int AS rooms_without_proctor,
  COALESCE(prs.proctor_assignment_count, 0)::int AS proctor_assignment_count
FROM room_stats rs, participant_stats ps, proctor_stats prs
`

type GetCbtSessionRoomReadinessRow struct {
	RoomCount                  int32 `json:"room_count"`
	TotalCapacity              int32 `json:"total_capacity"`
	ParticipantCount           int32 `json:"participant_count"`
	AssignedParticipantCount   int32 `json:"assigned_participant_count"`
	UnassignedParticipantCount int32 `json:"unassigned_participant_count"`
	MissingSeatCount           int32 `json:"missing_seat_count"`
	RoomsWithoutProctor        int32 `json:"rooms_without_proctor"`
	ProctorAssignmentCount     int32 `json:"proctor_assignment_count"`
}

func (q *Queries) GetCbtSessionRoomReadiness(ctx context.Context, targetSessionID pgtype.UUID) (GetCbtSessionRoomReadinessRow, error) {
	row := q.db.QueryRow(ctx, getCbtSessionRoomReadiness, targetSessionID)
	var i GetCbtSessionRoomReadinessRow
	err := row.Scan(
		&i.RoomCount,
		&i.TotalCapacity,
		&i.ParticipantCount,
		&i.AssignedParticipantCount,
		&i.UnassignedParticipantCount,
		&i.MissingSeatCount,
		&i.RoomsWithoutProctor,
		&i.ProctorAssignmentCount,
	)
	return i, err
}

const hasSessionRoomParticipant = `-- name: HasSessionRoomParticipant :one
SELECT EXISTS (
  SELECT 1
  FROM cbt_exam_participants ep
  WHERE ep.session_id = $1
    AND ep.room_id = $2
    AND ep.id = $3
)::boolean
`

type HasSessionRoomParticipantParams struct {
	SessionID     pgtype.UUID `json:"session_id"`
	RoomID        pgtype.UUID `json:"room_id"`
	ParticipantID pgtype.UUID `json:"participant_id"`
}

func (q *Queries) HasSessionRoomParticipant(ctx context.Context, arg HasSessionRoomParticipantParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasSessionRoomParticipant, arg.SessionID, arg.RoomID, arg.ParticipantID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const hasSessionRoomProctor = `-- name: HasSessionRoomProctor :one
SELECT EXISTS (
  SELECT 1
  FROM cbt_room_proctors rp
  JOIN cbt_exam_rooms r ON r.id = rp.exam_room_id
  WHERE r.session_id = $1
    AND r.id = $2
    AND rp.employee_id = $3
)::boolean
`

type HasSessionRoomProctorParams struct {
	SessionID  pgtype.UUID `json:"session_id"`
	RoomID     pgtype.UUID `json:"room_id"`
	EmployeeID pgtype.UUID `json:"employee_id"`
}

func (q *Queries) HasSessionRoomProctor(ctx context.Context, arg HasSessionRoomProctorParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasSessionRoomProctor, arg.SessionID, arg.RoomID, arg.EmployeeID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listCbtExamRooms = `-- name: ListCbtExamRooms :many
WITH participant_counts AS (
  SELECT room_id, COUNT(*)::int AS participant_count
  FROM cbt_exam_participants
  WHERE session_id = $1 AND room_id IS NOT NULL
  GROUP BY room_id
),
proctor_counts AS (
  SELECT exam_room_id, COUNT(*)::int AS proctor_count
  FROM cbt_room_proctors
  GROUP BY exam_room_id
),
primary_proctors AS (
  SELECT DISTINCT ON (rp.exam_room_id)
    rp.exam_room_id, rp.employee_id AS primary_proctor_id, e.nama AS primary_proctor_name
  FROM cbt_room_proctors rp
  JOIN employees e ON e.id = rp.employee_id
  ORDER BY rp.exam_room_id, CASE rp.role WHEN 'utama' THEN 0 WHEN 'pendamping' THEN 1 ELSE 2 END, rp.assigned_at ASC
)
SELECT
  r.id, r.session_id, r.school_room_id,
  r.room_name, r.room_name_snapshot, r.capacity, r.capacity_override,
  r.room_token, r.status, r.is_locked, r.created_at, r.updated_at,
  COALESCE(sr.code, '') AS school_room_code,
  COALESCE(sr.name, '') AS school_room_name,
  COALESCE(sr.building, '') AS school_room_building,
  COALESCE(sr.location_note, '') AS school_room_location_note,
  COALESCE(sr.exam_capacity, 0)::int AS school_room_exam_capacity,
  COALESCE(sr.condition, '') AS school_room_condition,
  COALESCE(sr.is_exam_eligible, false) AS school_room_exam_eligible,
  COALESCE(pc.participant_count, 0)::int AS participant_count,
  COALESCE(prc.proctor_count, 0)::int AS proctor_count,
  pp.primary_proctor_id,
  COALESCE(pp.primary_proctor_name, '') AS primary_proctor_name
FROM cbt_exam_rooms r
LEFT JOIN school_rooms sr ON sr.id = r.school_room_id
LEFT JOIN participant_counts pc ON pc.room_id = r.id
LEFT JOIN proctor_counts prc ON prc.exam_room_id = r.id
LEFT JOIN primary_proctors pp ON pp.exam_room_id = r.id
WHERE r.session_id = $1
ORDER BY r.room_name ASC
`

type ListCbtExamRoomsRow struct {
	ID                     pgtype.UUID        `json:"id"`
	SessionID              pgtype.UUID        `json:"session_id"`
	SchoolRoomID           pgtype.UUID        `json:"school_room_id"`
	RoomName               string             `json:"room_name"`
	RoomNameSnapshot       string             `json:"room_name_snapshot"`
	Capacity               int32              `json:"capacity"`
	CapacityOverride       pgtype.Int4        `json:"capacity_override"`
	RoomToken              string             `json:"room_token"`
	Status                 string             `json:"status"`
	IsLocked               bool               `json:"is_locked"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	SchoolRoomCode         string             `json:"school_room_code"`
	SchoolRoomName         string             `json:"school_room_name"`
	SchoolRoomBuilding     string             `json:"school_room_building"`
	SchoolRoomLocationNote string             `json:"school_room_location_note"`
	SchoolRoomExamCapacity int32              `json:"school_room_exam_capacity"`
	SchoolRoomCondition    string             `json:"school_room_condition"`
	SchoolRoomExamEligible bool               `json:"school_room_exam_eligible"`
	ParticipantCount       int32              `json:"participant_count"`
	ProctorCount           int32              `json:"proctor_count"`
	PrimaryProctorID       pgtype.UUID        `json:"primary_proctor_id"`
	PrimaryProctorName     string             `json:"primary_proctor_name"`
}

func (q *Queries) ListCbtExamRooms(ctx context.Context, sessionID pgtype.UUID) ([]ListCbtExamRoomsRow, error) {
	rows, err := q.db.Query(ctx, listCbtExamRooms, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCbtExamRoomsRow{}
	for rows.Next() {
		var i ListCbtExamRoomsRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.SchoolRoomID,
			&i.RoomName,
			&i.RoomNameSnapshot,
			&i.Capacity,
			&i.CapacityOverride,
			&i.RoomToken,
			&i.Status,
			&i.IsLocked,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SchoolRoomCode,
			&i.SchoolRoomName,
			&i.SchoolRoomBuilding,
			&i.SchoolRoomLocationNote,
			&i.SchoolRoomExamCapacity,
			&i.SchoolRoomCondition,
			&i.SchoolRoomExamEligible,
			&i.ParticipantCount,
			&i.ProctorCount,
			&i.PrimaryProctorID,
			&i.PrimaryProctorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCbtProctorRooms = `-- name: ListCbtProctorRooms :many
WITH participant_stats AS (
  SELECT
    ep.room_id,
    COUNT(*)::int AS participant_count,
    COUNT(*) FILTER (WHERE ep.submitted_at IS NOT NULL)::int AS submitted_count,
    COUNT(*) FILTER (WHERE ep.last_heartbeat IS NOT NULL AND ep.last_heartbeat > NOW() - INTERVAL '2 minutes')::int AS online_count,
    COUNT(*) FILTER (WHERE ep.suspicious_flag = TRUE)::int AS suspicious_count,
    COUNT(*) FILTER (WHERE ep.seat_no IS NULL)::int AS missing_seat_count
  FROM cbt_exam_participants ep
  WHERE ep.room_id IS NOT NULL
  GROUP BY ep.room_id
),
proctor_rollup AS (
  SELECT
    rp.exam_room_id,
    COUNT(*)::int AS proctor_count,
    STRING_AGG(e.nama, ', ' ORDER BY CASE rp.role WHEN 'utama' THEN 0 WHEN 'pendamping' THEN 1 ELSE 2 END, e.nama ASC)::text AS proctor_names,
    COALESCE(
      MAX(CASE WHEN rp.employee_id = $2 THEN rp.role ELSE '' END),
      ''
    )::text AS actor_role
  FROM cbt_room_proctors rp
  JOIN employees e ON e.id = rp.employee_id
  GROUP BY rp.exam_room_id
)
SELECT
  r.id,
  r.session_id,
  r.school_room_id,
  r.room_name,
  r.room_name_snapshot,
  r.capacity,
  r.capacity_override,
  r.room_token,
  r.status,
  r.is_locked,
  r.created_at,
  r.updated_at,
  s.title AS session_title,
  s.status AS session_status,
  s.scheduled_start,
  s.scheduled_end,
  p.title AS package_title,
  p.duration_minutes,
  COALESCE(sr.code, '') AS school_room_code,
  COALESCE(sr.name, '') AS school_room_name,
  COALESCE(sr.building, '') AS school_room_building,
  COALESCE(sr.location_note, '') AS school_room_location_note,
  COALESCE(ps.participant_count, 0)::int AS participant_count,
  COALESCE(ps.submitted_count, 0)::int AS submitted_count,
  COALESCE(ps.online_count, 0)::int AS online_count,
  COALESCE(ps.suspicious_count, 0)::int AS suspicious_count,
  COALESCE(ps.missing_seat_count, 0)::int AS missing_seat_count,
  COALESCE(pr.proctor_count, 0)::int AS proctor_count,
  COALESCE(pr.proctor_names, '')::text AS proctor_names,
  COALESCE(pr.actor_role, '')::text AS actor_role
FROM cbt_exam_rooms r
JOIN cbt_exam_sessions s ON s.id = r.session_id
JOIN cbt_packages p ON p.id = s.package_id
LEFT JOIN school_rooms sr ON sr.id = r.school_room_id
LEFT JOIN participant_stats ps ON ps.room_id = r.id
LEFT JOIN proctor_rollup pr ON pr.exam_room_id = r.id
WHERE (
    $1::boolean
    OR EXISTS (
      SELECT 1
      FROM cbt_room_proctors actor_rp
      WHERE actor_rp.exam_room_id = r.id
        AND actor_rp.employee_id = $2
    )
  )
  AND (s.status IN ('draft', 'scheduled', 'active') OR s.scheduled_end >= NOW() - INTERVAL '7 days')
ORDER BY CASE s.status WHEN 'active' THEN 0 WHEN 'scheduled' THEN 1 WHEN 'draft' THEN 2 ELSE 3 END,
         s.scheduled_start ASC,
         r.room_name ASC
`

type ListCbtProctorRoomsParams struct {
	IncludeAll bool        `json:"include_all"`
	EmployeeID pgtype.UUID `json:"employee_id"`
}

type ListCbtProctorRoomsRow struct {
	ID                     pgtype.UUID          `json:"id"`
	SessionID              pgtype.UUID          `json:"session_id"`
	SchoolRoomID           pgtype.UUID          `json:"school_room_id"`
	RoomName               string               `json:"room_name"`
	RoomNameSnapshot       string               `json:"room_name_snapshot"`
	Capacity               int32                `json:"capacity"`
	CapacityOverride       pgtype.Int4          `json:"capacity_override"`
	RoomToken              string               `json:"room_token"`
	Status                 string               `json:"status"`
	IsLocked               bool                 `json:"is_locked"`
	CreatedAt              pgtype.Timestamptz   `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz   `json:"updated_at"`
	SessionTitle           string               `json:"session_title"`
	SessionStatus          CbtSessionStatusEnum `json:"session_status"`
	ScheduledStart         pgtype.Timestamptz   `json:"scheduled_start"`
	ScheduledEnd           pgtype.Timestamptz   `json:"scheduled_end"`
	PackageTitle           string               `json:"package_title"`
	DurationMinutes        int32                `json:"duration_minutes"`
	SchoolRoomCode         string               `json:"school_room_code"`
	SchoolRoomName         string               `json:"school_room_name"`
	SchoolRoomBuilding     string               `json:"school_room_building"`
	SchoolRoomLocationNote string               `json:"school_room_location_note"`
	ParticipantCount       int32                `json:"participant_count"`
	SubmittedCount         int32                `json:"submitted_count"`
	OnlineCount            int32                `json:"online_count"`
	SuspiciousCount        int32                `json:"suspicious_count"`
	MissingSeatCount       int32                `json:"missing_seat_count"`
	ProctorCount           int32                `json:"proctor_count"`
	ProctorNames           string               `json:"proctor_names"`
	ActorRole              string               `json:"actor_role"`
}

func (q *Queries) ListCbtProctorRooms(ctx context.Context, arg ListCbtProctorRoomsParams) ([]ListCbtProctorRoomsRow, error) {
	rows, err := q.db.Query(ctx, listCbtProctorRooms, arg.IncludeAll, arg.EmployeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCbtProctorRoomsRow{}
	for rows.Next() {
		var i ListCbtProctorRoomsRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.SchoolRoomID,
			&i.RoomName,
			&i.RoomNameSnapshot,
			&i.Capacity,
			&i.CapacityOverride,
			&i.RoomToken,
			&i.Status,
			&i.IsLocked,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SessionTitle,
			&i.SessionStatus,
			&i.ScheduledStart,
			&i.ScheduledEnd,
			&i.PackageTitle,
			&i.DurationMinutes,
			&i.SchoolRoomCode,
			&i.SchoolRoomName,
			&i.SchoolRoomBuilding,
			&i.SchoolRoomLocationNote,
			&i.ParticipantCount,
			&i.SubmittedCount,
			&i.OnlineCount,
			&i.SuspiciousCount,
			&i.MissingSeatCount,
			&i.ProctorCount,
			&i.ProctorNames,
			&i.ActorRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCbtRoomProctors = `-- name: ListCbtRoomProctors :many
SELECT rp.id, rp.exam_room_id, rp.employee_id, e.nip, e.nama,
       rp.role, rp.assigned_by, rp.assigned_at
FROM cbt_room_proctors rp
JOIN employees e ON e.id = rp.employee_id
WHERE rp.exam_room_id = $1
ORDER BY CASE rp.role WHEN 'utama' THEN 0 WHEN 'pendamping' THEN 1 ELSE 2 END, e.nama ASC
`

type ListCbtRoomProctorsRow struct {
	ID         pgtype.UUID        `json:"id"`
	ExamRoomID pgtype.UUID        `json:"exam_room_id"`
	EmployeeID pgtype.UUID        `json:"employee_id"`
	Nip        string             `json:"nip"`
	Nama       string             `json:"nama"`
	Role       string             `json:"role"`
	AssignedBy pgtype.UUID        `json:"assigned_by"`
	AssignedAt pgtype.Timestamptz `json:"assigned_at"`
}

func (q *Queries) ListCbtRoomProctors(ctx context.Context, examRoomID pgtype.UUID) ([]ListCbtRoomProctorsRow, error) {
	rows, err := q.db.Query(ctx, listCbtRoomProctors, examRoomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCbtRoomProctorsRow{}
	for rows.Next() {
		var i ListCbtRoomProctorsRow
		if err := rows.Scan(
			&i.ID,
			&i.ExamRoomID,
			&i.EmployeeID,
			&i.Nip,
			&i.Nama,
			&i.Role,
			&i.AssignedBy,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCbtSessionRoomOperationalRecap = `-- name: ListCbtSessionRoomOperationalRecap :many
WITH participant_stats AS (
  SELECT
    ep.room_id,
    COUNT(*)::int AS participant_count,
    COUNT(*) FILTER (WHERE ep.joined_at IS NOT NULL)::int AS joined_count,
    COUNT(*) FILTER (WHERE ep.submitted_at IS NOT NULL)::int AS submitted_count,
    COUNT(*) FILTER (WHERE ep.joined_at IS NULL AND ep.submitted_at IS NULL)::int AS no_show_count,
    COUNT(*) FILTER (WHERE ep.suspicious_flag = TRUE)::int AS suspicious_count,
    COUNT(*) FILTER (WHERE ep.seat_no IS NULL)::int AS missing_seat_count,
    COALESCE(SUM(ep.app_switch_count), 0)::int AS app_switch_count,
    COALESCE(SUM(ep.screenshot_attempt), 0)::int AS screenshot_attempt_count
  FROM cbt_exam_participants ep
  WHERE ep.session_id = $1 AND ep.room_id IS NOT NULL
  GROUP BY ep.room_id
),
event_stats AS (
  SELECT
    ep.room_id,
    COUNT(ev.id) FILTER (
      WHERE ev.event_type IN ('app_switch', 'screenshot_attempt', 'proctor_force_submit', 'proctor_reset_access', 'warning')
    )::int AS incident_event_count,
    COUNT(ev.id) FILTER (WHERE ev.event_type = 'proctor_force_submit')::int AS force_submit_count,
    COUNT(ev.id) FILTER (WHERE ev.event_type = 'proctor_reset_access')::int AS reset_access_count
  FROM cbt_exam_participants ep
  LEFT JOIN cbt_participant_events ev ON ev.participant_id = ep.id
  WHERE ep.session_id = $1 AND ep.room_id IS NOT NULL
  GROUP BY ep.room_id
)
SELECT
  r.id AS room_id,
  r.session_id,
  r.room_name,
  r.room_token,
  r.status AS room_status,
  r.is_locked AS room_is_locked,
  COALESCE(ps.participant_count, 0)::int AS participant_count,
  COALESCE(ps.joined_count, 0)::int AS joined_count,
  COALESCE(ps.submitted_count, 0)::int AS submitted_count,
  COALESCE(ps.no_show_count, 0)::int AS no_show_count,
  COALESCE(ps.suspicious_count, 0)::int AS suspicious_count,
  COALESCE(ps.missing_seat_count, 0)::int AS missing_seat_count,
  COALESCE(ps.app_switch_count, 0)::int AS app_switch_count,
  COALESCE(ps.screenshot_attempt_count, 0)::int AS screenshot_attempt_count,
  COALESCE(es.incident_event_count, 0)::int AS incident_event_count,
  COALESCE(es.force_submit_count, 0)::int AS force_submit_count,
  COALESCE(es.reset_access_count, 0)::int AS reset_access_count,
  h.id AS handover_id,
  COALESCE(h.attendance_checked, FALSE)::boolean AS attendance_checked,
  COALESCE(h.all_submitted_checked, FALSE)::boolean AS all_submitted_checked,
  COALESCE(h.device_issue_checked, FALSE)::boolean AS device_issue_checked,
  COALESCE(h.room_clean_checked, FALSE)::boolean AS room_clean_checked,
  COALESCE(h.token_returned_checked, FALSE)::boolean AS token_returned_checked,
  COALESCE(h.assets_returned_checked, FALSE)::boolean AS assets_returned_checked,
  COALESCE(h.incident_notes, '')::text AS incident_notes,
  COALESCE(h.operator_notes, '')::text AS operator_notes,
  COALESCE(h.handover_notes, '')::text AS handover_notes,
  h.locked_at,
  h.updated_at AS handover_updated_at
FROM cbt_exam_rooms r
LEFT JOIN participant_stats ps ON ps.room_id = r.id
LEFT JOIN event_stats es ON es.room_id = r.id
LEFT JOIN cbt_room_handovers h ON h.exam_room_id = r.id
WHERE r.session_id = $1
ORDER BY
  CASE
    WHEN h.id IS NULL THEN 0
    WHEN h.locked_at IS NULL THEN 1
    ELSE 2
  END,
  COALESCE(es.incident_event_count, 0) DESC,
  r.room_name ASC
`

type ListCbtSessionRoomOperationalRecapRow struct {
	RoomID                 pgtype.UUID        `json:"room_id"`
	SessionID              pgtype.UUID        `json:"session_id"`
	RoomName               string             `json:"room_name"`
	RoomToken              string             `json:"room_token"`
	RoomStatus             string             `json:"room_status"`
	RoomIsLocked           bool               `json:"room_is_locked"`
	ParticipantCount       int32              `json:"participant_count"`
	JoinedCount            int32              `json:"joined_count"`
	SubmittedCount         int32              `json:"submitted_count"`
	NoShowCount            int32              `json:"no_show_count"`
	SuspiciousCount        int32              `json:"suspicious_count"`
	MissingSeatCount       int32              `json:"missing_seat_count"`
	AppSwitchCount         int32              `json:"app_switch_count"`
	ScreenshotAttemptCount int32              `json:"screenshot_attempt_count"`
	IncidentEventCount     int32              `json:"incident_event_count"`
	ForceSubmitCount       int32              `json:"force_submit_count"`
	ResetAccessCount       int32              `json:"reset_access_count"`
	HandoverID             pgtype.UUID        `json:"handover_id"`
	AttendanceChecked      bool               `json:"attendance_checked"`
	AllSubmittedChecked    bool               `json:"all_submitted_checked"`
	DeviceIssueChecked     bool               `json:"device_issue_checked"`
	RoomCleanChecked       bool               `json:"room_clean_checked"`
	TokenReturnedChecked   bool               `json:"token_returned_checked"`
	AssetsReturnedChecked  bool               `json:"assets_returned_checked"`
	IncidentNotes          string             `json:"incident_notes"`
	OperatorNotes          string             `json:"operator_notes"`
	HandoverNotes          string             `json:"handover_notes"`
	LockedAt               pgtype.Timestamptz `json:"locked_at"`
	HandoverUpdatedAt      pgtype.Timestamptz `json:"handover_updated_at"`
}

func (q *Queries) ListCbtSessionRoomOperationalRecap(ctx context.Context, sessionID pgtype.UUID) ([]ListCbtSessionRoomOperationalRecapRow, error) {
	rows, err := q.db.Query(ctx, listCbtSessionRoomOperationalRecap, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCbtSessionRoomOperationalRecapRow{}
	for rows.Next() {
		var i ListCbtSessionRoomOperationalRecapRow
		if err := rows.Scan(
			&i.RoomID,
			&i.SessionID,
			&i.RoomName,
			&i.RoomToken,
			&i.RoomStatus,
			&i.RoomIsLocked,
			&i.ParticipantCount,
			&i.JoinedCount,
			&i.SubmittedCount,
			&i.NoShowCount,
			&i.SuspiciousCount,
			&i.MissingSeatCount,
			&i.AppSwitchCount,
			&i.ScreenshotAttemptCount,
			&i.IncidentEventCount,
			&i.ForceSubmitCount,
			&i.ResetAccessCount,
			&i.HandoverID,
			&i.AttendanceChecked,
			&i.AllSubmittedChecked,
			&i.DeviceIssueChecked,
			&i.RoomCleanChecked,
			&i.TokenReturnedChecked,
			&i.AssetsReturnedChecked,
			&i.IncidentNotes,
			&i.OperatorNotes,
			&i.HandoverNotes,
			&i.LockedAt,
			&i.HandoverUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCbtRoomHandover = `-- name: LockCbtRoomHandover :one
INSERT INTO cbt_room_handovers (
  exam_room_id,
  locked_at,
  locked_by,
  updated_by
)
VALUES (
  $1,
  NOW(),
  $2,
  $2
)
ON CONFLICT (exam_room_id) DO UPDATE
SET
  locked_at = NOW(),
  locked_by = EXCLUDED.locked_by,
  updated_by = EXCLUDED.updated_by,
  updated_at = NOW()
WHERE cbt_room_handovers.locked_at IS NULL
RETURNING id, exam_room_id, attendance_checked, all_submitted_checked, device_issue_checked, room_clean_checked, token_returned_checked, assets_returned_checked, incident_notes, operator_notes, handover_notes, locked_at, locked_by, updated_by, created_at, updated_at
`

type LockCbtRoomHandoverParams struct {
	ExamRoomID pgtype.UUID `json:"exam_room_id"`
	LockedBy   pgtype.UUID `json:"locked_by"`
}

func (q *Queries) LockCbtRoomHandover(ctx context.Context, arg LockCbtRoomHandoverParams) (CbtRoomHandover, error) {
	row := q.db.QueryRow(ctx, lockCbtRoomHandover, arg.ExamRoomID, arg.LockedBy)
	var i CbtRoomHandover
	err := row.Scan(
		&i.ID,
		&i.ExamRoomID,
		&i.AttendanceChecked,
		&i.AllSubmittedChecked,
		&i.DeviceIssueChecked,
		&i.RoomCleanChecked,
		&i.TokenReturnedChecked,
		&i.AssetsReturnedChecked,
		&i.IncidentNotes,
		&i.OperatorNotes,
		&i.HandoverNotes,
		&i.LockedAt,
		&i.LockedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCbtRoomHandover = `-- name: UpsertCbtRoomHandover :one
INSERT INTO cbt_room_handovers (
  exam_room_id,
  attendance_checked,
  all_submitted_checked,
  device_issue_checked,
  room_clean_checked,
  token_returned_checked,
  assets_returned_checked,
  incident_notes,
  operator_notes,
  handover_notes,
  updated_by
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11
)
ON CONFLICT (exam_room_id) DO UPDATE
SET
  attendance_checked = EXCLUDED.attendance_checked,
  all_submitted_checked = EXCLUDED.all_submitted_checked,
  device_issue_checked = EXCLUDED.device_issue_checked,
  room_clean_checked = EXCLUDED.room_clean_checked,
  token_returned_checked = EXCLUDED.token_returned_checked,
  assets_returned_checked = EXCLUDED.assets_returned_checked,
  incident_notes = EXCLUDED.incident_notes,
  operator_notes = EXCLUDED.operator_notes,
  handover_notes = EXCLUDED.handover_notes,
  updated_by = EXCLUDED.updated_by,
  updated_at = NOW()
WHERE cbt_room_handovers.locked_at IS NULL
RETURNING id, exam_room_id, attendance_checked, all_submitted_checked, device_issue_checked, room_clean_checked, token_returned_checked, assets_returned_checked, incident_notes, operator_notes, handover_notes, locked_at, locked_by, updated_by, created_at, updated_at
`

type UpsertCbtRoomHandoverParams struct {
	ExamRoomID            pgtype.UUID `json:"exam_room_id"`
	AttendanceChecked     bool        `json:"attendance_checked"`
	AllSubmittedChecked   bool        `json:"all_submitted_checked"`
	DeviceIssueChecked    bool        `json:"device_issue_checked"`
	RoomCleanChecked      bool        `json:"room_clean_checked"`
	TokenReturnedChecked  bool        `json:"token_returned_checked"`
	AssetsReturnedChecked bool        `json:"assets_returned_checked"`
	IncidentNotes         string      `json:"incident_notes"`
	OperatorNotes         string      `json:"operator_notes"`
	HandoverNotes         string      `json:"handover_notes"`
	UpdatedBy             pgtype.UUID `json:"updated_by"`
}

func (q *Queries) UpsertCbtRoomHandover(ctx context.Context, arg UpsertCbtRoomHandoverParams) (CbtRoomHandover, error) {
	row := q.db.QueryRow(ctx, upsertCbtRoomHandover,
		arg.ExamRoomID,
		arg.AttendanceChecked,
		arg.AllSubmittedChecked,
		arg.DeviceIssueChecked,
		arg.RoomCleanChecked,
		arg.TokenReturnedChecked,
		arg.AssetsReturnedChecked,
		arg.IncidentNotes,
		arg.OperatorNotes,
		arg.HandoverNotes,
		arg.UpdatedBy,
	)
	var i CbtRoomHandover
	err := row.Scan(
		&i.ID,
		&i.ExamRoomID,
		&i.AttendanceChecked,
		&i.AllSubmittedChecked,
		&i.DeviceIssueChecked,
		&i.RoomCleanChecked,
		&i.TokenReturnedChecked,
		&i.AssetsReturnedChecked,
		&i.IncidentNotes,
		&i.OperatorNotes,
		&i.HandoverNotes,
		&i.LockedAt,
		&i.LockedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
