// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: document_cycles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDocumentCycleCatalog = `-- name: CreateDocumentCycleCatalog :one
INSERT INTO document_cycle_catalogs (
    code,
    title,
    frequency,
    snp_standard,
    regulation_ref,
    default_owner_unit_id,
    default_responsible_employee_id,
    default_verifier_employee_id,
    deadline_days_after_period,
    reminder_days_before_due,
    description,
    is_active,
    sort_order
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13
)
RETURNING id, code, title, frequency, snp_standard, regulation_ref, default_owner_unit_id, default_responsible_employee_id, default_verifier_employee_id, deadline_days_after_period, reminder_days_before_due, description, is_active, sort_order, created_at, updated_at
`

type CreateDocumentCycleCatalogParams struct {
	Code                         string      `json:"code"`
	Title                        string      `json:"title"`
	Frequency                    string      `json:"frequency"`
	SnpStandard                  string      `json:"snp_standard"`
	RegulationRef                string      `json:"regulation_ref"`
	DefaultOwnerUnitID           pgtype.UUID `json:"default_owner_unit_id"`
	DefaultResponsibleEmployeeID pgtype.UUID `json:"default_responsible_employee_id"`
	DefaultVerifierEmployeeID    pgtype.UUID `json:"default_verifier_employee_id"`
	DeadlineDaysAfterPeriod      int32       `json:"deadline_days_after_period"`
	ReminderDaysBeforeDue        int32       `json:"reminder_days_before_due"`
	Description                  string      `json:"description"`
	IsActive                     bool        `json:"is_active"`
	SortOrder                    int32       `json:"sort_order"`
}

func (q *Queries) CreateDocumentCycleCatalog(ctx context.Context, arg CreateDocumentCycleCatalogParams) (DocumentCycleCatalog, error) {
	row := q.db.QueryRow(ctx, createDocumentCycleCatalog,
		arg.Code,
		arg.Title,
		arg.Frequency,
		arg.SnpStandard,
		arg.RegulationRef,
		arg.DefaultOwnerUnitID,
		arg.DefaultResponsibleEmployeeID,
		arg.DefaultVerifierEmployeeID,
		arg.DeadlineDaysAfterPeriod,
		arg.ReminderDaysBeforeDue,
		arg.Description,
		arg.IsActive,
		arg.SortOrder,
	)
	var i DocumentCycleCatalog
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Title,
		&i.Frequency,
		&i.SnpStandard,
		&i.RegulationRef,
		&i.DefaultOwnerUnitID,
		&i.DefaultResponsibleEmployeeID,
		&i.DefaultVerifierEmployeeID,
		&i.DeadlineDaysAfterPeriod,
		&i.ReminderDaysBeforeDue,
		&i.Description,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDocumentCycleEvent = `-- name: CreateDocumentCycleEvent :one
INSERT INTO document_cycle_events (
    obligation_id,
    event_type,
    from_status,
    to_status,
    notes,
    actor_user_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, obligation_id, event_type, from_status, to_status, notes, actor_user_id, created_at
`

type CreateDocumentCycleEventParams struct {
	ObligationID pgtype.UUID `json:"obligation_id"`
	EventType    string      `json:"event_type"`
	FromStatus   string      `json:"from_status"`
	ToStatus     string      `json:"to_status"`
	Notes        string      `json:"notes"`
	ActorUserID  pgtype.UUID `json:"actor_user_id"`
}

func (q *Queries) CreateDocumentCycleEvent(ctx context.Context, arg CreateDocumentCycleEventParams) (DocumentCycleEvent, error) {
	row := q.db.QueryRow(ctx, createDocumentCycleEvent,
		arg.ObligationID,
		arg.EventType,
		arg.FromStatus,
		arg.ToStatus,
		arg.Notes,
		arg.ActorUserID,
	)
	var i DocumentCycleEvent
	err := row.Scan(
		&i.ID,
		&i.ObligationID,
		&i.EventType,
		&i.FromStatus,
		&i.ToStatus,
		&i.Notes,
		&i.ActorUserID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDocumentCycleCatalog = `-- name: DeleteDocumentCycleCatalog :exec
DELETE FROM document_cycle_catalogs WHERE id = $1
`

func (q *Queries) DeleteDocumentCycleCatalog(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDocumentCycleCatalog, id)
	return err
}

const deleteDocumentCycleObligation = `-- name: DeleteDocumentCycleObligation :exec
DELETE FROM document_cycle_obligations WHERE id = $1
`

func (q *Queries) DeleteDocumentCycleObligation(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDocumentCycleObligation, id)
	return err
}

const ensureDocumentCycleObligation = `-- name: EnsureDocumentCycleObligation :one
INSERT INTO document_cycle_obligations (
    catalog_id,
    period_year,
    period_label,
    period_start,
    period_end,
    due_date,
    reminder_date,
    owner_unit_id,
    responsible_employee_id,
    verifier_employee_id,
    status,
    notes,
    created_by_user_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13
)
ON CONFLICT (catalog_id, period_year, period_label) DO UPDATE
SET updated_at = document_cycle_obligations.updated_at
RETURNING id, catalog_id, period_year, period_label, period_start, period_end, due_date, reminder_date, owner_unit_id, responsible_employee_id, verifier_employee_id, status, governance_document_id, evidence_item_id, archive_document_id, notes, verification_notes, completed_at, created_by_user_id, created_at, updated_at
`

type EnsureDocumentCycleObligationParams struct {
	CatalogID             pgtype.UUID `json:"catalog_id"`
	PeriodYear            int32       `json:"period_year"`
	PeriodLabel           string      `json:"period_label"`
	PeriodStart           pgtype.Date `json:"period_start"`
	PeriodEnd             pgtype.Date `json:"period_end"`
	DueDate               pgtype.Date `json:"due_date"`
	ReminderDate          pgtype.Date `json:"reminder_date"`
	OwnerUnitID           pgtype.UUID `json:"owner_unit_id"`
	ResponsibleEmployeeID pgtype.UUID `json:"responsible_employee_id"`
	VerifierEmployeeID    pgtype.UUID `json:"verifier_employee_id"`
	Status                string      `json:"status"`
	Notes                 string      `json:"notes"`
	CreatedByUserID       pgtype.UUID `json:"created_by_user_id"`
}

func (q *Queries) EnsureDocumentCycleObligation(ctx context.Context, arg EnsureDocumentCycleObligationParams) (DocumentCycleObligation, error) {
	row := q.db.QueryRow(ctx, ensureDocumentCycleObligation,
		arg.CatalogID,
		arg.PeriodYear,
		arg.PeriodLabel,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.DueDate,
		arg.ReminderDate,
		arg.OwnerUnitID,
		arg.ResponsibleEmployeeID,
		arg.VerifierEmployeeID,
		arg.Status,
		arg.Notes,
		arg.CreatedByUserID,
	)
	var i DocumentCycleObligation
	err := row.Scan(
		&i.ID,
		&i.CatalogID,
		&i.PeriodYear,
		&i.PeriodLabel,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.DueDate,
		&i.ReminderDate,
		&i.OwnerUnitID,
		&i.ResponsibleEmployeeID,
		&i.VerifierEmployeeID,
		&i.Status,
		&i.GovernanceDocumentID,
		&i.EvidenceItemID,
		&i.ArchiveDocumentID,
		&i.Notes,
		&i.VerificationNotes,
		&i.CompletedAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const generateDocumentCycleYearObligations = `-- name: GenerateDocumentCycleYearObligations :one
WITH params AS (
    SELECT
        $1::INT AS period_year,
        $2::UUID AS created_by_user_id
),
month_names(month_no, month_name) AS (
    VALUES
        (1, 'Januari'),
        (2, 'Februari'),
        (3, 'Maret'),
        (4, 'April'),
        (5, 'Mei'),
        (6, 'Juni'),
        (7, 'Juli'),
        (8, 'Agustus'),
        (9, 'September'),
        (10, 'Oktober'),
        (11, 'November'),
        (12, 'Desember')
),
quarter_periods(label, start_month, end_month) AS (
    VALUES
        ('Triwulan I', 1, 3),
        ('Triwulan II', 4, 6),
        ('Triwulan III', 7, 9),
        ('Triwulan IV', 10, 12)
),
semester_periods(label, start_month, end_month) AS (
    VALUES
        ('Semester I', 1, 6),
        ('Semester II', 7, 12)
),
raw_periods AS (
    SELECT
        c.id AS catalog_id,
        p.period_year,
        FORMAT('Bundel Harian %s %s', mn.month_name, p.period_year)::TEXT AS period_label,
        MAKE_DATE(p.period_year, mn.month_no, 1)::DATE AS period_start,
        (MAKE_DATE(p.period_year, mn.month_no, 1) + INTERVAL '1 month - 1 day')::DATE AS period_end,
        c.default_owner_unit_id,
        c.default_responsible_employee_id,
        c.default_verifier_employee_id,
        c.deadline_days_after_period,
        c.reminder_days_before_due,
        p.created_by_user_id
    FROM document_cycle_catalogs c
    CROSS JOIN params p
    CROSS JOIN month_names mn
    WHERE c.is_active = TRUE AND c.frequency = 'daily'

    UNION ALL

    SELECT
        c.id AS catalog_id,
        p.period_year,
        FORMAT('Minggu %s %s', LPAD(w.week_no::TEXT, 2, '0'), p.period_year)::TEXT AS period_label,
        w.period_start,
        w.period_end,
        c.default_owner_unit_id,
        c.default_responsible_employee_id,
        c.default_verifier_employee_id,
        c.deadline_days_after_period,
        c.reminder_days_before_due,
        p.created_by_user_id
    FROM document_cycle_catalogs c
    CROSS JOIN params p
    CROSS JOIN LATERAL (
        SELECT
            ROW_NUMBER() OVER (ORDER BY gs.period_start)::INT AS week_no,
            gs.period_start::DATE AS period_start,
            LEAST((gs.period_start + INTERVAL '6 days')::DATE, MAKE_DATE(p.period_year, 12, 31))::DATE AS period_end
        FROM GENERATE_SERIES(
            MAKE_DATE(p.period_year, 1, 1)::TIMESTAMP,
            MAKE_DATE(p.period_year, 12, 31)::TIMESTAMP,
            INTERVAL '7 days'
        ) AS gs(period_start)
    ) w
    WHERE c.is_active = TRUE AND c.frequency = 'weekly'

    UNION ALL

    SELECT
        c.id AS catalog_id,
        p.period_year,
        FORMAT('Bulanan %s %s', mn.month_name, p.period_year)::TEXT AS period_label,
        MAKE_DATE(p.period_year, mn.month_no, 1)::DATE AS period_start,
        (MAKE_DATE(p.period_year, mn.month_no, 1) + INTERVAL '1 month - 1 day')::DATE AS period_end,
        c.default_owner_unit_id,
        c.default_responsible_employee_id,
        c.default_verifier_employee_id,
        c.deadline_days_after_period,
        c.reminder_days_before_due,
        p.created_by_user_id
    FROM document_cycle_catalogs c
    CROSS JOIN params p
    CROSS JOIN month_names mn
    WHERE c.is_active = TRUE AND c.frequency = 'monthly'

    UNION ALL

    SELECT
        c.id AS catalog_id,
        p.period_year,
        FORMAT('%s %s', qp.label, p.period_year)::TEXT AS period_label,
        MAKE_DATE(p.period_year, qp.start_month, 1)::DATE AS period_start,
        (MAKE_DATE(p.period_year, qp.end_month, 1) + INTERVAL '1 month - 1 day')::DATE AS period_end,
        c.default_owner_unit_id,
        c.default_responsible_employee_id,
        c.default_verifier_employee_id,
        c.deadline_days_after_period,
        c.reminder_days_before_due,
        p.created_by_user_id
    FROM document_cycle_catalogs c
    CROSS JOIN params p
    CROSS JOIN quarter_periods qp
    WHERE c.is_active = TRUE AND c.frequency = 'quarterly'

    UNION ALL

    SELECT
        c.id AS catalog_id,
        p.period_year,
        FORMAT('%s %s', sp.label, p.period_year)::TEXT AS period_label,
        MAKE_DATE(p.period_year, sp.start_month, 1)::DATE AS period_start,
        (MAKE_DATE(p.period_year, sp.end_month, 1) + INTERVAL '1 month - 1 day')::DATE AS period_end,
        c.default_owner_unit_id,
        c.default_responsible_employee_id,
        c.default_verifier_employee_id,
        c.deadline_days_after_period,
        c.reminder_days_before_due,
        p.created_by_user_id
    FROM document_cycle_catalogs c
    CROSS JOIN params p
    CROSS JOIN semester_periods sp
    WHERE c.is_active = TRUE AND c.frequency = 'semester'

    UNION ALL

    SELECT
        c.id AS catalog_id,
        p.period_year,
        FORMAT('Tahunan %s', p.period_year)::TEXT AS period_label,
        MAKE_DATE(p.period_year, 1, 1)::DATE AS period_start,
        MAKE_DATE(p.period_year, 12, 31)::DATE AS period_end,
        c.default_owner_unit_id,
        c.default_responsible_employee_id,
        c.default_verifier_employee_id,
        c.deadline_days_after_period,
        c.reminder_days_before_due,
        p.created_by_user_id
    FROM document_cycle_catalogs c
    CROSS JOIN params p
    WHERE c.is_active = TRUE AND c.frequency = 'annual'

    UNION ALL

    SELECT
        c.id AS catalog_id,
        p.period_year,
        FORMAT('Periode %s-%s', p.period_year, p.period_year + 3)::TEXT AS period_label,
        MAKE_DATE(p.period_year, 1, 1)::DATE AS period_start,
        MAKE_DATE(p.period_year + 3, 12, 31)::DATE AS period_end,
        c.default_owner_unit_id,
        c.default_responsible_employee_id,
        c.default_verifier_employee_id,
        c.deadline_days_after_period,
        c.reminder_days_before_due,
        p.created_by_user_id
    FROM document_cycle_catalogs c
    CROSS JOIN params p
    WHERE c.is_active = TRUE AND c.frequency = 'four_year'

    UNION ALL

    SELECT
        c.id AS catalog_id,
        p.period_year,
        FORMAT('Periode %s-%s', p.period_year, p.period_year + 4)::TEXT AS period_label,
        MAKE_DATE(p.period_year, 1, 1)::DATE AS period_start,
        MAKE_DATE(p.period_year + 4, 12, 31)::DATE AS period_end,
        c.default_owner_unit_id,
        c.default_responsible_employee_id,
        c.default_verifier_employee_id,
        c.deadline_days_after_period,
        c.reminder_days_before_due,
        p.created_by_user_id
    FROM document_cycle_catalogs c
    CROSS JOIN params p
    WHERE c.is_active = TRUE AND c.frequency = 'five_year'
),
periods AS (
    SELECT
        catalog_id,
        period_year,
        period_label,
        period_start,
        period_end,
        (period_end + deadline_days_after_period::INT)::DATE AS due_date,
        ((period_end + deadline_days_after_period::INT)::DATE - reminder_days_before_due::INT)::DATE AS reminder_date,
        default_owner_unit_id AS owner_unit_id,
        default_responsible_employee_id AS responsible_employee_id,
        default_verifier_employee_id AS verifier_employee_id,
        'not_started'::TEXT AS status,
        ''::TEXT AS notes,
        created_by_user_id
    FROM raw_periods
),
inserted AS (
    INSERT INTO document_cycle_obligations (
        catalog_id,
        period_year,
        period_label,
        period_start,
        period_end,
        due_date,
        reminder_date,
        owner_unit_id,
        responsible_employee_id,
        verifier_employee_id,
        status,
        notes,
        created_by_user_id
    )
    SELECT
        catalog_id,
        period_year,
        period_label,
        period_start,
        period_end,
        due_date,
        reminder_date,
        owner_unit_id,
        responsible_employee_id,
        verifier_employee_id,
        status,
        notes,
        created_by_user_id
    FROM periods
    ON CONFLICT (catalog_id, period_year, period_label) DO NOTHING
    RETURNING id, status, created_by_user_id
),
events AS (
    INSERT INTO document_cycle_events (
        obligation_id,
        event_type,
        from_status,
        to_status,
        notes,
        actor_user_id
    )
    SELECT
        id,
        'generated',
        '',
        status,
        'Jadwal dokumen dibuat dari generator tahunan.',
        created_by_user_id
    FROM inserted
    RETURNING id
)
SELECT
    (SELECT COUNT(*) FROM periods)::INT AS generated,
    (SELECT COUNT(*) FROM inserted)::INT AS inserted,
    (SELECT COUNT(*) FROM events)::INT AS event_count
`

type GenerateDocumentCycleYearObligationsParams struct {
	PeriodYear      int32       `json:"period_year"`
	CreatedByUserID pgtype.UUID `json:"created_by_user_id"`
}

type GenerateDocumentCycleYearObligationsRow struct {
	Generated  int32 `json:"generated"`
	Inserted   int32 `json:"inserted"`
	EventCount int32 `json:"event_count"`
}

func (q *Queries) GenerateDocumentCycleYearObligations(ctx context.Context, arg GenerateDocumentCycleYearObligationsParams) (GenerateDocumentCycleYearObligationsRow, error) {
	row := q.db.QueryRow(ctx, generateDocumentCycleYearObligations, arg.PeriodYear, arg.CreatedByUserID)
	var i GenerateDocumentCycleYearObligationsRow
	err := row.Scan(&i.Generated, &i.Inserted, &i.EventCount)
	return i, err
}

const getDocumentCycleStats = `-- name: GetDocumentCycleStats :one
SELECT
    (SELECT COUNT(*) FROM document_cycle_catalogs WHERE is_active)::BIGINT AS active_catalogs,
    COUNT(*)::BIGINT AS total_obligations,
    COUNT(*) FILTER (WHERE status = 'not_started')::BIGINT AS not_started_obligations,
    COUNT(*) FILTER (WHERE status = 'draft')::BIGINT AS draft_obligations,
    COUNT(*) FILTER (WHERE status = 'waiting_verification')::BIGINT AS waiting_verification_obligations,
    COUNT(*) FILTER (WHERE status = 'completed')::BIGINT AS completed_obligations,
    COUNT(*) FILTER (WHERE status <> 'completed' AND due_date < CURRENT_DATE)::BIGINT AS overdue_obligations,
    COUNT(*) FILTER (
        WHERE status <> 'completed'
          AND reminder_date <= CURRENT_DATE
          AND due_date >= CURRENT_DATE
    )::BIGINT AS due_soon_obligations,
    COUNT(*) FILTER (WHERE responsible_employee_id IS NULL)::BIGINT AS no_pic_obligations
FROM document_cycle_obligations
WHERE $1::INT = 0 OR period_year = $1::INT
`

type GetDocumentCycleStatsRow struct {
	ActiveCatalogs                 int64 `json:"active_catalogs"`
	TotalObligations               int64 `json:"total_obligations"`
	NotStartedObligations          int64 `json:"not_started_obligations"`
	DraftObligations               int64 `json:"draft_obligations"`
	WaitingVerificationObligations int64 `json:"waiting_verification_obligations"`
	CompletedObligations           int64 `json:"completed_obligations"`
	OverdueObligations             int64 `json:"overdue_obligations"`
	DueSoonObligations             int64 `json:"due_soon_obligations"`
	NoPicObligations               int64 `json:"no_pic_obligations"`
}

func (q *Queries) GetDocumentCycleStats(ctx context.Context, periodYear int32) (GetDocumentCycleStatsRow, error) {
	row := q.db.QueryRow(ctx, getDocumentCycleStats, periodYear)
	var i GetDocumentCycleStatsRow
	err := row.Scan(
		&i.ActiveCatalogs,
		&i.TotalObligations,
		&i.NotStartedObligations,
		&i.DraftObligations,
		&i.WaitingVerificationObligations,
		&i.CompletedObligations,
		&i.OverdueObligations,
		&i.DueSoonObligations,
		&i.NoPicObligations,
	)
	return i, err
}

const listDocumentCycleCatalogs = `-- name: ListDocumentCycleCatalogs :many
SELECT
    c.id,
    c.code,
    c.title,
    c.frequency,
    c.snp_standard,
    c.regulation_ref,
    c.default_owner_unit_id,
    COALESCE(ou.name, '')::TEXT AS default_owner_unit_name,
    c.default_responsible_employee_id,
    COALESCE(re.nama, '')::TEXT AS default_responsible_employee_name,
    COALESCE(re.nip, '')::TEXT AS default_responsible_employee_nip,
    c.default_verifier_employee_id,
    COALESCE(ve.nama, '')::TEXT AS default_verifier_employee_name,
    COALESCE(ve.nip, '')::TEXT AS default_verifier_employee_nip,
    c.deadline_days_after_period,
    c.reminder_days_before_due,
    c.description,
    c.is_active,
    c.sort_order,
    c.created_at,
    c.updated_at
FROM document_cycle_catalogs c
LEFT JOIN governance_units ou ON ou.id = c.default_owner_unit_id
LEFT JOIN employees re ON re.id = c.default_responsible_employee_id
LEFT JOIN employees ve ON ve.id = c.default_verifier_employee_id
WHERE (
    $1::TEXT = '' OR
    c.code ILIKE '%' || $1 || '%' OR
    c.title ILIKE '%' || $1 || '%' OR
    c.description ILIKE '%' || $1 || '%' OR
    c.regulation_ref ILIKE '%' || $1 || '%'
) AND (
    $2::TEXT = '' OR c.frequency = $2
) AND (
    $3::BOOLEAN = FALSE OR c.is_active = TRUE
)
ORDER BY c.is_active DESC, c.sort_order, c.code
`

type ListDocumentCycleCatalogsParams struct {
	Search     string `json:"search"`
	Frequency  string `json:"frequency"`
	ActiveOnly bool   `json:"active_only"`
}

type ListDocumentCycleCatalogsRow struct {
	ID                             pgtype.UUID        `json:"id"`
	Code                           string             `json:"code"`
	Title                          string             `json:"title"`
	Frequency                      string             `json:"frequency"`
	SnpStandard                    string             `json:"snp_standard"`
	RegulationRef                  string             `json:"regulation_ref"`
	DefaultOwnerUnitID             pgtype.UUID        `json:"default_owner_unit_id"`
	DefaultOwnerUnitName           string             `json:"default_owner_unit_name"`
	DefaultResponsibleEmployeeID   pgtype.UUID        `json:"default_responsible_employee_id"`
	DefaultResponsibleEmployeeName string             `json:"default_responsible_employee_name"`
	DefaultResponsibleEmployeeNip  string             `json:"default_responsible_employee_nip"`
	DefaultVerifierEmployeeID      pgtype.UUID        `json:"default_verifier_employee_id"`
	DefaultVerifierEmployeeName    string             `json:"default_verifier_employee_name"`
	DefaultVerifierEmployeeNip     string             `json:"default_verifier_employee_nip"`
	DeadlineDaysAfterPeriod        int32              `json:"deadline_days_after_period"`
	ReminderDaysBeforeDue          int32              `json:"reminder_days_before_due"`
	Description                    string             `json:"description"`
	IsActive                       bool               `json:"is_active"`
	SortOrder                      int32              `json:"sort_order"`
	CreatedAt                      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListDocumentCycleCatalogs(ctx context.Context, arg ListDocumentCycleCatalogsParams) ([]ListDocumentCycleCatalogsRow, error) {
	rows, err := q.db.Query(ctx, listDocumentCycleCatalogs, arg.Search, arg.Frequency, arg.ActiveOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentCycleCatalogsRow{}
	for rows.Next() {
		var i ListDocumentCycleCatalogsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Title,
			&i.Frequency,
			&i.SnpStandard,
			&i.RegulationRef,
			&i.DefaultOwnerUnitID,
			&i.DefaultOwnerUnitName,
			&i.DefaultResponsibleEmployeeID,
			&i.DefaultResponsibleEmployeeName,
			&i.DefaultResponsibleEmployeeNip,
			&i.DefaultVerifierEmployeeID,
			&i.DefaultVerifierEmployeeName,
			&i.DefaultVerifierEmployeeNip,
			&i.DeadlineDaysAfterPeriod,
			&i.ReminderDaysBeforeDue,
			&i.Description,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentCycleObligations = `-- name: ListDocumentCycleObligations :many
SELECT
    o.id,
    o.catalog_id,
    c.code AS catalog_code,
    c.title AS catalog_title,
    c.frequency,
    c.snp_standard,
    c.regulation_ref,
    o.period_year,
    o.period_label,
    o.period_start,
    o.period_end,
    o.due_date,
    o.reminder_date,
    o.owner_unit_id,
    COALESCE(ou.name, '')::TEXT AS owner_unit_name,
    o.responsible_employee_id,
    COALESCE(re.nama, '')::TEXT AS responsible_employee_name,
    COALESCE(re.nip, '')::TEXT AS responsible_employee_nip,
    o.verifier_employee_id,
    COALESCE(ve.nama, '')::TEXT AS verifier_employee_name,
    COALESCE(ve.nip, '')::TEXT AS verifier_employee_nip,
    o.status,
    o.governance_document_id,
    COALESCE(gd.title, '')::TEXT AS governance_document_title,
    o.evidence_item_id,
    COALESCE(ge.title, '')::TEXT AS evidence_item_title,
    o.archive_document_id,
    COALESCE(ad.title, '')::TEXT AS archive_document_title,
    o.notes,
    o.verification_notes,
    o.completed_at,
    o.created_by_user_id,
    o.created_at,
    o.updated_at,
    (o.status <> 'completed' AND o.due_date < CURRENT_DATE)::BOOLEAN AS is_overdue,
    (o.status <> 'completed' AND o.reminder_date <= CURRENT_DATE AND o.due_date >= CURRENT_DATE)::BOOLEAN AS is_due_soon
FROM document_cycle_obligations o
JOIN document_cycle_catalogs c ON c.id = o.catalog_id
LEFT JOIN governance_units ou ON ou.id = o.owner_unit_id
LEFT JOIN employees re ON re.id = o.responsible_employee_id
LEFT JOIN employees ve ON ve.id = o.verifier_employee_id
LEFT JOIN governance_documents gd ON gd.id = o.governance_document_id
LEFT JOIN governance_evidence_items ge ON ge.id = o.evidence_item_id
LEFT JOIN archive_documents ad ON ad.id = o.archive_document_id
WHERE (
    $1::TEXT = '' OR
    c.code ILIKE '%' || $1 || '%' OR
    c.title ILIKE '%' || $1 || '%' OR
    o.period_label ILIKE '%' || $1 || '%' OR
    o.notes ILIKE '%' || $1 || '%'
) AND (
    $2::TEXT = '' OR o.status = $2
) AND (
    $3::TEXT = '' OR c.frequency = $3
) AND (
    $4::INT = 0 OR o.period_year = $4::INT
) AND (
    $5::UUID IS NULL OR o.owner_unit_id = $5::UUID
) AND (
    $6::UUID IS NULL OR o.responsible_employee_id = $6::UUID
) AND (
    $7::BOOLEAN = FALSE OR (
        o.status <> 'completed'
        AND o.reminder_date <= CURRENT_DATE
    )
)
ORDER BY
    CASE
        WHEN o.status <> 'completed' AND o.due_date < CURRENT_DATE THEN 0
        WHEN o.status <> 'completed' AND o.reminder_date <= CURRENT_DATE THEN 1
        WHEN o.status = 'waiting_verification' THEN 2
        WHEN o.status = 'draft' THEN 3
        WHEN o.status = 'not_started' THEN 4
        ELSE 5
    END,
    o.due_date ASC,
    c.sort_order,
    c.code
`

type ListDocumentCycleObligationsParams struct {
	Search                string      `json:"search"`
	Status                string      `json:"status"`
	Frequency             string      `json:"frequency"`
	PeriodYear            int32       `json:"period_year"`
	OwnerUnitID           pgtype.UUID `json:"owner_unit_id"`
	ResponsibleEmployeeID pgtype.UUID `json:"responsible_employee_id"`
	ReminderOnly          bool        `json:"reminder_only"`
}

type ListDocumentCycleObligationsRow struct {
	ID                      pgtype.UUID        `json:"id"`
	CatalogID               pgtype.UUID        `json:"catalog_id"`
	CatalogCode             string             `json:"catalog_code"`
	CatalogTitle            string             `json:"catalog_title"`
	Frequency               string             `json:"frequency"`
	SnpStandard             string             `json:"snp_standard"`
	RegulationRef           string             `json:"regulation_ref"`
	PeriodYear              int32              `json:"period_year"`
	PeriodLabel             string             `json:"period_label"`
	PeriodStart             pgtype.Date        `json:"period_start"`
	PeriodEnd               pgtype.Date        `json:"period_end"`
	DueDate                 pgtype.Date        `json:"due_date"`
	ReminderDate            pgtype.Date        `json:"reminder_date"`
	OwnerUnitID             pgtype.UUID        `json:"owner_unit_id"`
	OwnerUnitName           string             `json:"owner_unit_name"`
	ResponsibleEmployeeID   pgtype.UUID        `json:"responsible_employee_id"`
	ResponsibleEmployeeName string             `json:"responsible_employee_name"`
	ResponsibleEmployeeNip  string             `json:"responsible_employee_nip"`
	VerifierEmployeeID      pgtype.UUID        `json:"verifier_employee_id"`
	VerifierEmployeeName    string             `json:"verifier_employee_name"`
	VerifierEmployeeNip     string             `json:"verifier_employee_nip"`
	Status                  string             `json:"status"`
	GovernanceDocumentID    pgtype.UUID        `json:"governance_document_id"`
	GovernanceDocumentTitle string             `json:"governance_document_title"`
	EvidenceItemID          pgtype.UUID        `json:"evidence_item_id"`
	EvidenceItemTitle       string             `json:"evidence_item_title"`
	ArchiveDocumentID       pgtype.UUID        `json:"archive_document_id"`
	ArchiveDocumentTitle    string             `json:"archive_document_title"`
	Notes                   string             `json:"notes"`
	VerificationNotes       string             `json:"verification_notes"`
	CompletedAt             pgtype.Timestamptz `json:"completed_at"`
	CreatedByUserID         pgtype.UUID        `json:"created_by_user_id"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	IsOverdue               bool               `json:"is_overdue"`
	IsDueSoon               bool               `json:"is_due_soon"`
}

func (q *Queries) ListDocumentCycleObligations(ctx context.Context, arg ListDocumentCycleObligationsParams) ([]ListDocumentCycleObligationsRow, error) {
	rows, err := q.db.Query(ctx, listDocumentCycleObligations,
		arg.Search,
		arg.Status,
		arg.Frequency,
		arg.PeriodYear,
		arg.OwnerUnitID,
		arg.ResponsibleEmployeeID,
		arg.ReminderOnly,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentCycleObligationsRow{}
	for rows.Next() {
		var i ListDocumentCycleObligationsRow
		if err := rows.Scan(
			&i.ID,
			&i.CatalogID,
			&i.CatalogCode,
			&i.CatalogTitle,
			&i.Frequency,
			&i.SnpStandard,
			&i.RegulationRef,
			&i.PeriodYear,
			&i.PeriodLabel,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.DueDate,
			&i.ReminderDate,
			&i.OwnerUnitID,
			&i.OwnerUnitName,
			&i.ResponsibleEmployeeID,
			&i.ResponsibleEmployeeName,
			&i.ResponsibleEmployeeNip,
			&i.VerifierEmployeeID,
			&i.VerifierEmployeeName,
			&i.VerifierEmployeeNip,
			&i.Status,
			&i.GovernanceDocumentID,
			&i.GovernanceDocumentTitle,
			&i.EvidenceItemID,
			&i.EvidenceItemTitle,
			&i.ArchiveDocumentID,
			&i.ArchiveDocumentTitle,
			&i.Notes,
			&i.VerificationNotes,
			&i.CompletedAt,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsOverdue,
			&i.IsDueSoon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocumentCycleCatalog = `-- name: UpdateDocumentCycleCatalog :one
UPDATE document_cycle_catalogs
SET code = $1,
    title = $2,
    frequency = $3,
    snp_standard = $4,
    regulation_ref = $5,
    default_owner_unit_id = $6,
    default_responsible_employee_id = $7,
    default_verifier_employee_id = $8,
    deadline_days_after_period = $9,
    reminder_days_before_due = $10,
    description = $11,
    is_active = $12,
    sort_order = $13,
    updated_at = NOW()
WHERE id = $14
RETURNING id, code, title, frequency, snp_standard, regulation_ref, default_owner_unit_id, default_responsible_employee_id, default_verifier_employee_id, deadline_days_after_period, reminder_days_before_due, description, is_active, sort_order, created_at, updated_at
`

type UpdateDocumentCycleCatalogParams struct {
	Code                         string      `json:"code"`
	Title                        string      `json:"title"`
	Frequency                    string      `json:"frequency"`
	SnpStandard                  string      `json:"snp_standard"`
	RegulationRef                string      `json:"regulation_ref"`
	DefaultOwnerUnitID           pgtype.UUID `json:"default_owner_unit_id"`
	DefaultResponsibleEmployeeID pgtype.UUID `json:"default_responsible_employee_id"`
	DefaultVerifierEmployeeID    pgtype.UUID `json:"default_verifier_employee_id"`
	DeadlineDaysAfterPeriod      int32       `json:"deadline_days_after_period"`
	ReminderDaysBeforeDue        int32       `json:"reminder_days_before_due"`
	Description                  string      `json:"description"`
	IsActive                     bool        `json:"is_active"`
	SortOrder                    int32       `json:"sort_order"`
	ID                           pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateDocumentCycleCatalog(ctx context.Context, arg UpdateDocumentCycleCatalogParams) (DocumentCycleCatalog, error) {
	row := q.db.QueryRow(ctx, updateDocumentCycleCatalog,
		arg.Code,
		arg.Title,
		arg.Frequency,
		arg.SnpStandard,
		arg.RegulationRef,
		arg.DefaultOwnerUnitID,
		arg.DefaultResponsibleEmployeeID,
		arg.DefaultVerifierEmployeeID,
		arg.DeadlineDaysAfterPeriod,
		arg.ReminderDaysBeforeDue,
		arg.Description,
		arg.IsActive,
		arg.SortOrder,
		arg.ID,
	)
	var i DocumentCycleCatalog
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Title,
		&i.Frequency,
		&i.SnpStandard,
		&i.RegulationRef,
		&i.DefaultOwnerUnitID,
		&i.DefaultResponsibleEmployeeID,
		&i.DefaultVerifierEmployeeID,
		&i.DeadlineDaysAfterPeriod,
		&i.ReminderDaysBeforeDue,
		&i.Description,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDocumentCycleObligation = `-- name: UpdateDocumentCycleObligation :one
UPDATE document_cycle_obligations
SET due_date = $1,
    reminder_date = $2,
    owner_unit_id = $3,
    responsible_employee_id = $4,
    verifier_employee_id = $5,
    governance_document_id = $6,
    evidence_item_id = $7,
    archive_document_id = $8,
    notes = $9,
    verification_notes = $10,
    updated_at = NOW()
WHERE id = $11
RETURNING id, catalog_id, period_year, period_label, period_start, period_end, due_date, reminder_date, owner_unit_id, responsible_employee_id, verifier_employee_id, status, governance_document_id, evidence_item_id, archive_document_id, notes, verification_notes, completed_at, created_by_user_id, created_at, updated_at
`

type UpdateDocumentCycleObligationParams struct {
	DueDate               pgtype.Date `json:"due_date"`
	ReminderDate          pgtype.Date `json:"reminder_date"`
	OwnerUnitID           pgtype.UUID `json:"owner_unit_id"`
	ResponsibleEmployeeID pgtype.UUID `json:"responsible_employee_id"`
	VerifierEmployeeID    pgtype.UUID `json:"verifier_employee_id"`
	GovernanceDocumentID  pgtype.UUID `json:"governance_document_id"`
	EvidenceItemID        pgtype.UUID `json:"evidence_item_id"`
	ArchiveDocumentID     pgtype.UUID `json:"archive_document_id"`
	Notes                 string      `json:"notes"`
	VerificationNotes     string      `json:"verification_notes"`
	ID                    pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateDocumentCycleObligation(ctx context.Context, arg UpdateDocumentCycleObligationParams) (DocumentCycleObligation, error) {
	row := q.db.QueryRow(ctx, updateDocumentCycleObligation,
		arg.DueDate,
		arg.ReminderDate,
		arg.OwnerUnitID,
		arg.ResponsibleEmployeeID,
		arg.VerifierEmployeeID,
		arg.GovernanceDocumentID,
		arg.EvidenceItemID,
		arg.ArchiveDocumentID,
		arg.Notes,
		arg.VerificationNotes,
		arg.ID,
	)
	var i DocumentCycleObligation
	err := row.Scan(
		&i.ID,
		&i.CatalogID,
		&i.PeriodYear,
		&i.PeriodLabel,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.DueDate,
		&i.ReminderDate,
		&i.OwnerUnitID,
		&i.ResponsibleEmployeeID,
		&i.VerifierEmployeeID,
		&i.Status,
		&i.GovernanceDocumentID,
		&i.EvidenceItemID,
		&i.ArchiveDocumentID,
		&i.Notes,
		&i.VerificationNotes,
		&i.CompletedAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDocumentCycleObligationStatus = `-- name: UpdateDocumentCycleObligationStatus :one
UPDATE document_cycle_obligations
SET status = $1,
    notes = CASE
        WHEN $2::TEXT = '' THEN notes
        ELSE $2
    END,
    verification_notes = CASE
        WHEN $1::TEXT IN ('waiting_verification', 'completed') AND $2::TEXT <> '' THEN $2
        ELSE verification_notes
    END,
    completed_at = CASE
        WHEN $1::TEXT = 'completed' THEN NOW()
        ELSE NULL
    END,
    updated_at = NOW()
WHERE id = $3
RETURNING id, catalog_id, period_year, period_label, period_start, period_end, due_date, reminder_date, owner_unit_id, responsible_employee_id, verifier_employee_id, status, governance_document_id, evidence_item_id, archive_document_id, notes, verification_notes, completed_at, created_by_user_id, created_at, updated_at
`

type UpdateDocumentCycleObligationStatusParams struct {
	Status string      `json:"status"`
	Notes  string      `json:"notes"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateDocumentCycleObligationStatus(ctx context.Context, arg UpdateDocumentCycleObligationStatusParams) (DocumentCycleObligation, error) {
	row := q.db.QueryRow(ctx, updateDocumentCycleObligationStatus, arg.Status, arg.Notes, arg.ID)
	var i DocumentCycleObligation
	err := row.Scan(
		&i.ID,
		&i.CatalogID,
		&i.PeriodYear,
		&i.PeriodLabel,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.DueDate,
		&i.ReminderDate,
		&i.OwnerUnitID,
		&i.ResponsibleEmployeeID,
		&i.VerifierEmployeeID,
		&i.Status,
		&i.GovernanceDocumentID,
		&i.EvidenceItemID,
		&i.ArchiveDocumentID,
		&i.Notes,
		&i.VerificationNotes,
		&i.CompletedAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
