// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: employees.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEmployees = `-- name: CountEmployees :one
SELECT COUNT(*) FROM employees
`

func (q *Queries) CountEmployees(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countEmployees)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employees (id, nip, nama, unit_kerja, employment_type, tanggal_lahir, is_active)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6)
RETURNING id, nip, nama, unit_kerja, is_active, created_at, updated_at, employment_type, tanggal_lahir, phone, email, address, photo_url
`

type CreateEmployeeParams struct {
	Nip            string      `json:"nip"`
	Nama           string      `json:"nama"`
	UnitKerja      string      `json:"unit_kerja"`
	EmploymentType string      `json:"employment_type"`
	TanggalLahir   pgtype.Date `json:"tanggal_lahir"`
	IsActive       bool        `json:"is_active"`
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.Nip,
		arg.Nama,
		arg.UnitKerja,
		arg.EmploymentType,
		arg.TanggalLahir,
		arg.IsActive,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.Nip,
		&i.Nama,
		&i.UnitKerja,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmploymentType,
		&i.TanggalLahir,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.PhotoUrl,
	)
	return i, err
}

const deleteEmployee = `-- name: DeleteEmployee :exec
DELETE FROM employees WHERE id = $1
`

func (q *Queries) DeleteEmployee(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmployee, id)
	return err
}

const getEmployee = `-- name: GetEmployee :one
SELECT e.id, e.nip, e.nama, e.unit_kerja, e.employment_type, e.tanggal_lahir,
       COALESCE(pa.pusaka_username, '') AS pusaka_username,
       COALESCE(pa.pusaka_password, '') AS pusaka_password,
       COALESCE(pa.is_enabled, FALSE) AS pusaka_is_enabled,
       e.is_active, e.created_at, e.updated_at
FROM employees e
LEFT JOIN pusaka_accounts pa ON pa.employee_id = e.id
WHERE e.id = $1
`

type GetEmployeeRow struct {
	ID              pgtype.UUID        `json:"id"`
	Nip             string             `json:"nip"`
	Nama            string             `json:"nama"`
	UnitKerja       string             `json:"unit_kerja"`
	EmploymentType  string             `json:"employment_type"`
	TanggalLahir    pgtype.Date        `json:"tanggal_lahir"`
	PusakaUsername  string             `json:"pusaka_username"`
	PusakaPassword  string             `json:"pusaka_password"`
	PusakaIsEnabled bool               `json:"pusaka_is_enabled"`
	IsActive        bool               `json:"is_active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetEmployee(ctx context.Context, id pgtype.UUID) (GetEmployeeRow, error) {
	row := q.db.QueryRow(ctx, getEmployee, id)
	var i GetEmployeeRow
	err := row.Scan(
		&i.ID,
		&i.Nip,
		&i.Nama,
		&i.UnitKerja,
		&i.EmploymentType,
		&i.TanggalLahir,
		&i.PusakaUsername,
		&i.PusakaPassword,
		&i.PusakaIsEnabled,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveEmployees = `-- name: ListActiveEmployees :many
SELECT e.id, e.nip, e.nama, e.unit_kerja, e.employment_type, e.tanggal_lahir,
       COALESCE(pa.pusaka_username, '') AS pusaka_username,
       COALESCE(pa.pusaka_password, '') AS pusaka_password,
       COALESCE(pa.is_enabled, FALSE) AS pusaka_is_enabled,
       e.is_active, e.created_at, e.updated_at
FROM employees e
JOIN pusaka_accounts pa ON pa.employee_id = e.id
WHERE e.is_active = TRUE
  AND pa.is_enabled = TRUE
  AND pa.pusaka_username <> ''
  AND pa.pusaka_password <> ''
ORDER BY nama ASC
`

type ListActiveEmployeesRow struct {
	ID              pgtype.UUID        `json:"id"`
	Nip             string             `json:"nip"`
	Nama            string             `json:"nama"`
	UnitKerja       string             `json:"unit_kerja"`
	EmploymentType  string             `json:"employment_type"`
	TanggalLahir    pgtype.Date        `json:"tanggal_lahir"`
	PusakaUsername  string             `json:"pusaka_username"`
	PusakaPassword  string             `json:"pusaka_password"`
	PusakaIsEnabled bool               `json:"pusaka_is_enabled"`
	IsActive        bool               `json:"is_active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListActiveEmployees(ctx context.Context) ([]ListActiveEmployeesRow, error) {
	rows, err := q.db.Query(ctx, listActiveEmployees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveEmployeesRow{}
	for rows.Next() {
		var i ListActiveEmployeesRow
		if err := rows.Scan(
			&i.ID,
			&i.Nip,
			&i.Nama,
			&i.UnitKerja,
			&i.EmploymentType,
			&i.TanggalLahir,
			&i.PusakaUsername,
			&i.PusakaPassword,
			&i.PusakaIsEnabled,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployees = `-- name: ListEmployees :many
SELECT e.id, e.nip, e.nama, e.unit_kerja, e.employment_type, e.tanggal_lahir,
       COALESCE(pa.pusaka_username, '') AS pusaka_username,
       COALESCE(pa.pusaka_password, '') AS pusaka_password,
       COALESCE(pa.is_enabled, FALSE) AS pusaka_is_enabled,
       e.is_active, e.created_at, e.updated_at
FROM employees e
LEFT JOIN pusaka_accounts pa ON pa.employee_id = e.id
ORDER BY nama ASC
`

type ListEmployeesRow struct {
	ID              pgtype.UUID        `json:"id"`
	Nip             string             `json:"nip"`
	Nama            string             `json:"nama"`
	UnitKerja       string             `json:"unit_kerja"`
	EmploymentType  string             `json:"employment_type"`
	TanggalLahir    pgtype.Date        `json:"tanggal_lahir"`
	PusakaUsername  string             `json:"pusaka_username"`
	PusakaPassword  string             `json:"pusaka_password"`
	PusakaIsEnabled bool               `json:"pusaka_is_enabled"`
	IsActive        bool               `json:"is_active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListEmployees(ctx context.Context) ([]ListEmployeesRow, error) {
	rows, err := q.db.Query(ctx, listEmployees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeesRow{}
	for rows.Next() {
		var i ListEmployeesRow
		if err := rows.Scan(
			&i.ID,
			&i.Nip,
			&i.Nama,
			&i.UnitKerja,
			&i.EmploymentType,
			&i.TanggalLahir,
			&i.PusakaUsername,
			&i.PusakaPassword,
			&i.PusakaIsEnabled,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeesWithStatus = `-- name: ListEmployeesWithStatus :many
SELECT e.id, e.nip, e.nama, e.unit_kerja, e.employment_type, e.tanggal_lahir, COALESCE(pa.pusaka_username, '') AS pusaka_username, COALESCE(pa.is_enabled, FALSE) AS pusaka_is_enabled, e.is_active, e.created_at,
  COALESCE(
    (SELECT j.status::text FROM jobs j
     WHERE j.employee_id = e.id AND (j.status = 'queued' OR j.status = 'running')
     ORDER BY CASE j.status::text WHEN 'running' THEN 0 ELSE 1 END, j.created_at DESC
     LIMIT 1), '') AS active_status,
  COALESCE(
    (SELECT j.run_type::text FROM jobs j
     WHERE j.employee_id = e.id AND (j.status = 'queued' OR j.status = 'running')
     ORDER BY CASE j.status::text WHEN 'running' THEN 0 ELSE 1 END, j.created_at DESC
     LIMIT 1), '') AS active_run_type,
  COALESCE(
    (SELECT j.status::text FROM jobs j
     WHERE j.employee_id = e.id ORDER BY j.created_at DESC LIMIT 1), '') AS last_status,
  COALESCE(
    (SELECT j.run_type::text FROM jobs j
     WHERE j.employee_id = e.id ORDER BY j.created_at DESC LIMIT 1), '') AS last_run_type,
  EXISTS(
    SELECT 1 FROM employee_schedules es
    WHERE es.employee_id = e.id AND es.run_type = 'checkin' AND es.is_enabled = TRUE
  ) AS has_checkin_schedule,
  EXISTS(
    SELECT 1 FROM employee_schedules es
    WHERE es.employee_id = e.id AND es.run_type = 'checkout' AND es.is_enabled = TRUE
  ) AS has_checkout_schedule,
  (e.employment_type IN ('pns', 'pppk')) AS pusaka_eligible,
  COALESCE((pa.employee_id IS NOT NULL AND pa.pusaka_username <> ''), FALSE) AS has_pusaka_account
FROM employees e
LEFT JOIN pusaka_accounts pa ON pa.employee_id = e.id
ORDER BY e.created_at DESC
`

type ListEmployeesWithStatusRow struct {
	ID                  pgtype.UUID        `json:"id"`
	Nip                 string             `json:"nip"`
	Nama                string             `json:"nama"`
	UnitKerja           string             `json:"unit_kerja"`
	EmploymentType      string             `json:"employment_type"`
	TanggalLahir        pgtype.Date        `json:"tanggal_lahir"`
	PusakaUsername      string             `json:"pusaka_username"`
	PusakaIsEnabled     bool               `json:"pusaka_is_enabled"`
	IsActive            bool               `json:"is_active"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	ActiveStatus        interface{}        `json:"active_status"`
	ActiveRunType       interface{}        `json:"active_run_type"`
	LastStatus          interface{}        `json:"last_status"`
	LastRunType         interface{}        `json:"last_run_type"`
	HasCheckinSchedule  bool               `json:"has_checkin_schedule"`
	HasCheckoutSchedule bool               `json:"has_checkout_schedule"`
	PusakaEligible      bool               `json:"pusaka_eligible"`
	HasPusakaAccount    interface{}        `json:"has_pusaka_account"`
}

func (q *Queries) ListEmployeesWithStatus(ctx context.Context) ([]ListEmployeesWithStatusRow, error) {
	rows, err := q.db.Query(ctx, listEmployeesWithStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeesWithStatusRow{}
	for rows.Next() {
		var i ListEmployeesWithStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.Nip,
			&i.Nama,
			&i.UnitKerja,
			&i.EmploymentType,
			&i.TanggalLahir,
			&i.PusakaUsername,
			&i.PusakaIsEnabled,
			&i.IsActive,
			&i.CreatedAt,
			&i.ActiveStatus,
			&i.ActiveRunType,
			&i.LastStatus,
			&i.LastRunType,
			&i.HasCheckinSchedule,
			&i.HasCheckoutSchedule,
			&i.PusakaEligible,
			&i.HasPusakaAccount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPusakaEligibleEmployeesWithStatus = `-- name: ListPusakaEligibleEmployeesWithStatus :many
SELECT e.id, e.nip, e.nama, e.unit_kerja, e.employment_type, e.tanggal_lahir, COALESCE(pa.pusaka_username, '') AS pusaka_username, COALESCE(pa.is_enabled, FALSE) AS pusaka_is_enabled, e.is_active, e.created_at,
  COALESCE(
    (SELECT j.status::text FROM jobs j
     WHERE j.employee_id = e.id AND (j.status = 'queued' OR j.status = 'running')
     ORDER BY CASE j.status::text WHEN 'running' THEN 0 ELSE 1 END, j.created_at DESC
     LIMIT 1), '') AS active_status,
  COALESCE(
    (SELECT j.run_type::text FROM jobs j
     WHERE j.employee_id = e.id AND (j.status = 'queued' OR j.status = 'running')
     ORDER BY CASE j.status::text WHEN 'running' THEN 0 ELSE 1 END, j.created_at DESC
     LIMIT 1), '') AS active_run_type,
  COALESCE(
    (SELECT j.status::text FROM jobs j
     WHERE j.employee_id = e.id ORDER BY j.created_at DESC LIMIT 1), '') AS last_status,
  COALESCE(
    (SELECT j.run_type::text FROM jobs j
     WHERE j.employee_id = e.id ORDER BY j.created_at DESC LIMIT 1), '') AS last_run_type,
  EXISTS(
    SELECT 1 FROM employee_schedules es
    WHERE es.employee_id = e.id AND es.run_type = 'checkin' AND es.is_enabled = TRUE
  ) AS has_checkin_schedule,
  EXISTS(
    SELECT 1 FROM employee_schedules es
    WHERE es.employee_id = e.id AND es.run_type = 'checkout' AND es.is_enabled = TRUE
  ) AS has_checkout_schedule,
  TRUE AS pusaka_eligible,
  COALESCE((pa.employee_id IS NOT NULL AND pa.pusaka_username <> ''), FALSE) AS has_pusaka_account
FROM employees e
LEFT JOIN pusaka_accounts pa ON pa.employee_id = e.id
WHERE e.employment_type IN ('pns', 'pppk')
ORDER BY e.created_at DESC
`

type ListPusakaEligibleEmployeesWithStatusRow struct {
	ID                  pgtype.UUID        `json:"id"`
	Nip                 string             `json:"nip"`
	Nama                string             `json:"nama"`
	UnitKerja           string             `json:"unit_kerja"`
	EmploymentType      string             `json:"employment_type"`
	TanggalLahir        pgtype.Date        `json:"tanggal_lahir"`
	PusakaUsername      string             `json:"pusaka_username"`
	PusakaIsEnabled     bool               `json:"pusaka_is_enabled"`
	IsActive            bool               `json:"is_active"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	ActiveStatus        interface{}        `json:"active_status"`
	ActiveRunType       interface{}        `json:"active_run_type"`
	LastStatus          interface{}        `json:"last_status"`
	LastRunType         interface{}        `json:"last_run_type"`
	HasCheckinSchedule  bool               `json:"has_checkin_schedule"`
	HasCheckoutSchedule bool               `json:"has_checkout_schedule"`
	PusakaEligible      bool               `json:"pusaka_eligible"`
	HasPusakaAccount    interface{}        `json:"has_pusaka_account"`
}

func (q *Queries) ListPusakaEligibleEmployeesWithStatus(ctx context.Context) ([]ListPusakaEligibleEmployeesWithStatusRow, error) {
	rows, err := q.db.Query(ctx, listPusakaEligibleEmployeesWithStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPusakaEligibleEmployeesWithStatusRow{}
	for rows.Next() {
		var i ListPusakaEligibleEmployeesWithStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.Nip,
			&i.Nama,
			&i.UnitKerja,
			&i.EmploymentType,
			&i.TanggalLahir,
			&i.PusakaUsername,
			&i.PusakaIsEnabled,
			&i.IsActive,
			&i.CreatedAt,
			&i.ActiveStatus,
			&i.ActiveRunType,
			&i.LastStatus,
			&i.LastRunType,
			&i.HasCheckinSchedule,
			&i.HasCheckoutSchedule,
			&i.PusakaEligible,
			&i.HasPusakaAccount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmployee = `-- name: UpdateEmployee :one
UPDATE employees
SET nip             = $2,
    nama            = $3,
    unit_kerja      = $4,
    employment_type = $5,
    tanggal_lahir   = $6,
    is_active       = $7,
    updated_at      = NOW()
WHERE id = $1
RETURNING id, nip, nama, unit_kerja, is_active, created_at, updated_at, employment_type, tanggal_lahir, phone, email, address, photo_url
`

type UpdateEmployeeParams struct {
	ID             pgtype.UUID `json:"id"`
	Nip            string      `json:"nip"`
	Nama           string      `json:"nama"`
	UnitKerja      string      `json:"unit_kerja"`
	EmploymentType string      `json:"employment_type"`
	TanggalLahir   pgtype.Date `json:"tanggal_lahir"`
	IsActive       bool        `json:"is_active"`
}

func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, updateEmployee,
		arg.ID,
		arg.Nip,
		arg.Nama,
		arg.UnitKerja,
		arg.EmploymentType,
		arg.TanggalLahir,
		arg.IsActive,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.Nip,
		&i.Nama,
		&i.UnitKerja,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmploymentType,
		&i.TanggalLahir,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.PhotoUrl,
	)
	return i, err
}
