// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: governance.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGovernanceAssignment = `-- name: CreateGovernanceAssignment :one
INSERT INTO governance_assignments (
    position_id, employee_id, start_date, end_date, decree_outgoing_letter_id, notes
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, position_id, employee_id, start_date, end_date, decree_outgoing_letter_id, notes, created_at, updated_at
`

type CreateGovernanceAssignmentParams struct {
	PositionID             pgtype.UUID `json:"position_id"`
	EmployeeID             pgtype.UUID `json:"employee_id"`
	StartDate              pgtype.Date `json:"start_date"`
	EndDate                pgtype.Date `json:"end_date"`
	DecreeOutgoingLetterID pgtype.UUID `json:"decree_outgoing_letter_id"`
	Notes                  string      `json:"notes"`
}

func (q *Queries) CreateGovernanceAssignment(ctx context.Context, arg CreateGovernanceAssignmentParams) (GovernanceAssignment, error) {
	row := q.db.QueryRow(ctx, createGovernanceAssignment,
		arg.PositionID,
		arg.EmployeeID,
		arg.StartDate,
		arg.EndDate,
		arg.DecreeOutgoingLetterID,
		arg.Notes,
	)
	var i GovernanceAssignment
	err := row.Scan(
		&i.ID,
		&i.PositionID,
		&i.EmployeeID,
		&i.StartDate,
		&i.EndDate,
		&i.DecreeOutgoingLetterID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGovernanceComplianceAction = `-- name: CreateGovernanceComplianceAction :one
INSERT INTO governance_compliance_actions (
    period_year, source_type, source_ref_id, snp_standard, program_id, document_id,
    performance_target_id, evidence_item_id, owner_unit_id, responsible_employee_id,
    title, description, priority, status, due_date, completed_at, follow_up_notes,
    evidence_url, created_by_user_id
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19
)
RETURNING id, period_year, source_type, source_ref_id, snp_standard, program_id, document_id, performance_target_id, evidence_item_id, owner_unit_id, responsible_employee_id, title, description, priority, status, due_date, completed_at, follow_up_notes, evidence_url, created_by_user_id, created_at, updated_at
`

type CreateGovernanceComplianceActionParams struct {
	PeriodYear            int32              `json:"period_year"`
	SourceType            string             `json:"source_type"`
	SourceRefID           pgtype.UUID        `json:"source_ref_id"`
	SnpStandard           string             `json:"snp_standard"`
	ProgramID             pgtype.UUID        `json:"program_id"`
	DocumentID            pgtype.UUID        `json:"document_id"`
	PerformanceTargetID   pgtype.UUID        `json:"performance_target_id"`
	EvidenceItemID        pgtype.UUID        `json:"evidence_item_id"`
	OwnerUnitID           pgtype.UUID        `json:"owner_unit_id"`
	ResponsibleEmployeeID pgtype.UUID        `json:"responsible_employee_id"`
	Title                 string             `json:"title"`
	Description           string             `json:"description"`
	Priority              string             `json:"priority"`
	Status                string             `json:"status"`
	DueDate               pgtype.Date        `json:"due_date"`
	CompletedAt           pgtype.Timestamptz `json:"completed_at"`
	FollowUpNotes         string             `json:"follow_up_notes"`
	EvidenceUrl           string             `json:"evidence_url"`
	CreatedByUserID       pgtype.UUID        `json:"created_by_user_id"`
}

func (q *Queries) CreateGovernanceComplianceAction(ctx context.Context, arg CreateGovernanceComplianceActionParams) (GovernanceComplianceAction, error) {
	row := q.db.QueryRow(ctx, createGovernanceComplianceAction,
		arg.PeriodYear,
		arg.SourceType,
		arg.SourceRefID,
		arg.SnpStandard,
		arg.ProgramID,
		arg.DocumentID,
		arg.PerformanceTargetID,
		arg.EvidenceItemID,
		arg.OwnerUnitID,
		arg.ResponsibleEmployeeID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.Status,
		arg.DueDate,
		arg.CompletedAt,
		arg.FollowUpNotes,
		arg.EvidenceUrl,
		arg.CreatedByUserID,
	)
	var i GovernanceComplianceAction
	err := row.Scan(
		&i.ID,
		&i.PeriodYear,
		&i.SourceType,
		&i.SourceRefID,
		&i.SnpStandard,
		&i.ProgramID,
		&i.DocumentID,
		&i.PerformanceTargetID,
		&i.EvidenceItemID,
		&i.OwnerUnitID,
		&i.ResponsibleEmployeeID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.DueDate,
		&i.CompletedAt,
		&i.FollowUpNotes,
		&i.EvidenceUrl,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGovernanceDocument = `-- name: CreateGovernanceDocument :one
INSERT INTO governance_documents (
    doc_type, title, period_year, period_label, owner_unit_id, snp_standard, status,
    document_url, outgoing_letter_id, summary, created_by_user_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, doc_type, title, period_year, period_label, owner_unit_id, snp_standard, status, document_url, outgoing_letter_id, summary, created_by_user_id, created_at, updated_at
`

type CreateGovernanceDocumentParams struct {
	DocType          string      `json:"doc_type"`
	Title            string      `json:"title"`
	PeriodYear       int32       `json:"period_year"`
	PeriodLabel      string      `json:"period_label"`
	OwnerUnitID      pgtype.UUID `json:"owner_unit_id"`
	SnpStandard      string      `json:"snp_standard"`
	Status           string      `json:"status"`
	DocumentUrl      string      `json:"document_url"`
	OutgoingLetterID pgtype.UUID `json:"outgoing_letter_id"`
	Summary          string      `json:"summary"`
	CreatedByUserID  pgtype.UUID `json:"created_by_user_id"`
}

func (q *Queries) CreateGovernanceDocument(ctx context.Context, arg CreateGovernanceDocumentParams) (GovernanceDocument, error) {
	row := q.db.QueryRow(ctx, createGovernanceDocument,
		arg.DocType,
		arg.Title,
		arg.PeriodYear,
		arg.PeriodLabel,
		arg.OwnerUnitID,
		arg.SnpStandard,
		arg.Status,
		arg.DocumentUrl,
		arg.OutgoingLetterID,
		arg.Summary,
		arg.CreatedByUserID,
	)
	var i GovernanceDocument
	err := row.Scan(
		&i.ID,
		&i.DocType,
		&i.Title,
		&i.PeriodYear,
		&i.PeriodLabel,
		&i.OwnerUnitID,
		&i.SnpStandard,
		&i.Status,
		&i.DocumentUrl,
		&i.OutgoingLetterID,
		&i.Summary,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGovernanceEvidenceItem = `-- name: CreateGovernanceEvidenceItem :one
INSERT INTO governance_evidence_items (
    period_year, title, evidence_type, snp_standard, owner_unit_id, document_id,
    program_id, performance_target_id, source_module, evidence_url, status, notes,
    created_by_user_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, period_year, title, evidence_type, snp_standard, owner_unit_id, document_id, program_id, performance_target_id, source_module, evidence_url, status, notes, verified_by_user_id, verified_at, created_by_user_id, created_at, updated_at
`

type CreateGovernanceEvidenceItemParams struct {
	PeriodYear          int32       `json:"period_year"`
	Title               string      `json:"title"`
	EvidenceType        string      `json:"evidence_type"`
	SnpStandard         string      `json:"snp_standard"`
	OwnerUnitID         pgtype.UUID `json:"owner_unit_id"`
	DocumentID          pgtype.UUID `json:"document_id"`
	ProgramID           pgtype.UUID `json:"program_id"`
	PerformanceTargetID pgtype.UUID `json:"performance_target_id"`
	SourceModule        string      `json:"source_module"`
	EvidenceUrl         string      `json:"evidence_url"`
	Status              string      `json:"status"`
	Notes               string      `json:"notes"`
	CreatedByUserID     pgtype.UUID `json:"created_by_user_id"`
}

func (q *Queries) CreateGovernanceEvidenceItem(ctx context.Context, arg CreateGovernanceEvidenceItemParams) (GovernanceEvidenceItem, error) {
	row := q.db.QueryRow(ctx, createGovernanceEvidenceItem,
		arg.PeriodYear,
		arg.Title,
		arg.EvidenceType,
		arg.SnpStandard,
		arg.OwnerUnitID,
		arg.DocumentID,
		arg.ProgramID,
		arg.PerformanceTargetID,
		arg.SourceModule,
		arg.EvidenceUrl,
		arg.Status,
		arg.Notes,
		arg.CreatedByUserID,
	)
	var i GovernanceEvidenceItem
	err := row.Scan(
		&i.ID,
		&i.PeriodYear,
		&i.Title,
		&i.EvidenceType,
		&i.SnpStandard,
		&i.OwnerUnitID,
		&i.DocumentID,
		&i.ProgramID,
		&i.PerformanceTargetID,
		&i.SourceModule,
		&i.EvidenceUrl,
		&i.Status,
		&i.Notes,
		&i.VerifiedByUserID,
		&i.VerifiedAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGovernancePerformanceTarget = `-- name: CreateGovernancePerformanceTarget :one
INSERT INTO governance_performance_targets (
    period_year, employee_id, position_id, program_id, parent_target_id, aspect,
    title, indicator, target_value, target_unit, status, progress_percent,
    evidence_url, review_notes, due_date, created_by_user_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, period_year, employee_id, position_id, program_id, parent_target_id, aspect, title, indicator, target_value, target_unit, status, progress_percent, evidence_url, review_notes, due_date, created_by_user_id, created_at, updated_at
`

type CreateGovernancePerformanceTargetParams struct {
	PeriodYear      int32       `json:"period_year"`
	EmployeeID      pgtype.UUID `json:"employee_id"`
	PositionID      pgtype.UUID `json:"position_id"`
	ProgramID       pgtype.UUID `json:"program_id"`
	ParentTargetID  pgtype.UUID `json:"parent_target_id"`
	Aspect          string      `json:"aspect"`
	Title           string      `json:"title"`
	Indicator       string      `json:"indicator"`
	TargetValue     string      `json:"target_value"`
	TargetUnit      string      `json:"target_unit"`
	Status          string      `json:"status"`
	ProgressPercent int32       `json:"progress_percent"`
	EvidenceUrl     string      `json:"evidence_url"`
	ReviewNotes     string      `json:"review_notes"`
	DueDate         pgtype.Date `json:"due_date"`
	CreatedByUserID pgtype.UUID `json:"created_by_user_id"`
}

func (q *Queries) CreateGovernancePerformanceTarget(ctx context.Context, arg CreateGovernancePerformanceTargetParams) (GovernancePerformanceTarget, error) {
	row := q.db.QueryRow(ctx, createGovernancePerformanceTarget,
		arg.PeriodYear,
		arg.EmployeeID,
		arg.PositionID,
		arg.ProgramID,
		arg.ParentTargetID,
		arg.Aspect,
		arg.Title,
		arg.Indicator,
		arg.TargetValue,
		arg.TargetUnit,
		arg.Status,
		arg.ProgressPercent,
		arg.EvidenceUrl,
		arg.ReviewNotes,
		arg.DueDate,
		arg.CreatedByUserID,
	)
	var i GovernancePerformanceTarget
	err := row.Scan(
		&i.ID,
		&i.PeriodYear,
		&i.EmployeeID,
		&i.PositionID,
		&i.ProgramID,
		&i.ParentTargetID,
		&i.Aspect,
		&i.Title,
		&i.Indicator,
		&i.TargetValue,
		&i.TargetUnit,
		&i.Status,
		&i.ProgressPercent,
		&i.EvidenceUrl,
		&i.ReviewNotes,
		&i.DueDate,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGovernancePosition = `-- name: CreateGovernancePosition :one
INSERT INTO governance_positions (
    unit_id, title, position_type, parent_position_id, description, tupoksi, is_active, sort_order
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, unit_id, title, position_type, parent_position_id, description, tupoksi, is_active, sort_order, created_at, updated_at
`

type CreateGovernancePositionParams struct {
	UnitID           pgtype.UUID `json:"unit_id"`
	Title            string      `json:"title"`
	PositionType     string      `json:"position_type"`
	ParentPositionID pgtype.UUID `json:"parent_position_id"`
	Description      string      `json:"description"`
	Tupoksi          string      `json:"tupoksi"`
	IsActive         bool        `json:"is_active"`
	SortOrder        int32       `json:"sort_order"`
}

func (q *Queries) CreateGovernancePosition(ctx context.Context, arg CreateGovernancePositionParams) (GovernancePosition, error) {
	row := q.db.QueryRow(ctx, createGovernancePosition,
		arg.UnitID,
		arg.Title,
		arg.PositionType,
		arg.ParentPositionID,
		arg.Description,
		arg.Tupoksi,
		arg.IsActive,
		arg.SortOrder,
	)
	var i GovernancePosition
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.Title,
		&i.PositionType,
		&i.ParentPositionID,
		&i.Description,
		&i.Tupoksi,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGovernanceProgram = `-- name: CreateGovernanceProgram :one
INSERT INTO governance_programs (
    period_year, code, name, source_document_id, owner_unit_id, responsible_position_id,
    responsible_employee_id, snp_standard, iku_code, indicator, target_value, target_unit,
    status, progress_percent, realization_summary, evidence_url, due_date
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
RETURNING id, period_year, code, name, source_document_id, owner_unit_id, responsible_position_id, responsible_employee_id, snp_standard, iku_code, indicator, target_value, target_unit, status, progress_percent, realization_summary, evidence_url, due_date, created_at, updated_at
`

type CreateGovernanceProgramParams struct {
	PeriodYear            int32       `json:"period_year"`
	Code                  string      `json:"code"`
	Name                  string      `json:"name"`
	SourceDocumentID      pgtype.UUID `json:"source_document_id"`
	OwnerUnitID           pgtype.UUID `json:"owner_unit_id"`
	ResponsiblePositionID pgtype.UUID `json:"responsible_position_id"`
	ResponsibleEmployeeID pgtype.UUID `json:"responsible_employee_id"`
	SnpStandard           string      `json:"snp_standard"`
	IkuCode               string      `json:"iku_code"`
	Indicator             string      `json:"indicator"`
	TargetValue           string      `json:"target_value"`
	TargetUnit            string      `json:"target_unit"`
	Status                string      `json:"status"`
	ProgressPercent       int32       `json:"progress_percent"`
	RealizationSummary    string      `json:"realization_summary"`
	EvidenceUrl           string      `json:"evidence_url"`
	DueDate               pgtype.Date `json:"due_date"`
}

func (q *Queries) CreateGovernanceProgram(ctx context.Context, arg CreateGovernanceProgramParams) (GovernanceProgram, error) {
	row := q.db.QueryRow(ctx, createGovernanceProgram,
		arg.PeriodYear,
		arg.Code,
		arg.Name,
		arg.SourceDocumentID,
		arg.OwnerUnitID,
		arg.ResponsiblePositionID,
		arg.ResponsibleEmployeeID,
		arg.SnpStandard,
		arg.IkuCode,
		arg.Indicator,
		arg.TargetValue,
		arg.TargetUnit,
		arg.Status,
		arg.ProgressPercent,
		arg.RealizationSummary,
		arg.EvidenceUrl,
		arg.DueDate,
	)
	var i GovernanceProgram
	err := row.Scan(
		&i.ID,
		&i.PeriodYear,
		&i.Code,
		&i.Name,
		&i.SourceDocumentID,
		&i.OwnerUnitID,
		&i.ResponsiblePositionID,
		&i.ResponsibleEmployeeID,
		&i.SnpStandard,
		&i.IkuCode,
		&i.Indicator,
		&i.TargetValue,
		&i.TargetUnit,
		&i.Status,
		&i.ProgressPercent,
		&i.RealizationSummary,
		&i.EvidenceUrl,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGovernanceUnit = `-- name: CreateGovernanceUnit :one
INSERT INTO governance_units (code, name, unit_type, parent_id, description, is_active, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, code, name, unit_type, parent_id, description, is_active, sort_order, created_at, updated_at
`

type CreateGovernanceUnitParams struct {
	Code        string      `json:"code"`
	Name        string      `json:"name"`
	UnitType    string      `json:"unit_type"`
	ParentID    pgtype.UUID `json:"parent_id"`
	Description string      `json:"description"`
	IsActive    bool        `json:"is_active"`
	SortOrder   int32       `json:"sort_order"`
}

func (q *Queries) CreateGovernanceUnit(ctx context.Context, arg CreateGovernanceUnitParams) (GovernanceUnit, error) {
	row := q.db.QueryRow(ctx, createGovernanceUnit,
		arg.Code,
		arg.Name,
		arg.UnitType,
		arg.ParentID,
		arg.Description,
		arg.IsActive,
		arg.SortOrder,
	)
	var i GovernanceUnit
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.UnitType,
		&i.ParentID,
		&i.Description,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGovernanceWorkPlanItem = `-- name: CreateGovernanceWorkPlanItem :one
INSERT INTO governance_work_plan_items (
    period_year, program_id, source_document_id, owner_unit_id, responsible_employee_id,
    evidence_item_id, activity_code, activity_name, output_indicator, target_volume,
    target_unit, budget_source, budget_amount, realization_amount, status,
    progress_percent, start_date, end_date, evidence_url, notes
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19, $20
)
RETURNING id, period_year, program_id, source_document_id, owner_unit_id, responsible_employee_id, evidence_item_id, activity_code, activity_name, output_indicator, target_volume, target_unit, budget_source, budget_amount, realization_amount, status, progress_percent, start_date, end_date, evidence_url, notes, created_at, updated_at
`

type CreateGovernanceWorkPlanItemParams struct {
	PeriodYear            int32       `json:"period_year"`
	ProgramID             pgtype.UUID `json:"program_id"`
	SourceDocumentID      pgtype.UUID `json:"source_document_id"`
	OwnerUnitID           pgtype.UUID `json:"owner_unit_id"`
	ResponsibleEmployeeID pgtype.UUID `json:"responsible_employee_id"`
	EvidenceItemID        pgtype.UUID `json:"evidence_item_id"`
	ActivityCode          string      `json:"activity_code"`
	ActivityName          string      `json:"activity_name"`
	OutputIndicator       string      `json:"output_indicator"`
	TargetVolume          string      `json:"target_volume"`
	TargetUnit            string      `json:"target_unit"`
	BudgetSource          string      `json:"budget_source"`
	BudgetAmount          int64       `json:"budget_amount"`
	RealizationAmount     int64       `json:"realization_amount"`
	Status                string      `json:"status"`
	ProgressPercent       int32       `json:"progress_percent"`
	StartDate             pgtype.Date `json:"start_date"`
	EndDate               pgtype.Date `json:"end_date"`
	EvidenceUrl           string      `json:"evidence_url"`
	Notes                 string      `json:"notes"`
}

func (q *Queries) CreateGovernanceWorkPlanItem(ctx context.Context, arg CreateGovernanceWorkPlanItemParams) (GovernanceWorkPlanItem, error) {
	row := q.db.QueryRow(ctx, createGovernanceWorkPlanItem,
		arg.PeriodYear,
		arg.ProgramID,
		arg.SourceDocumentID,
		arg.OwnerUnitID,
		arg.ResponsibleEmployeeID,
		arg.EvidenceItemID,
		arg.ActivityCode,
		arg.ActivityName,
		arg.OutputIndicator,
		arg.TargetVolume,
		arg.TargetUnit,
		arg.BudgetSource,
		arg.BudgetAmount,
		arg.RealizationAmount,
		arg.Status,
		arg.ProgressPercent,
		arg.StartDate,
		arg.EndDate,
		arg.EvidenceUrl,
		arg.Notes,
	)
	var i GovernanceWorkPlanItem
	err := row.Scan(
		&i.ID,
		&i.PeriodYear,
		&i.ProgramID,
		&i.SourceDocumentID,
		&i.OwnerUnitID,
		&i.ResponsibleEmployeeID,
		&i.EvidenceItemID,
		&i.ActivityCode,
		&i.ActivityName,
		&i.OutputIndicator,
		&i.TargetVolume,
		&i.TargetUnit,
		&i.BudgetSource,
		&i.BudgetAmount,
		&i.RealizationAmount,
		&i.Status,
		&i.ProgressPercent,
		&i.StartDate,
		&i.EndDate,
		&i.EvidenceUrl,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGovernanceAssignment = `-- name: DeleteGovernanceAssignment :exec
DELETE FROM governance_assignments WHERE id = $1
`

func (q *Queries) DeleteGovernanceAssignment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGovernanceAssignment, id)
	return err
}

const deleteGovernanceComplianceAction = `-- name: DeleteGovernanceComplianceAction :exec
DELETE FROM governance_compliance_actions WHERE id = $1
`

func (q *Queries) DeleteGovernanceComplianceAction(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGovernanceComplianceAction, id)
	return err
}

const deleteGovernanceDocument = `-- name: DeleteGovernanceDocument :exec
DELETE FROM governance_documents WHERE id = $1
`

func (q *Queries) DeleteGovernanceDocument(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGovernanceDocument, id)
	return err
}

const deleteGovernanceEvidenceItem = `-- name: DeleteGovernanceEvidenceItem :exec
DELETE FROM governance_evidence_items WHERE id = $1
`

func (q *Queries) DeleteGovernanceEvidenceItem(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGovernanceEvidenceItem, id)
	return err
}

const deleteGovernancePerformanceTarget = `-- name: DeleteGovernancePerformanceTarget :exec
DELETE FROM governance_performance_targets WHERE id = $1
`

func (q *Queries) DeleteGovernancePerformanceTarget(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGovernancePerformanceTarget, id)
	return err
}

const deleteGovernancePosition = `-- name: DeleteGovernancePosition :exec
DELETE FROM governance_positions WHERE id = $1
`

func (q *Queries) DeleteGovernancePosition(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGovernancePosition, id)
	return err
}

const deleteGovernanceProgram = `-- name: DeleteGovernanceProgram :exec
DELETE FROM governance_programs WHERE id = $1
`

func (q *Queries) DeleteGovernanceProgram(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGovernanceProgram, id)
	return err
}

const deleteGovernanceUnit = `-- name: DeleteGovernanceUnit :exec
DELETE FROM governance_units WHERE id = $1
`

func (q *Queries) DeleteGovernanceUnit(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGovernanceUnit, id)
	return err
}

const deleteGovernanceWorkPlanItem = `-- name: DeleteGovernanceWorkPlanItem :exec
DELETE FROM governance_work_plan_items WHERE id = $1
`

func (q *Queries) DeleteGovernanceWorkPlanItem(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGovernanceWorkPlanItem, id)
	return err
}

const getGovernanceStats = `-- name: GetGovernanceStats :one
SELECT
    (SELECT COUNT(*) FROM governance_units WHERE is_active) AS total_units,
    (SELECT COUNT(*) FROM governance_positions WHERE is_active) AS total_positions,
    (SELECT COUNT(*) FROM governance_assignments WHERE end_date IS NULL) AS active_assignments,
    (SELECT COUNT(*) FROM governance_documents WHERE status = 'final') AS final_documents,
    (SELECT COUNT(*) FROM governance_programs WHERE status IN ('planned', 'in_progress')) AS active_programs,
    (SELECT COUNT(*) FROM governance_programs WHERE status = 'blocked') AS blocked_programs,
    (SELECT COUNT(*) FROM governance_programs WHERE status = 'done') AS completed_programs,
    (SELECT COUNT(*) FROM governance_programs WHERE evidence_url <> '') AS programs_with_evidence,
    (SELECT COUNT(*) FROM governance_performance_targets) AS performance_targets,
    (SELECT COUNT(*) FROM governance_performance_targets WHERE status = 'done') AS completed_performance_targets,
    (SELECT COUNT(*) FROM governance_performance_targets WHERE status = 'blocked') AS blocked_performance_targets,
    (SELECT COUNT(*) FROM governance_evidence_items) AS evidence_items,
    (SELECT COUNT(*) FROM governance_evidence_items WHERE status = 'verified') AS verified_evidence_items,
    (SELECT COUNT(*) FROM governance_evidence_items WHERE status = 'gap') AS gap_evidence_items,
    (SELECT COUNT(*) FROM governance_work_plan_items) AS work_plan_items,
    (SELECT COUNT(*) FROM governance_work_plan_items WHERE status = 'done') AS completed_work_plan_items,
    (SELECT COUNT(*) FROM governance_work_plan_items WHERE status = 'blocked') AS blocked_work_plan_items,
    (SELECT COALESCE(SUM(budget_amount), 0)::BIGINT FROM governance_work_plan_items) AS work_plan_budget_amount,
    (SELECT COALESCE(SUM(realization_amount), 0)::BIGINT FROM governance_work_plan_items) AS work_plan_realization_amount,
    (SELECT COUNT(*) FROM governance_compliance_actions) AS compliance_actions,
    (SELECT COUNT(*) FROM governance_compliance_actions WHERE status NOT IN ('done', 'cancelled')) AS open_compliance_actions,
    (SELECT COUNT(*) FROM governance_compliance_actions WHERE status = 'done') AS completed_compliance_actions,
    (SELECT COUNT(*) FROM governance_compliance_actions WHERE priority IN ('high', 'urgent') AND status NOT IN ('done', 'cancelled')) AS critical_compliance_actions
`

type GetGovernanceStatsRow struct {
	TotalUnits                  int64 `json:"total_units"`
	TotalPositions              int64 `json:"total_positions"`
	ActiveAssignments           int64 `json:"active_assignments"`
	FinalDocuments              int64 `json:"final_documents"`
	ActivePrograms              int64 `json:"active_programs"`
	BlockedPrograms             int64 `json:"blocked_programs"`
	CompletedPrograms           int64 `json:"completed_programs"`
	ProgramsWithEvidence        int64 `json:"programs_with_evidence"`
	PerformanceTargets          int64 `json:"performance_targets"`
	CompletedPerformanceTargets int64 `json:"completed_performance_targets"`
	BlockedPerformanceTargets   int64 `json:"blocked_performance_targets"`
	EvidenceItems               int64 `json:"evidence_items"`
	VerifiedEvidenceItems       int64 `json:"verified_evidence_items"`
	GapEvidenceItems            int64 `json:"gap_evidence_items"`
	WorkPlanItems               int64 `json:"work_plan_items"`
	CompletedWorkPlanItems      int64 `json:"completed_work_plan_items"`
	BlockedWorkPlanItems        int64 `json:"blocked_work_plan_items"`
	WorkPlanBudgetAmount        int64 `json:"work_plan_budget_amount"`
	WorkPlanRealizationAmount   int64 `json:"work_plan_realization_amount"`
	ComplianceActions           int64 `json:"compliance_actions"`
	OpenComplianceActions       int64 `json:"open_compliance_actions"`
	CompletedComplianceActions  int64 `json:"completed_compliance_actions"`
	CriticalComplianceActions   int64 `json:"critical_compliance_actions"`
}

func (q *Queries) GetGovernanceStats(ctx context.Context) (GetGovernanceStatsRow, error) {
	row := q.db.QueryRow(ctx, getGovernanceStats)
	var i GetGovernanceStatsRow
	err := row.Scan(
		&i.TotalUnits,
		&i.TotalPositions,
		&i.ActiveAssignments,
		&i.FinalDocuments,
		&i.ActivePrograms,
		&i.BlockedPrograms,
		&i.CompletedPrograms,
		&i.ProgramsWithEvidence,
		&i.PerformanceTargets,
		&i.CompletedPerformanceTargets,
		&i.BlockedPerformanceTargets,
		&i.EvidenceItems,
		&i.VerifiedEvidenceItems,
		&i.GapEvidenceItems,
		&i.WorkPlanItems,
		&i.CompletedWorkPlanItems,
		&i.BlockedWorkPlanItems,
		&i.WorkPlanBudgetAmount,
		&i.WorkPlanRealizationAmount,
		&i.ComplianceActions,
		&i.OpenComplianceActions,
		&i.CompletedComplianceActions,
		&i.CriticalComplianceActions,
	)
	return i, err
}

const listGovernanceAssignments = `-- name: ListGovernanceAssignments :many
SELECT
    ga.id, ga.position_id, ga.employee_id, ga.start_date, ga.end_date,
    ga.decree_outgoing_letter_id, ga.notes, ga.created_at, ga.updated_at,
    p.title AS position_title,
    u.name AS unit_name,
    e.nama AS employee_name,
    COALESCE(e.nip, '')::text AS employee_nip,
    ol.nomor_surat AS decree_nomor_surat
FROM governance_assignments ga
JOIN governance_positions p ON p.id = ga.position_id
JOIN governance_units u ON u.id = p.unit_id
JOIN employees e ON e.id = ga.employee_id
LEFT JOIN outgoing_letters ol ON ol.id = ga.decree_outgoing_letter_id
WHERE (
    $1::BOOLEAN = FALSE OR ga.end_date IS NULL
) AND (
    $2::TEXT = '' OR
    p.title ILIKE '%' || $2 || '%' OR
    u.name ILIKE '%' || $2 || '%' OR
    e.nama ILIKE '%' || $2 || '%' OR
    COALESCE(e.nip, '') ILIKE '%' || $2 || '%'
)
ORDER BY ga.end_date NULLS FIRST, ga.start_date DESC, u.sort_order, p.sort_order
`

type ListGovernanceAssignmentsParams struct {
	ActiveOnly bool   `json:"active_only"`
	Search     string `json:"search"`
}

type ListGovernanceAssignmentsRow struct {
	ID                     pgtype.UUID        `json:"id"`
	PositionID             pgtype.UUID        `json:"position_id"`
	EmployeeID             pgtype.UUID        `json:"employee_id"`
	StartDate              pgtype.Date        `json:"start_date"`
	EndDate                pgtype.Date        `json:"end_date"`
	DecreeOutgoingLetterID pgtype.UUID        `json:"decree_outgoing_letter_id"`
	Notes                  string             `json:"notes"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	PositionTitle          string             `json:"position_title"`
	UnitName               string             `json:"unit_name"`
	EmployeeName           string             `json:"employee_name"`
	EmployeeNip            string             `json:"employee_nip"`
	DecreeNomorSurat       pgtype.Text        `json:"decree_nomor_surat"`
}

func (q *Queries) ListGovernanceAssignments(ctx context.Context, arg ListGovernanceAssignmentsParams) ([]ListGovernanceAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, listGovernanceAssignments, arg.ActiveOnly, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGovernanceAssignmentsRow{}
	for rows.Next() {
		var i ListGovernanceAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.PositionID,
			&i.EmployeeID,
			&i.StartDate,
			&i.EndDate,
			&i.DecreeOutgoingLetterID,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PositionTitle,
			&i.UnitName,
			&i.EmployeeName,
			&i.EmployeeNip,
			&i.DecreeNomorSurat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGovernanceComplianceActions = `-- name: ListGovernanceComplianceActions :many
SELECT
    gca.id,
    gca.period_year,
    gca.source_type,
    gca.source_ref_id,
    gca.snp_standard,
    gca.program_id,
    gca.document_id,
    gca.performance_target_id,
    gca.evidence_item_id,
    gca.owner_unit_id,
    gca.responsible_employee_id,
    gca.title,
    gca.description,
    gca.priority,
    gca.status,
    gca.due_date,
    gca.completed_at,
    gca.follow_up_notes,
    gca.evidence_url,
    gca.created_by_user_id,
    gca.created_at,
    gca.updated_at,
    gp.code AS program_code,
    gp.name AS program_name,
    gd.title AS document_title,
    gpt.title AS performance_target_title,
    gei.title AS evidence_item_title,
    u.name AS owner_unit_name,
    e.nama AS responsible_employee_name,
    COALESCE(e.nip, '')::text AS responsible_employee_nip
FROM governance_compliance_actions gca
LEFT JOIN governance_programs gp ON gp.id = gca.program_id
LEFT JOIN governance_documents gd ON gd.id = gca.document_id
LEFT JOIN governance_performance_targets gpt ON gpt.id = gca.performance_target_id
LEFT JOIN governance_evidence_items gei ON gei.id = gca.evidence_item_id
LEFT JOIN governance_units u ON u.id = gca.owner_unit_id
LEFT JOIN employees e ON e.id = gca.responsible_employee_id
WHERE (
    $1::TEXT = '' OR
    gca.title ILIKE '%' || $1 || '%' OR
    gca.description ILIKE '%' || $1 || '%' OR
    gca.follow_up_notes ILIKE '%' || $1 || '%' OR
    gp.code ILIKE '%' || $1 || '%' OR
    gp.name ILIKE '%' || $1 || '%' OR
    gd.title ILIKE '%' || $1 || '%' OR
    gpt.title ILIKE '%' || $1 || '%' OR
    gei.title ILIKE '%' || $1 || '%' OR
    u.name ILIKE '%' || $1 || '%' OR
    e.nama ILIKE '%' || $1 || '%'
) AND (
    $2::INT = 0 OR gca.period_year = $2
) AND (
    $3::TEXT = '' OR gca.status = $3
) AND (
    $4::TEXT = '' OR gca.priority = $4
) AND (
    $5::TEXT = '' OR gca.source_type = $5
) AND (
    $6::TEXT = '' OR gca.snp_standard = $6
) AND (
    $7::UUID IS NULL OR gca.responsible_employee_id = $7::UUID
)
ORDER BY
    gca.period_year DESC,
    CASE gca.status
        WHEN 'open' THEN 1
        WHEN 'in_progress' THEN 2
        WHEN 'waiting_evidence' THEN 3
        WHEN 'done' THEN 4
        ELSE 5
    END,
    CASE gca.priority
        WHEN 'urgent' THEN 1
        WHEN 'high' THEN 2
        WHEN 'medium' THEN 3
        ELSE 4
    END,
    gca.due_date NULLS LAST,
    gca.updated_at DESC
`

type ListGovernanceComplianceActionsParams struct {
	Search                string      `json:"search"`
	PeriodYear            int32       `json:"period_year"`
	Status                string      `json:"status"`
	Priority              string      `json:"priority"`
	SourceType            string      `json:"source_type"`
	SnpStandard           string      `json:"snp_standard"`
	ResponsibleEmployeeID pgtype.UUID `json:"responsible_employee_id"`
}

type ListGovernanceComplianceActionsRow struct {
	ID                      pgtype.UUID        `json:"id"`
	PeriodYear              int32              `json:"period_year"`
	SourceType              string             `json:"source_type"`
	SourceRefID             pgtype.UUID        `json:"source_ref_id"`
	SnpStandard             string             `json:"snp_standard"`
	ProgramID               pgtype.UUID        `json:"program_id"`
	DocumentID              pgtype.UUID        `json:"document_id"`
	PerformanceTargetID     pgtype.UUID        `json:"performance_target_id"`
	EvidenceItemID          pgtype.UUID        `json:"evidence_item_id"`
	OwnerUnitID             pgtype.UUID        `json:"owner_unit_id"`
	ResponsibleEmployeeID   pgtype.UUID        `json:"responsible_employee_id"`
	Title                   string             `json:"title"`
	Description             string             `json:"description"`
	Priority                string             `json:"priority"`
	Status                  string             `json:"status"`
	DueDate                 pgtype.Date        `json:"due_date"`
	CompletedAt             pgtype.Timestamptz `json:"completed_at"`
	FollowUpNotes           string             `json:"follow_up_notes"`
	EvidenceUrl             string             `json:"evidence_url"`
	CreatedByUserID         pgtype.UUID        `json:"created_by_user_id"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	ProgramCode             pgtype.Text        `json:"program_code"`
	ProgramName             pgtype.Text        `json:"program_name"`
	DocumentTitle           pgtype.Text        `json:"document_title"`
	PerformanceTargetTitle  pgtype.Text        `json:"performance_target_title"`
	EvidenceItemTitle       pgtype.Text        `json:"evidence_item_title"`
	OwnerUnitName           pgtype.Text        `json:"owner_unit_name"`
	ResponsibleEmployeeName pgtype.Text        `json:"responsible_employee_name"`
	ResponsibleEmployeeNip  string             `json:"responsible_employee_nip"`
}

func (q *Queries) ListGovernanceComplianceActions(ctx context.Context, arg ListGovernanceComplianceActionsParams) ([]ListGovernanceComplianceActionsRow, error) {
	rows, err := q.db.Query(ctx, listGovernanceComplianceActions,
		arg.Search,
		arg.PeriodYear,
		arg.Status,
		arg.Priority,
		arg.SourceType,
		arg.SnpStandard,
		arg.ResponsibleEmployeeID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGovernanceComplianceActionsRow{}
	for rows.Next() {
		var i ListGovernanceComplianceActionsRow
		if err := rows.Scan(
			&i.ID,
			&i.PeriodYear,
			&i.SourceType,
			&i.SourceRefID,
			&i.SnpStandard,
			&i.ProgramID,
			&i.DocumentID,
			&i.PerformanceTargetID,
			&i.EvidenceItemID,
			&i.OwnerUnitID,
			&i.ResponsibleEmployeeID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.Status,
			&i.DueDate,
			&i.CompletedAt,
			&i.FollowUpNotes,
			&i.EvidenceUrl,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProgramCode,
			&i.ProgramName,
			&i.DocumentTitle,
			&i.PerformanceTargetTitle,
			&i.EvidenceItemTitle,
			&i.OwnerUnitName,
			&i.ResponsibleEmployeeName,
			&i.ResponsibleEmployeeNip,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGovernanceDocuments = `-- name: ListGovernanceDocuments :many
SELECT
    gd.id, gd.doc_type, gd.title, gd.period_year, gd.period_label, gd.owner_unit_id,
    gd.snp_standard, gd.status, gd.document_url, gd.outgoing_letter_id, gd.summary,
    gd.created_by_user_id, gd.created_at, gd.updated_at,
    u.name AS owner_unit_name,
    ol.nomor_surat AS outgoing_nomor_surat
FROM governance_documents gd
LEFT JOIN governance_units u ON u.id = gd.owner_unit_id
LEFT JOIN outgoing_letters ol ON ol.id = gd.outgoing_letter_id
WHERE (
    $1::TEXT = '' OR
    gd.title ILIKE '%' || $1 || '%' OR
    gd.doc_type ILIKE '%' || $1 || '%' OR
    gd.summary ILIKE '%' || $1 || '%'
) AND (
    $2::TEXT = '' OR gd.doc_type = $2
) AND (
    $3::INT = 0 OR gd.period_year = $3
) AND (
    $4::TEXT = '' OR gd.snp_standard = $4
)
ORDER BY gd.period_year DESC, gd.doc_type, gd.updated_at DESC
`

type ListGovernanceDocumentsParams struct {
	Search      string `json:"search"`
	DocType     string `json:"doc_type"`
	PeriodYear  int32  `json:"period_year"`
	SnpStandard string `json:"snp_standard"`
}

type ListGovernanceDocumentsRow struct {
	ID                 pgtype.UUID        `json:"id"`
	DocType            string             `json:"doc_type"`
	Title              string             `json:"title"`
	PeriodYear         int32              `json:"period_year"`
	PeriodLabel        string             `json:"period_label"`
	OwnerUnitID        pgtype.UUID        `json:"owner_unit_id"`
	SnpStandard        string             `json:"snp_standard"`
	Status             string             `json:"status"`
	DocumentUrl        string             `json:"document_url"`
	OutgoingLetterID   pgtype.UUID        `json:"outgoing_letter_id"`
	Summary            string             `json:"summary"`
	CreatedByUserID    pgtype.UUID        `json:"created_by_user_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	OwnerUnitName      pgtype.Text        `json:"owner_unit_name"`
	OutgoingNomorSurat pgtype.Text        `json:"outgoing_nomor_surat"`
}

func (q *Queries) ListGovernanceDocuments(ctx context.Context, arg ListGovernanceDocumentsParams) ([]ListGovernanceDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listGovernanceDocuments,
		arg.Search,
		arg.DocType,
		arg.PeriodYear,
		arg.SnpStandard,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGovernanceDocumentsRow{}
	for rows.Next() {
		var i ListGovernanceDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.DocType,
			&i.Title,
			&i.PeriodYear,
			&i.PeriodLabel,
			&i.OwnerUnitID,
			&i.SnpStandard,
			&i.Status,
			&i.DocumentUrl,
			&i.OutgoingLetterID,
			&i.Summary,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerUnitName,
			&i.OutgoingNomorSurat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGovernanceEmployeeOptions = `-- name: ListGovernanceEmployeeOptions :many
SELECT id, COALESCE(nip, '')::text AS nip, nama, unit_kerja
FROM employees
WHERE is_active = TRUE
ORDER BY nama ASC
`

type ListGovernanceEmployeeOptionsRow struct {
	ID        pgtype.UUID `json:"id"`
	Nip       string      `json:"nip"`
	Nama      string      `json:"nama"`
	UnitKerja string      `json:"unit_kerja"`
}

func (q *Queries) ListGovernanceEmployeeOptions(ctx context.Context) ([]ListGovernanceEmployeeOptionsRow, error) {
	rows, err := q.db.Query(ctx, listGovernanceEmployeeOptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGovernanceEmployeeOptionsRow{}
	for rows.Next() {
		var i ListGovernanceEmployeeOptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Nip,
			&i.Nama,
			&i.UnitKerja,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGovernanceEvidenceItems = `-- name: ListGovernanceEvidenceItems :many
SELECT
    gei.id, gei.period_year, gei.title, gei.evidence_type, gei.snp_standard,
    gei.owner_unit_id, gei.document_id, gei.program_id, gei.performance_target_id,
    gei.source_module, gei.evidence_url, gei.status, gei.notes, gei.verified_by_user_id,
    gei.verified_at, gei.created_by_user_id, gei.created_at, gei.updated_at,
    u.name AS owner_unit_name,
    gd.title AS document_title,
    gp.code AS program_code,
    gp.name AS program_name,
    gpt.title AS performance_target_title
FROM governance_evidence_items gei
LEFT JOIN governance_units u ON u.id = gei.owner_unit_id
LEFT JOIN governance_documents gd ON gd.id = gei.document_id
LEFT JOIN governance_programs gp ON gp.id = gei.program_id
LEFT JOIN governance_performance_targets gpt ON gpt.id = gei.performance_target_id
WHERE (
    $1::TEXT = '' OR
    gei.title ILIKE '%' || $1 || '%' OR
    gei.evidence_type ILIKE '%' || $1 || '%' OR
    gei.source_module ILIKE '%' || $1 || '%' OR
    gei.notes ILIKE '%' || $1 || '%' OR
    u.name ILIKE '%' || $1 || '%' OR
    gd.title ILIKE '%' || $1 || '%' OR
    gp.code ILIKE '%' || $1 || '%' OR
    gp.name ILIKE '%' || $1 || '%' OR
    gpt.title ILIKE '%' || $1 || '%'
) AND (
    $2::INT = 0 OR gei.period_year = $2
) AND (
    $3::TEXT = '' OR gei.status = $3
) AND (
    $4::TEXT = '' OR gei.snp_standard = $4
)
ORDER BY gei.period_year DESC, gei.status, gei.updated_at DESC
`

type ListGovernanceEvidenceItemsParams struct {
	Search      string `json:"search"`
	PeriodYear  int32  `json:"period_year"`
	Status      string `json:"status"`
	SnpStandard string `json:"snp_standard"`
}

type ListGovernanceEvidenceItemsRow struct {
	ID                     pgtype.UUID        `json:"id"`
	PeriodYear             int32              `json:"period_year"`
	Title                  string             `json:"title"`
	EvidenceType           string             `json:"evidence_type"`
	SnpStandard            string             `json:"snp_standard"`
	OwnerUnitID            pgtype.UUID        `json:"owner_unit_id"`
	DocumentID             pgtype.UUID        `json:"document_id"`
	ProgramID              pgtype.UUID        `json:"program_id"`
	PerformanceTargetID    pgtype.UUID        `json:"performance_target_id"`
	SourceModule           string             `json:"source_module"`
	EvidenceUrl            string             `json:"evidence_url"`
	Status                 string             `json:"status"`
	Notes                  string             `json:"notes"`
	VerifiedByUserID       pgtype.UUID        `json:"verified_by_user_id"`
	VerifiedAt             pgtype.Timestamptz `json:"verified_at"`
	CreatedByUserID        pgtype.UUID        `json:"created_by_user_id"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	OwnerUnitName          pgtype.Text        `json:"owner_unit_name"`
	DocumentTitle          pgtype.Text        `json:"document_title"`
	ProgramCode            pgtype.Text        `json:"program_code"`
	ProgramName            pgtype.Text        `json:"program_name"`
	PerformanceTargetTitle pgtype.Text        `json:"performance_target_title"`
}

func (q *Queries) ListGovernanceEvidenceItems(ctx context.Context, arg ListGovernanceEvidenceItemsParams) ([]ListGovernanceEvidenceItemsRow, error) {
	rows, err := q.db.Query(ctx, listGovernanceEvidenceItems,
		arg.Search,
		arg.PeriodYear,
		arg.Status,
		arg.SnpStandard,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGovernanceEvidenceItemsRow{}
	for rows.Next() {
		var i ListGovernanceEvidenceItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.PeriodYear,
			&i.Title,
			&i.EvidenceType,
			&i.SnpStandard,
			&i.OwnerUnitID,
			&i.DocumentID,
			&i.ProgramID,
			&i.PerformanceTargetID,
			&i.SourceModule,
			&i.EvidenceUrl,
			&i.Status,
			&i.Notes,
			&i.VerifiedByUserID,
			&i.VerifiedAt,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerUnitName,
			&i.DocumentTitle,
			&i.ProgramCode,
			&i.ProgramName,
			&i.PerformanceTargetTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGovernancePerformanceTargets = `-- name: ListGovernancePerformanceTargets :many
SELECT
    gpt.id, gpt.period_year, gpt.employee_id, gpt.position_id, gpt.program_id,
    gpt.parent_target_id, gpt.aspect, gpt.title, gpt.indicator, gpt.target_value,
    gpt.target_unit, gpt.status, gpt.progress_percent, gpt.evidence_url,
    gpt.review_notes, gpt.due_date, gpt.created_by_user_id, gpt.created_at, gpt.updated_at,
    e.nama AS employee_name,
    COALESCE(e.nip, '')::text AS employee_nip,
    p.title AS position_title,
    gp.code AS program_code,
    gp.name AS program_name,
    parent.title AS parent_target_title
FROM governance_performance_targets gpt
JOIN employees e ON e.id = gpt.employee_id
LEFT JOIN governance_positions p ON p.id = gpt.position_id
LEFT JOIN governance_programs gp ON gp.id = gpt.program_id
LEFT JOIN governance_performance_targets parent ON parent.id = gpt.parent_target_id
WHERE (
    $1::TEXT = '' OR
    gpt.title ILIKE '%' || $1 || '%' OR
    gpt.indicator ILIKE '%' || $1 || '%' OR
    e.nama ILIKE '%' || $1 || '%' OR
    COALESCE(e.nip, '') ILIKE '%' || $1 || '%' OR
    gp.code ILIKE '%' || $1 || '%' OR
    gp.name ILIKE '%' || $1 || '%'
) AND (
    $2::INT = 0 OR gpt.period_year = $2
) AND (
    $3::TEXT = '' OR gpt.status = $3
) AND (
    $4::UUID IS NULL OR gpt.employee_id = $4::UUID
)
ORDER BY gpt.period_year DESC, e.nama ASC, gpt.created_at DESC
`

type ListGovernancePerformanceTargetsParams struct {
	Search     string      `json:"search"`
	PeriodYear int32       `json:"period_year"`
	Status     string      `json:"status"`
	EmployeeID pgtype.UUID `json:"employee_id"`
}

type ListGovernancePerformanceTargetsRow struct {
	ID                pgtype.UUID        `json:"id"`
	PeriodYear        int32              `json:"period_year"`
	EmployeeID        pgtype.UUID        `json:"employee_id"`
	PositionID        pgtype.UUID        `json:"position_id"`
	ProgramID         pgtype.UUID        `json:"program_id"`
	ParentTargetID    pgtype.UUID        `json:"parent_target_id"`
	Aspect            string             `json:"aspect"`
	Title             string             `json:"title"`
	Indicator         string             `json:"indicator"`
	TargetValue       string             `json:"target_value"`
	TargetUnit        string             `json:"target_unit"`
	Status            string             `json:"status"`
	ProgressPercent   int32              `json:"progress_percent"`
	EvidenceUrl       string             `json:"evidence_url"`
	ReviewNotes       string             `json:"review_notes"`
	DueDate           pgtype.Date        `json:"due_date"`
	CreatedByUserID   pgtype.UUID        `json:"created_by_user_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	EmployeeName      string             `json:"employee_name"`
	EmployeeNip       string             `json:"employee_nip"`
	PositionTitle     pgtype.Text        `json:"position_title"`
	ProgramCode       pgtype.Text        `json:"program_code"`
	ProgramName       pgtype.Text        `json:"program_name"`
	ParentTargetTitle pgtype.Text        `json:"parent_target_title"`
}

func (q *Queries) ListGovernancePerformanceTargets(ctx context.Context, arg ListGovernancePerformanceTargetsParams) ([]ListGovernancePerformanceTargetsRow, error) {
	rows, err := q.db.Query(ctx, listGovernancePerformanceTargets,
		arg.Search,
		arg.PeriodYear,
		arg.Status,
		arg.EmployeeID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGovernancePerformanceTargetsRow{}
	for rows.Next() {
		var i ListGovernancePerformanceTargetsRow
		if err := rows.Scan(
			&i.ID,
			&i.PeriodYear,
			&i.EmployeeID,
			&i.PositionID,
			&i.ProgramID,
			&i.ParentTargetID,
			&i.Aspect,
			&i.Title,
			&i.Indicator,
			&i.TargetValue,
			&i.TargetUnit,
			&i.Status,
			&i.ProgressPercent,
			&i.EvidenceUrl,
			&i.ReviewNotes,
			&i.DueDate,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmployeeName,
			&i.EmployeeNip,
			&i.PositionTitle,
			&i.ProgramCode,
			&i.ProgramName,
			&i.ParentTargetTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGovernancePositions = `-- name: ListGovernancePositions :many
SELECT
    p.id, p.unit_id, p.title, p.position_type, p.parent_position_id, p.description,
    p.tupoksi, p.is_active, p.sort_order, p.created_at, p.updated_at,
    u.name AS unit_name,
    pp.title AS parent_position_title,
    ae.nama AS active_employee_name,
    COALESCE(ae.nip, '')::text AS active_employee_nip
FROM governance_positions p
JOIN governance_units u ON u.id = p.unit_id
LEFT JOIN governance_positions pp ON pp.id = p.parent_position_id
LEFT JOIN governance_assignments ga ON ga.position_id = p.id AND ga.end_date IS NULL
LEFT JOIN employees ae ON ae.id = ga.employee_id
WHERE (
    $1::TEXT = '' OR
    p.title ILIKE '%' || $1 || '%' OR
    u.name ILIKE '%' || $1 || '%' OR
    p.position_type ILIKE '%' || $1 || '%'
)
ORDER BY u.sort_order, p.sort_order, p.title
`

type ListGovernancePositionsRow struct {
	ID                  pgtype.UUID        `json:"id"`
	UnitID              pgtype.UUID        `json:"unit_id"`
	Title               string             `json:"title"`
	PositionType        string             `json:"position_type"`
	ParentPositionID    pgtype.UUID        `json:"parent_position_id"`
	Description         string             `json:"description"`
	Tupoksi             string             `json:"tupoksi"`
	IsActive            bool               `json:"is_active"`
	SortOrder           int32              `json:"sort_order"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	UnitName            string             `json:"unit_name"`
	ParentPositionTitle pgtype.Text        `json:"parent_position_title"`
	ActiveEmployeeName  pgtype.Text        `json:"active_employee_name"`
	ActiveEmployeeNip   string             `json:"active_employee_nip"`
}

func (q *Queries) ListGovernancePositions(ctx context.Context, search string) ([]ListGovernancePositionsRow, error) {
	rows, err := q.db.Query(ctx, listGovernancePositions, search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGovernancePositionsRow{}
	for rows.Next() {
		var i ListGovernancePositionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UnitID,
			&i.Title,
			&i.PositionType,
			&i.ParentPositionID,
			&i.Description,
			&i.Tupoksi,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UnitName,
			&i.ParentPositionTitle,
			&i.ActiveEmployeeName,
			&i.ActiveEmployeeNip,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGovernancePrograms = `-- name: ListGovernancePrograms :many
SELECT
    gp.id, gp.period_year, gp.code, gp.name, gp.source_document_id, gp.owner_unit_id,
    gp.responsible_position_id, gp.responsible_employee_id, gp.snp_standard, gp.iku_code,
    gp.indicator, gp.target_value, gp.target_unit, gp.status, gp.progress_percent,
    gp.realization_summary, gp.evidence_url, gp.due_date, gp.created_at, gp.updated_at,
    gd.title AS source_document_title,
    u.name AS owner_unit_name,
    p.title AS responsible_position_title,
    e.nama AS responsible_employee_name
FROM governance_programs gp
LEFT JOIN governance_documents gd ON gd.id = gp.source_document_id
LEFT JOIN governance_units u ON u.id = gp.owner_unit_id
LEFT JOIN governance_positions p ON p.id = gp.responsible_position_id
LEFT JOIN employees e ON e.id = gp.responsible_employee_id
WHERE (
    $1::TEXT = '' OR
    gp.code ILIKE '%' || $1 || '%' OR
    gp.name ILIKE '%' || $1 || '%' OR
    gp.indicator ILIKE '%' || $1 || '%' OR
    gp.iku_code ILIKE '%' || $1 || '%'
) AND (
    $2::INT = 0 OR gp.period_year = $2
) AND (
    $3::TEXT = '' OR gp.status = $3
) AND (
    $4::TEXT = '' OR gp.snp_standard = $4
)
ORDER BY gp.period_year DESC, gp.code
`

type ListGovernanceProgramsParams struct {
	Search      string `json:"search"`
	PeriodYear  int32  `json:"period_year"`
	Status      string `json:"status"`
	SnpStandard string `json:"snp_standard"`
}

type ListGovernanceProgramsRow struct {
	ID                       pgtype.UUID        `json:"id"`
	PeriodYear               int32              `json:"period_year"`
	Code                     string             `json:"code"`
	Name                     string             `json:"name"`
	SourceDocumentID         pgtype.UUID        `json:"source_document_id"`
	OwnerUnitID              pgtype.UUID        `json:"owner_unit_id"`
	ResponsiblePositionID    pgtype.UUID        `json:"responsible_position_id"`
	ResponsibleEmployeeID    pgtype.UUID        `json:"responsible_employee_id"`
	SnpStandard              string             `json:"snp_standard"`
	IkuCode                  string             `json:"iku_code"`
	Indicator                string             `json:"indicator"`
	TargetValue              string             `json:"target_value"`
	TargetUnit               string             `json:"target_unit"`
	Status                   string             `json:"status"`
	ProgressPercent          int32              `json:"progress_percent"`
	RealizationSummary       string             `json:"realization_summary"`
	EvidenceUrl              string             `json:"evidence_url"`
	DueDate                  pgtype.Date        `json:"due_date"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	SourceDocumentTitle      pgtype.Text        `json:"source_document_title"`
	OwnerUnitName            pgtype.Text        `json:"owner_unit_name"`
	ResponsiblePositionTitle pgtype.Text        `json:"responsible_position_title"`
	ResponsibleEmployeeName  pgtype.Text        `json:"responsible_employee_name"`
}

func (q *Queries) ListGovernancePrograms(ctx context.Context, arg ListGovernanceProgramsParams) ([]ListGovernanceProgramsRow, error) {
	rows, err := q.db.Query(ctx, listGovernancePrograms,
		arg.Search,
		arg.PeriodYear,
		arg.Status,
		arg.SnpStandard,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGovernanceProgramsRow{}
	for rows.Next() {
		var i ListGovernanceProgramsRow
		if err := rows.Scan(
			&i.ID,
			&i.PeriodYear,
			&i.Code,
			&i.Name,
			&i.SourceDocumentID,
			&i.OwnerUnitID,
			&i.ResponsiblePositionID,
			&i.ResponsibleEmployeeID,
			&i.SnpStandard,
			&i.IkuCode,
			&i.Indicator,
			&i.TargetValue,
			&i.TargetUnit,
			&i.Status,
			&i.ProgressPercent,
			&i.RealizationSummary,
			&i.EvidenceUrl,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceDocumentTitle,
			&i.OwnerUnitName,
			&i.ResponsiblePositionTitle,
			&i.ResponsibleEmployeeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGovernanceSNPMatrix = `-- name: ListGovernanceSNPMatrix :many
WITH standards AS (
    SELECT 'skl'::TEXT AS code, 'Standar Kompetensi Lulusan'::TEXT AS name
    UNION ALL SELECT 'isi', 'Standar Isi'
    UNION ALL SELECT 'proses', 'Standar Proses'
    UNION ALL SELECT 'penilaian', 'Standar Penilaian'
    UNION ALL SELECT 'ptk', 'Standar Pendidik dan Tenaga Kependidikan'
    UNION ALL SELECT 'sarpras', 'Standar Sarana dan Prasarana'
    UNION ALL SELECT 'pengelolaan', 'Standar Pengelolaan'
    UNION ALL SELECT 'pembiayaan', 'Standar Pembiayaan'
),
doc_counts AS (
    SELECT snp_standard, COUNT(*) AS total_documents
    FROM governance_documents
    WHERE snp_standard <> ''
    GROUP BY snp_standard
),
program_counts AS (
    SELECT
        snp_standard,
        COUNT(*) AS total_programs,
        COUNT(*) FILTER (WHERE status = 'done') AS completed_programs,
        COUNT(*) FILTER (WHERE evidence_url <> '') AS evidence_programs
    FROM governance_programs
    WHERE snp_standard <> ''
    GROUP BY snp_standard
),
evidence_counts AS (
    SELECT
        snp_standard,
        COUNT(*) AS total_evidence_items,
        COUNT(*) FILTER (WHERE status = 'verified') AS verified_evidence_items,
        COUNT(*) FILTER (WHERE status = 'gap') AS gap_evidence_items
    FROM governance_evidence_items
    WHERE snp_standard <> ''
    GROUP BY snp_standard
),
last_updates AS (
    SELECT snp_standard, MAX(updated_at) AS last_updated_at
    FROM (
        SELECT snp_standard, updated_at FROM governance_documents WHERE snp_standard <> ''
        UNION ALL
        SELECT snp_standard, updated_at FROM governance_programs WHERE snp_standard <> ''
        UNION ALL
        SELECT snp_standard, updated_at FROM governance_evidence_items WHERE snp_standard <> ''
    ) items
    GROUP BY snp_standard
)
SELECT
    s.code,
    s.name,
    COALESCE(dc.total_documents, 0)::BIGINT AS total_documents,
    COALESCE(pc.total_programs, 0)::BIGINT AS total_programs,
    COALESCE(pc.completed_programs, 0)::BIGINT AS completed_programs,
    COALESCE(pc.evidence_programs, 0)::BIGINT AS evidence_programs,
    COALESCE(ec.total_evidence_items, 0)::BIGINT AS total_evidence_items,
    COALESCE(ec.verified_evidence_items, 0)::BIGINT AS verified_evidence_items,
    COALESCE(ec.gap_evidence_items, 0)::BIGINT AS gap_evidence_items,
    lu.last_updated_at::TIMESTAMPTZ AS last_updated_at
FROM standards s
LEFT JOIN doc_counts dc ON dc.snp_standard = s.code
LEFT JOIN program_counts pc ON pc.snp_standard = s.code
LEFT JOIN evidence_counts ec ON ec.snp_standard = s.code
LEFT JOIN last_updates lu ON lu.snp_standard = s.code
ORDER BY CASE s.code
    WHEN 'skl' THEN 1
    WHEN 'isi' THEN 2
    WHEN 'proses' THEN 3
    WHEN 'penilaian' THEN 4
    WHEN 'ptk' THEN 5
    WHEN 'sarpras' THEN 6
    WHEN 'pengelolaan' THEN 7
    WHEN 'pembiayaan' THEN 8
    ELSE 99
END
`

type ListGovernanceSNPMatrixRow struct {
	Code                  string             `json:"code"`
	Name                  string             `json:"name"`
	TotalDocuments        int64              `json:"total_documents"`
	TotalPrograms         int64              `json:"total_programs"`
	CompletedPrograms     int64              `json:"completed_programs"`
	EvidencePrograms      int64              `json:"evidence_programs"`
	TotalEvidenceItems    int64              `json:"total_evidence_items"`
	VerifiedEvidenceItems int64              `json:"verified_evidence_items"`
	GapEvidenceItems      int64              `json:"gap_evidence_items"`
	LastUpdatedAt         pgtype.Timestamptz `json:"last_updated_at"`
}

func (q *Queries) ListGovernanceSNPMatrix(ctx context.Context) ([]ListGovernanceSNPMatrixRow, error) {
	rows, err := q.db.Query(ctx, listGovernanceSNPMatrix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGovernanceSNPMatrixRow{}
	for rows.Next() {
		var i ListGovernanceSNPMatrixRow
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.TotalDocuments,
			&i.TotalPrograms,
			&i.CompletedPrograms,
			&i.EvidencePrograms,
			&i.TotalEvidenceItems,
			&i.VerifiedEvidenceItems,
			&i.GapEvidenceItems,
			&i.LastUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGovernanceUnits = `-- name: ListGovernanceUnits :many
SELECT
    u.id, u.code, u.name, u.unit_type, u.parent_id, u.description, u.is_active,
    u.sort_order, u.created_at, u.updated_at,
    pu.name AS parent_unit_name
FROM governance_units u
LEFT JOIN governance_units pu ON pu.id = u.parent_id
WHERE (
    $1::TEXT = '' OR
    u.code ILIKE '%' || $1 || '%' OR
    u.name ILIKE '%' || $1 || '%' OR
    u.unit_type ILIKE '%' || $1 || '%'
)
ORDER BY COALESCE(pu.sort_order, -1), u.sort_order, u.name
`

type ListGovernanceUnitsRow struct {
	ID             pgtype.UUID        `json:"id"`
	Code           string             `json:"code"`
	Name           string             `json:"name"`
	UnitType       string             `json:"unit_type"`
	ParentID       pgtype.UUID        `json:"parent_id"`
	Description    string             `json:"description"`
	IsActive       bool               `json:"is_active"`
	SortOrder      int32              `json:"sort_order"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ParentUnitName pgtype.Text        `json:"parent_unit_name"`
}

func (q *Queries) ListGovernanceUnits(ctx context.Context, search string) ([]ListGovernanceUnitsRow, error) {
	rows, err := q.db.Query(ctx, listGovernanceUnits, search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGovernanceUnitsRow{}
	for rows.Next() {
		var i ListGovernanceUnitsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.UnitType,
			&i.ParentID,
			&i.Description,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentUnitName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGovernanceWorkPlanItems = `-- name: ListGovernanceWorkPlanItems :many
SELECT
    gwpi.id,
    gwpi.period_year,
    gwpi.program_id,
    gwpi.source_document_id,
    gwpi.owner_unit_id,
    gwpi.responsible_employee_id,
    gwpi.evidence_item_id,
    gwpi.activity_code,
    gwpi.activity_name,
    gwpi.output_indicator,
    gwpi.target_volume,
    gwpi.target_unit,
    gwpi.budget_source,
    gwpi.budget_amount,
    gwpi.realization_amount,
    gwpi.status,
    gwpi.progress_percent,
    gwpi.start_date,
    gwpi.end_date,
    gwpi.evidence_url,
    gwpi.notes,
    gwpi.created_at,
    gwpi.updated_at,
    gp.code AS program_code,
    gp.name AS program_name,
    gp.snp_standard AS program_snp_standard,
    gd.title AS source_document_title,
    u.name AS owner_unit_name,
    e.nama AS responsible_employee_name,
    COALESCE(e.nip, '')::text AS responsible_employee_nip,
    gei.title AS evidence_item_title
FROM governance_work_plan_items gwpi
JOIN governance_programs gp ON gp.id = gwpi.program_id
LEFT JOIN governance_documents gd ON gd.id = gwpi.source_document_id
LEFT JOIN governance_units u ON u.id = gwpi.owner_unit_id
LEFT JOIN employees e ON e.id = gwpi.responsible_employee_id
LEFT JOIN governance_evidence_items gei ON gei.id = gwpi.evidence_item_id
WHERE (
    $1::TEXT = '' OR
    gwpi.activity_code ILIKE '%' || $1 || '%' OR
    gwpi.activity_name ILIKE '%' || $1 || '%' OR
    gwpi.output_indicator ILIKE '%' || $1 || '%' OR
    gwpi.budget_source ILIKE '%' || $1 || '%' OR
    gp.code ILIKE '%' || $1 || '%' OR
    gp.name ILIKE '%' || $1 || '%' OR
    u.name ILIKE '%' || $1 || '%' OR
    e.nama ILIKE '%' || $1 || '%'
) AND (
    $2::INT = 0 OR gwpi.period_year = $2
) AND (
    $3::UUID IS NULL OR gwpi.program_id = $3::UUID
) AND (
    $4::TEXT = '' OR gwpi.status = $4
)
ORDER BY gwpi.period_year DESC, gp.code, gwpi.activity_code
`

type ListGovernanceWorkPlanItemsParams struct {
	Search     string      `json:"search"`
	PeriodYear int32       `json:"period_year"`
	ProgramID  pgtype.UUID `json:"program_id"`
	Status     string      `json:"status"`
}

type ListGovernanceWorkPlanItemsRow struct {
	ID                      pgtype.UUID        `json:"id"`
	PeriodYear              int32              `json:"period_year"`
	ProgramID               pgtype.UUID        `json:"program_id"`
	SourceDocumentID        pgtype.UUID        `json:"source_document_id"`
	OwnerUnitID             pgtype.UUID        `json:"owner_unit_id"`
	ResponsibleEmployeeID   pgtype.UUID        `json:"responsible_employee_id"`
	EvidenceItemID          pgtype.UUID        `json:"evidence_item_id"`
	ActivityCode            string             `json:"activity_code"`
	ActivityName            string             `json:"activity_name"`
	OutputIndicator         string             `json:"output_indicator"`
	TargetVolume            string             `json:"target_volume"`
	TargetUnit              string             `json:"target_unit"`
	BudgetSource            string             `json:"budget_source"`
	BudgetAmount            int64              `json:"budget_amount"`
	RealizationAmount       int64              `json:"realization_amount"`
	Status                  string             `json:"status"`
	ProgressPercent         int32              `json:"progress_percent"`
	StartDate               pgtype.Date        `json:"start_date"`
	EndDate                 pgtype.Date        `json:"end_date"`
	EvidenceUrl             string             `json:"evidence_url"`
	Notes                   string             `json:"notes"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	ProgramCode             string             `json:"program_code"`
	ProgramName             string             `json:"program_name"`
	ProgramSnpStandard      string             `json:"program_snp_standard"`
	SourceDocumentTitle     pgtype.Text        `json:"source_document_title"`
	OwnerUnitName           pgtype.Text        `json:"owner_unit_name"`
	ResponsibleEmployeeName pgtype.Text        `json:"responsible_employee_name"`
	ResponsibleEmployeeNip  string             `json:"responsible_employee_nip"`
	EvidenceItemTitle       pgtype.Text        `json:"evidence_item_title"`
}

func (q *Queries) ListGovernanceWorkPlanItems(ctx context.Context, arg ListGovernanceWorkPlanItemsParams) ([]ListGovernanceWorkPlanItemsRow, error) {
	rows, err := q.db.Query(ctx, listGovernanceWorkPlanItems,
		arg.Search,
		arg.PeriodYear,
		arg.ProgramID,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGovernanceWorkPlanItemsRow{}
	for rows.Next() {
		var i ListGovernanceWorkPlanItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.PeriodYear,
			&i.ProgramID,
			&i.SourceDocumentID,
			&i.OwnerUnitID,
			&i.ResponsibleEmployeeID,
			&i.EvidenceItemID,
			&i.ActivityCode,
			&i.ActivityName,
			&i.OutputIndicator,
			&i.TargetVolume,
			&i.TargetUnit,
			&i.BudgetSource,
			&i.BudgetAmount,
			&i.RealizationAmount,
			&i.Status,
			&i.ProgressPercent,
			&i.StartDate,
			&i.EndDate,
			&i.EvidenceUrl,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProgramCode,
			&i.ProgramName,
			&i.ProgramSnpStandard,
			&i.SourceDocumentTitle,
			&i.OwnerUnitName,
			&i.ResponsibleEmployeeName,
			&i.ResponsibleEmployeeNip,
			&i.EvidenceItemTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGovernanceAssignment = `-- name: UpdateGovernanceAssignment :one
UPDATE governance_assignments
SET position_id = $2,
    employee_id = $3,
    start_date = $4,
    end_date = $5,
    decree_outgoing_letter_id = $6,
    notes = $7,
    updated_at = NOW()
WHERE id = $1
RETURNING id, position_id, employee_id, start_date, end_date, decree_outgoing_letter_id, notes, created_at, updated_at
`

type UpdateGovernanceAssignmentParams struct {
	ID                     pgtype.UUID `json:"id"`
	PositionID             pgtype.UUID `json:"position_id"`
	EmployeeID             pgtype.UUID `json:"employee_id"`
	StartDate              pgtype.Date `json:"start_date"`
	EndDate                pgtype.Date `json:"end_date"`
	DecreeOutgoingLetterID pgtype.UUID `json:"decree_outgoing_letter_id"`
	Notes                  string      `json:"notes"`
}

func (q *Queries) UpdateGovernanceAssignment(ctx context.Context, arg UpdateGovernanceAssignmentParams) (GovernanceAssignment, error) {
	row := q.db.QueryRow(ctx, updateGovernanceAssignment,
		arg.ID,
		arg.PositionID,
		arg.EmployeeID,
		arg.StartDate,
		arg.EndDate,
		arg.DecreeOutgoingLetterID,
		arg.Notes,
	)
	var i GovernanceAssignment
	err := row.Scan(
		&i.ID,
		&i.PositionID,
		&i.EmployeeID,
		&i.StartDate,
		&i.EndDate,
		&i.DecreeOutgoingLetterID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGovernanceComplianceAction = `-- name: UpdateGovernanceComplianceAction :one
UPDATE governance_compliance_actions
SET period_year = $2,
    source_type = $3,
    source_ref_id = $4,
    snp_standard = $5,
    program_id = $6,
    document_id = $7,
    performance_target_id = $8,
    evidence_item_id = $9,
    owner_unit_id = $10,
    responsible_employee_id = $11,
    title = $12,
    description = $13,
    priority = $14,
    status = $15,
    due_date = $16,
    completed_at = $17,
    follow_up_notes = $18,
    evidence_url = $19,
    updated_at = NOW()
WHERE id = $1
RETURNING id, period_year, source_type, source_ref_id, snp_standard, program_id, document_id, performance_target_id, evidence_item_id, owner_unit_id, responsible_employee_id, title, description, priority, status, due_date, completed_at, follow_up_notes, evidence_url, created_by_user_id, created_at, updated_at
`

type UpdateGovernanceComplianceActionParams struct {
	ID                    pgtype.UUID        `json:"id"`
	PeriodYear            int32              `json:"period_year"`
	SourceType            string             `json:"source_type"`
	SourceRefID           pgtype.UUID        `json:"source_ref_id"`
	SnpStandard           string             `json:"snp_standard"`
	ProgramID             pgtype.UUID        `json:"program_id"`
	DocumentID            pgtype.UUID        `json:"document_id"`
	PerformanceTargetID   pgtype.UUID        `json:"performance_target_id"`
	EvidenceItemID        pgtype.UUID        `json:"evidence_item_id"`
	OwnerUnitID           pgtype.UUID        `json:"owner_unit_id"`
	ResponsibleEmployeeID pgtype.UUID        `json:"responsible_employee_id"`
	Title                 string             `json:"title"`
	Description           string             `json:"description"`
	Priority              string             `json:"priority"`
	Status                string             `json:"status"`
	DueDate               pgtype.Date        `json:"due_date"`
	CompletedAt           pgtype.Timestamptz `json:"completed_at"`
	FollowUpNotes         string             `json:"follow_up_notes"`
	EvidenceUrl           string             `json:"evidence_url"`
}

func (q *Queries) UpdateGovernanceComplianceAction(ctx context.Context, arg UpdateGovernanceComplianceActionParams) (GovernanceComplianceAction, error) {
	row := q.db.QueryRow(ctx, updateGovernanceComplianceAction,
		arg.ID,
		arg.PeriodYear,
		arg.SourceType,
		arg.SourceRefID,
		arg.SnpStandard,
		arg.ProgramID,
		arg.DocumentID,
		arg.PerformanceTargetID,
		arg.EvidenceItemID,
		arg.OwnerUnitID,
		arg.ResponsibleEmployeeID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.Status,
		arg.DueDate,
		arg.CompletedAt,
		arg.FollowUpNotes,
		arg.EvidenceUrl,
	)
	var i GovernanceComplianceAction
	err := row.Scan(
		&i.ID,
		&i.PeriodYear,
		&i.SourceType,
		&i.SourceRefID,
		&i.SnpStandard,
		&i.ProgramID,
		&i.DocumentID,
		&i.PerformanceTargetID,
		&i.EvidenceItemID,
		&i.OwnerUnitID,
		&i.ResponsibleEmployeeID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.DueDate,
		&i.CompletedAt,
		&i.FollowUpNotes,
		&i.EvidenceUrl,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGovernanceDocument = `-- name: UpdateGovernanceDocument :one
UPDATE governance_documents
SET doc_type = $2,
    title = $3,
    period_year = $4,
    period_label = $5,
    owner_unit_id = $6,
    snp_standard = $7,
    status = $8,
    document_url = $9,
    outgoing_letter_id = $10,
    summary = $11,
    updated_at = NOW()
WHERE id = $1
RETURNING id, doc_type, title, period_year, period_label, owner_unit_id, snp_standard, status, document_url, outgoing_letter_id, summary, created_by_user_id, created_at, updated_at
`

type UpdateGovernanceDocumentParams struct {
	ID               pgtype.UUID `json:"id"`
	DocType          string      `json:"doc_type"`
	Title            string      `json:"title"`
	PeriodYear       int32       `json:"period_year"`
	PeriodLabel      string      `json:"period_label"`
	OwnerUnitID      pgtype.UUID `json:"owner_unit_id"`
	SnpStandard      string      `json:"snp_standard"`
	Status           string      `json:"status"`
	DocumentUrl      string      `json:"document_url"`
	OutgoingLetterID pgtype.UUID `json:"outgoing_letter_id"`
	Summary          string      `json:"summary"`
}

func (q *Queries) UpdateGovernanceDocument(ctx context.Context, arg UpdateGovernanceDocumentParams) (GovernanceDocument, error) {
	row := q.db.QueryRow(ctx, updateGovernanceDocument,
		arg.ID,
		arg.DocType,
		arg.Title,
		arg.PeriodYear,
		arg.PeriodLabel,
		arg.OwnerUnitID,
		arg.SnpStandard,
		arg.Status,
		arg.DocumentUrl,
		arg.OutgoingLetterID,
		arg.Summary,
	)
	var i GovernanceDocument
	err := row.Scan(
		&i.ID,
		&i.DocType,
		&i.Title,
		&i.PeriodYear,
		&i.PeriodLabel,
		&i.OwnerUnitID,
		&i.SnpStandard,
		&i.Status,
		&i.DocumentUrl,
		&i.OutgoingLetterID,
		&i.Summary,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGovernanceEvidenceItem = `-- name: UpdateGovernanceEvidenceItem :one
UPDATE governance_evidence_items
SET period_year = $2,
    title = $3,
    evidence_type = $4,
    snp_standard = $5,
    owner_unit_id = $6,
    document_id = $7,
    program_id = $8,
    performance_target_id = $9,
    source_module = $10,
    evidence_url = $11,
    status = $12,
    notes = $13,
    updated_at = NOW()
WHERE id = $1
RETURNING id, period_year, title, evidence_type, snp_standard, owner_unit_id, document_id, program_id, performance_target_id, source_module, evidence_url, status, notes, verified_by_user_id, verified_at, created_by_user_id, created_at, updated_at
`

type UpdateGovernanceEvidenceItemParams struct {
	ID                  pgtype.UUID `json:"id"`
	PeriodYear          int32       `json:"period_year"`
	Title               string      `json:"title"`
	EvidenceType        string      `json:"evidence_type"`
	SnpStandard         string      `json:"snp_standard"`
	OwnerUnitID         pgtype.UUID `json:"owner_unit_id"`
	DocumentID          pgtype.UUID `json:"document_id"`
	ProgramID           pgtype.UUID `json:"program_id"`
	PerformanceTargetID pgtype.UUID `json:"performance_target_id"`
	SourceModule        string      `json:"source_module"`
	EvidenceUrl         string      `json:"evidence_url"`
	Status              string      `json:"status"`
	Notes               string      `json:"notes"`
}

func (q *Queries) UpdateGovernanceEvidenceItem(ctx context.Context, arg UpdateGovernanceEvidenceItemParams) (GovernanceEvidenceItem, error) {
	row := q.db.QueryRow(ctx, updateGovernanceEvidenceItem,
		arg.ID,
		arg.PeriodYear,
		arg.Title,
		arg.EvidenceType,
		arg.SnpStandard,
		arg.OwnerUnitID,
		arg.DocumentID,
		arg.ProgramID,
		arg.PerformanceTargetID,
		arg.SourceModule,
		arg.EvidenceUrl,
		arg.Status,
		arg.Notes,
	)
	var i GovernanceEvidenceItem
	err := row.Scan(
		&i.ID,
		&i.PeriodYear,
		&i.Title,
		&i.EvidenceType,
		&i.SnpStandard,
		&i.OwnerUnitID,
		&i.DocumentID,
		&i.ProgramID,
		&i.PerformanceTargetID,
		&i.SourceModule,
		&i.EvidenceUrl,
		&i.Status,
		&i.Notes,
		&i.VerifiedByUserID,
		&i.VerifiedAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGovernancePerformanceTarget = `-- name: UpdateGovernancePerformanceTarget :one
UPDATE governance_performance_targets
SET period_year = $2,
    employee_id = $3,
    position_id = $4,
    program_id = $5,
    parent_target_id = $6,
    aspect = $7,
    title = $8,
    indicator = $9,
    target_value = $10,
    target_unit = $11,
    status = $12,
    progress_percent = $13,
    evidence_url = $14,
    review_notes = $15,
    due_date = $16,
    updated_at = NOW()
WHERE id = $1
RETURNING id, period_year, employee_id, position_id, program_id, parent_target_id, aspect, title, indicator, target_value, target_unit, status, progress_percent, evidence_url, review_notes, due_date, created_by_user_id, created_at, updated_at
`

type UpdateGovernancePerformanceTargetParams struct {
	ID              pgtype.UUID `json:"id"`
	PeriodYear      int32       `json:"period_year"`
	EmployeeID      pgtype.UUID `json:"employee_id"`
	PositionID      pgtype.UUID `json:"position_id"`
	ProgramID       pgtype.UUID `json:"program_id"`
	ParentTargetID  pgtype.UUID `json:"parent_target_id"`
	Aspect          string      `json:"aspect"`
	Title           string      `json:"title"`
	Indicator       string      `json:"indicator"`
	TargetValue     string      `json:"target_value"`
	TargetUnit      string      `json:"target_unit"`
	Status          string      `json:"status"`
	ProgressPercent int32       `json:"progress_percent"`
	EvidenceUrl     string      `json:"evidence_url"`
	ReviewNotes     string      `json:"review_notes"`
	DueDate         pgtype.Date `json:"due_date"`
}

func (q *Queries) UpdateGovernancePerformanceTarget(ctx context.Context, arg UpdateGovernancePerformanceTargetParams) (GovernancePerformanceTarget, error) {
	row := q.db.QueryRow(ctx, updateGovernancePerformanceTarget,
		arg.ID,
		arg.PeriodYear,
		arg.EmployeeID,
		arg.PositionID,
		arg.ProgramID,
		arg.ParentTargetID,
		arg.Aspect,
		arg.Title,
		arg.Indicator,
		arg.TargetValue,
		arg.TargetUnit,
		arg.Status,
		arg.ProgressPercent,
		arg.EvidenceUrl,
		arg.ReviewNotes,
		arg.DueDate,
	)
	var i GovernancePerformanceTarget
	err := row.Scan(
		&i.ID,
		&i.PeriodYear,
		&i.EmployeeID,
		&i.PositionID,
		&i.ProgramID,
		&i.ParentTargetID,
		&i.Aspect,
		&i.Title,
		&i.Indicator,
		&i.TargetValue,
		&i.TargetUnit,
		&i.Status,
		&i.ProgressPercent,
		&i.EvidenceUrl,
		&i.ReviewNotes,
		&i.DueDate,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGovernancePosition = `-- name: UpdateGovernancePosition :one
UPDATE governance_positions
SET unit_id = $2,
    title = $3,
    position_type = $4,
    parent_position_id = $5,
    description = $6,
    tupoksi = $7,
    is_active = $8,
    sort_order = $9,
    updated_at = NOW()
WHERE id = $1
RETURNING id, unit_id, title, position_type, parent_position_id, description, tupoksi, is_active, sort_order, created_at, updated_at
`

type UpdateGovernancePositionParams struct {
	ID               pgtype.UUID `json:"id"`
	UnitID           pgtype.UUID `json:"unit_id"`
	Title            string      `json:"title"`
	PositionType     string      `json:"position_type"`
	ParentPositionID pgtype.UUID `json:"parent_position_id"`
	Description      string      `json:"description"`
	Tupoksi          string      `json:"tupoksi"`
	IsActive         bool        `json:"is_active"`
	SortOrder        int32       `json:"sort_order"`
}

func (q *Queries) UpdateGovernancePosition(ctx context.Context, arg UpdateGovernancePositionParams) (GovernancePosition, error) {
	row := q.db.QueryRow(ctx, updateGovernancePosition,
		arg.ID,
		arg.UnitID,
		arg.Title,
		arg.PositionType,
		arg.ParentPositionID,
		arg.Description,
		arg.Tupoksi,
		arg.IsActive,
		arg.SortOrder,
	)
	var i GovernancePosition
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.Title,
		&i.PositionType,
		&i.ParentPositionID,
		&i.Description,
		&i.Tupoksi,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGovernanceProgram = `-- name: UpdateGovernanceProgram :one
UPDATE governance_programs
SET period_year = $2,
    code = $3,
    name = $4,
    source_document_id = $5,
    owner_unit_id = $6,
    responsible_position_id = $7,
    responsible_employee_id = $8,
    snp_standard = $9,
    iku_code = $10,
    indicator = $11,
    target_value = $12,
    target_unit = $13,
    status = $14,
    progress_percent = $15,
    realization_summary = $16,
    evidence_url = $17,
    due_date = $18,
    updated_at = NOW()
WHERE id = $1
RETURNING id, period_year, code, name, source_document_id, owner_unit_id, responsible_position_id, responsible_employee_id, snp_standard, iku_code, indicator, target_value, target_unit, status, progress_percent, realization_summary, evidence_url, due_date, created_at, updated_at
`

type UpdateGovernanceProgramParams struct {
	ID                    pgtype.UUID `json:"id"`
	PeriodYear            int32       `json:"period_year"`
	Code                  string      `json:"code"`
	Name                  string      `json:"name"`
	SourceDocumentID      pgtype.UUID `json:"source_document_id"`
	OwnerUnitID           pgtype.UUID `json:"owner_unit_id"`
	ResponsiblePositionID pgtype.UUID `json:"responsible_position_id"`
	ResponsibleEmployeeID pgtype.UUID `json:"responsible_employee_id"`
	SnpStandard           string      `json:"snp_standard"`
	IkuCode               string      `json:"iku_code"`
	Indicator             string      `json:"indicator"`
	TargetValue           string      `json:"target_value"`
	TargetUnit            string      `json:"target_unit"`
	Status                string      `json:"status"`
	ProgressPercent       int32       `json:"progress_percent"`
	RealizationSummary    string      `json:"realization_summary"`
	EvidenceUrl           string      `json:"evidence_url"`
	DueDate               pgtype.Date `json:"due_date"`
}

func (q *Queries) UpdateGovernanceProgram(ctx context.Context, arg UpdateGovernanceProgramParams) (GovernanceProgram, error) {
	row := q.db.QueryRow(ctx, updateGovernanceProgram,
		arg.ID,
		arg.PeriodYear,
		arg.Code,
		arg.Name,
		arg.SourceDocumentID,
		arg.OwnerUnitID,
		arg.ResponsiblePositionID,
		arg.ResponsibleEmployeeID,
		arg.SnpStandard,
		arg.IkuCode,
		arg.Indicator,
		arg.TargetValue,
		arg.TargetUnit,
		arg.Status,
		arg.ProgressPercent,
		arg.RealizationSummary,
		arg.EvidenceUrl,
		arg.DueDate,
	)
	var i GovernanceProgram
	err := row.Scan(
		&i.ID,
		&i.PeriodYear,
		&i.Code,
		&i.Name,
		&i.SourceDocumentID,
		&i.OwnerUnitID,
		&i.ResponsiblePositionID,
		&i.ResponsibleEmployeeID,
		&i.SnpStandard,
		&i.IkuCode,
		&i.Indicator,
		&i.TargetValue,
		&i.TargetUnit,
		&i.Status,
		&i.ProgressPercent,
		&i.RealizationSummary,
		&i.EvidenceUrl,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGovernanceUnit = `-- name: UpdateGovernanceUnit :one
UPDATE governance_units
SET code = $2,
    name = $3,
    unit_type = $4,
    parent_id = $5,
    description = $6,
    is_active = $7,
    sort_order = $8,
    updated_at = NOW()
WHERE id = $1
RETURNING id, code, name, unit_type, parent_id, description, is_active, sort_order, created_at, updated_at
`

type UpdateGovernanceUnitParams struct {
	ID          pgtype.UUID `json:"id"`
	Code        string      `json:"code"`
	Name        string      `json:"name"`
	UnitType    string      `json:"unit_type"`
	ParentID    pgtype.UUID `json:"parent_id"`
	Description string      `json:"description"`
	IsActive    bool        `json:"is_active"`
	SortOrder   int32       `json:"sort_order"`
}

func (q *Queries) UpdateGovernanceUnit(ctx context.Context, arg UpdateGovernanceUnitParams) (GovernanceUnit, error) {
	row := q.db.QueryRow(ctx, updateGovernanceUnit,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.UnitType,
		arg.ParentID,
		arg.Description,
		arg.IsActive,
		arg.SortOrder,
	)
	var i GovernanceUnit
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.UnitType,
		&i.ParentID,
		&i.Description,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGovernanceWorkPlanItem = `-- name: UpdateGovernanceWorkPlanItem :one
UPDATE governance_work_plan_items
SET period_year = $2,
    program_id = $3,
    source_document_id = $4,
    owner_unit_id = $5,
    responsible_employee_id = $6,
    evidence_item_id = $7,
    activity_code = $8,
    activity_name = $9,
    output_indicator = $10,
    target_volume = $11,
    target_unit = $12,
    budget_source = $13,
    budget_amount = $14,
    realization_amount = $15,
    status = $16,
    progress_percent = $17,
    start_date = $18,
    end_date = $19,
    evidence_url = $20,
    notes = $21,
    updated_at = NOW()
WHERE id = $1
RETURNING id, period_year, program_id, source_document_id, owner_unit_id, responsible_employee_id, evidence_item_id, activity_code, activity_name, output_indicator, target_volume, target_unit, budget_source, budget_amount, realization_amount, status, progress_percent, start_date, end_date, evidence_url, notes, created_at, updated_at
`

type UpdateGovernanceWorkPlanItemParams struct {
	ID                    pgtype.UUID `json:"id"`
	PeriodYear            int32       `json:"period_year"`
	ProgramID             pgtype.UUID `json:"program_id"`
	SourceDocumentID      pgtype.UUID `json:"source_document_id"`
	OwnerUnitID           pgtype.UUID `json:"owner_unit_id"`
	ResponsibleEmployeeID pgtype.UUID `json:"responsible_employee_id"`
	EvidenceItemID        pgtype.UUID `json:"evidence_item_id"`
	ActivityCode          string      `json:"activity_code"`
	ActivityName          string      `json:"activity_name"`
	OutputIndicator       string      `json:"output_indicator"`
	TargetVolume          string      `json:"target_volume"`
	TargetUnit            string      `json:"target_unit"`
	BudgetSource          string      `json:"budget_source"`
	BudgetAmount          int64       `json:"budget_amount"`
	RealizationAmount     int64       `json:"realization_amount"`
	Status                string      `json:"status"`
	ProgressPercent       int32       `json:"progress_percent"`
	StartDate             pgtype.Date `json:"start_date"`
	EndDate               pgtype.Date `json:"end_date"`
	EvidenceUrl           string      `json:"evidence_url"`
	Notes                 string      `json:"notes"`
}

func (q *Queries) UpdateGovernanceWorkPlanItem(ctx context.Context, arg UpdateGovernanceWorkPlanItemParams) (GovernanceWorkPlanItem, error) {
	row := q.db.QueryRow(ctx, updateGovernanceWorkPlanItem,
		arg.ID,
		arg.PeriodYear,
		arg.ProgramID,
		arg.SourceDocumentID,
		arg.OwnerUnitID,
		arg.ResponsibleEmployeeID,
		arg.EvidenceItemID,
		arg.ActivityCode,
		arg.ActivityName,
		arg.OutputIndicator,
		arg.TargetVolume,
		arg.TargetUnit,
		arg.BudgetSource,
		arg.BudgetAmount,
		arg.RealizationAmount,
		arg.Status,
		arg.ProgressPercent,
		arg.StartDate,
		arg.EndDate,
		arg.EvidenceUrl,
		arg.Notes,
	)
	var i GovernanceWorkPlanItem
	err := row.Scan(
		&i.ID,
		&i.PeriodYear,
		&i.ProgramID,
		&i.SourceDocumentID,
		&i.OwnerUnitID,
		&i.ResponsibleEmployeeID,
		&i.EvidenceItemID,
		&i.ActivityCode,
		&i.ActivityName,
		&i.OutputIndicator,
		&i.TargetVolume,
		&i.TargetUnit,
		&i.BudgetSource,
		&i.BudgetAmount,
		&i.RealizationAmount,
		&i.Status,
		&i.ProgressPercent,
		&i.StartDate,
		&i.EndDate,
		&i.EvidenceUrl,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
