// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUserRole = `-- name: AddUserRole :exec
INSERT INTO user_account_roles (user_id, role) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddUserRoleParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Role   UserRole    `json:"role"`
}

func (q *Queries) AddUserRole(ctx context.Context, arg AddUserRoleParams) error {
	_, err := q.db.Exec(ctx, addUserRole, arg.UserID, arg.Role)
	return err
}

const changeUserPasswordAndInvalidate = `-- name: ChangeUserPasswordAndInvalidate :one
WITH updated AS (
  UPDATE users
  SET password_hash = $1,
      must_change_password = FALSE,
      password_changed_at = NOW(),
      auth_version = auth_version + 1,
      updated_at = NOW()
  WHERE users.id = $2
    AND users.deleted_at IS NULL
  RETURNING users.id, users.auth_version
), revoked AS (
  UPDATE auth_sessions
  SET revoked_at = NOW(),
      updated_at = NOW()
  WHERE user_id = (SELECT updated.id FROM updated)
    AND revoked_at IS NULL
  RETURNING auth_sessions.id
)
SELECT updated.auth_version FROM updated
`

type ChangeUserPasswordAndInvalidateParams struct {
	PasswordHash string      `json:"password_hash"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) ChangeUserPasswordAndInvalidate(ctx context.Context, arg ChangeUserPasswordAndInvalidateParams) (int32, error) {
	row := q.db.QueryRow(ctx, changeUserPasswordAndInvalidate, arg.PasswordHash, arg.ID)
	var auth_version int32
	err := row.Scan(&auth_version)
	return auth_version, err
}

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (user_id, action, entity_type, entity_id, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, action, entity_type, entity_id, metadata, created_at
`

type CreateAuditLogParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	Action     string      `json:"action"`
	EntityType string      `json:"entity_type"`
	EntityID   string      `json:"entity_id"`
	Metadata   []byte      `json:"metadata"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.UserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Metadata,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash, display_name, employee_id, student_id, parent_id, is_active, must_change_password, password_changed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, TRUE, NULL)
RETURNING id, username, display_name, employee_id, student_id, parent_id, is_active, auth_version, must_change_password, password_changed_at, last_login_at, deleted_at, created_at, updated_at
`

type CreateUserParams struct {
	Username     string      `json:"username"`
	PasswordHash string      `json:"password_hash"`
	DisplayName  pgtype.Text `json:"display_name"`
	EmployeeID   pgtype.UUID `json:"employee_id"`
	StudentID    pgtype.UUID `json:"student_id"`
	ParentID     pgtype.UUID `json:"parent_id"`
	IsActive     bool        `json:"is_active"`
}

type CreateUserRow struct {
	ID                 pgtype.UUID        `json:"id"`
	Username           string             `json:"username"`
	DisplayName        pgtype.Text        `json:"display_name"`
	EmployeeID         pgtype.UUID        `json:"employee_id"`
	StudentID          pgtype.UUID        `json:"student_id"`
	ParentID           pgtype.UUID        `json:"parent_id"`
	IsActive           bool               `json:"is_active"`
	AuthVersion        int32              `json:"auth_version"`
	MustChangePassword bool               `json:"must_change_password"`
	PasswordChangedAt  pgtype.Timestamptz `json:"password_changed_at"`
	LastLoginAt        pgtype.Timestamptz `json:"last_login_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.PasswordHash,
		arg.DisplayName,
		arg.EmployeeID,
		arg.StudentID,
		arg.ParentID,
		arg.IsActive,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.EmployeeID,
		&i.StudentID,
		&i.ParentID,
		&i.IsActive,
		&i.AuthVersion,
		&i.MustChangePassword,
		&i.PasswordChangedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserWithMustChangePassword = `-- name: CreateUserWithMustChangePassword :one
INSERT INTO users (username, password_hash, display_name, employee_id, student_id, parent_id, is_active, must_change_password, password_changed_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    CASE WHEN $8::boolean THEN NULL ELSE NOW() END
)
RETURNING id, username, display_name, employee_id, student_id, parent_id, is_active, auth_version, must_change_password, password_changed_at, last_login_at, deleted_at, created_at, updated_at
`

type CreateUserWithMustChangePasswordParams struct {
	Username           string      `json:"username"`
	PasswordHash       string      `json:"password_hash"`
	DisplayName        pgtype.Text `json:"display_name"`
	EmployeeID         pgtype.UUID `json:"employee_id"`
	StudentID          pgtype.UUID `json:"student_id"`
	ParentID           pgtype.UUID `json:"parent_id"`
	IsActive           bool        `json:"is_active"`
	MustChangePassword bool        `json:"must_change_password"`
}

type CreateUserWithMustChangePasswordRow struct {
	ID                 pgtype.UUID        `json:"id"`
	Username           string             `json:"username"`
	DisplayName        pgtype.Text        `json:"display_name"`
	EmployeeID         pgtype.UUID        `json:"employee_id"`
	StudentID          pgtype.UUID        `json:"student_id"`
	ParentID           pgtype.UUID        `json:"parent_id"`
	IsActive           bool               `json:"is_active"`
	AuthVersion        int32              `json:"auth_version"`
	MustChangePassword bool               `json:"must_change_password"`
	PasswordChangedAt  pgtype.Timestamptz `json:"password_changed_at"`
	LastLoginAt        pgtype.Timestamptz `json:"last_login_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUserWithMustChangePassword(ctx context.Context, arg CreateUserWithMustChangePasswordParams) (CreateUserWithMustChangePasswordRow, error) {
	row := q.db.QueryRow(ctx, createUserWithMustChangePassword,
		arg.Username,
		arg.PasswordHash,
		arg.DisplayName,
		arg.EmployeeID,
		arg.StudentID,
		arg.ParentID,
		arg.IsActive,
		arg.MustChangePassword,
	)
	var i CreateUserWithMustChangePasswordRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.EmployeeID,
		&i.StudentID,
		&i.ParentID,
		&i.IsActive,
		&i.AuthVersion,
		&i.MustChangePassword,
		&i.PasswordChangedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOldAuditLogs = `-- name: DeleteOldAuditLogs :execrows
DELETE FROM audit_logs
WHERE created_at < NOW() - INTERVAL '90 days'
`

func (q *Queries) DeleteOldAuditLogs(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldAuditLogs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserAccountSummary = `-- name: GetUserAccountSummary :one
SELECT
    u.id,
    u.username,
    COALESCE(NULLIF(u.display_name, ''), e.nama, s.nama, p.nama, u.username)::text AS display_name,
    u.employee_id,
    u.student_id,
    u.parent_id,
    CASE
        WHEN u.employee_id IS NOT NULL THEN 'employee'
        WHEN u.student_id IS NOT NULL THEN 'student'
        WHEN u.parent_id IS NOT NULL THEN 'parent'
        ELSE ''
    END::text AS profile_type,
    COALESCE(e.nama, s.nama, p.nama, '')::text AS profile_nama,
    CASE
        WHEN u.employee_id IS NOT NULL THEN e.phone
        WHEN u.student_id IS NOT NULL THEN s.phone
        WHEN u.parent_id IS NOT NULL THEN p.phone
        ELSE ''
    END::text AS contact_phone,
    CASE
        WHEN u.employee_id IS NOT NULL THEN e.email
        ELSE ''
    END::text AS contact_email,
    CASE
        WHEN u.employee_id IS NOT NULL THEN e.address
        WHEN u.student_id IS NOT NULL THEN s.alamat
        WHEN u.parent_id IS NOT NULL THEN p.address
        ELSE ''
    END::text AS contact_address,
    CASE
        WHEN u.employee_id IS NOT NULL THEN e.photo_url
        WHEN u.student_id IS NOT NULL THEN s.photo_url
        WHEN u.parent_id IS NOT NULL THEN p.photo_url
        ELSE ''
    END::text AS photo_url,
    u.is_active,
    u.must_change_password,
    u.password_changed_at,
    u.last_login_at,
    u.created_at,
    COALESCE(
      (
        SELECT json_agg(r.code ORDER BY r.code)
        FROM rbac_user_roles ur
        JOIN rbac_roles r ON r.id = ur.role_id
        WHERE ur.user_id = u.id
          AND r.is_active = TRUE
      ),
      (SELECT json_agg(role) FROM user_account_roles WHERE user_id = u.id),
      '[]'::json
    ) as roles
FROM users u
LEFT JOIN employees e ON e.id = u.employee_id
LEFT JOIN students s ON s.id = u.student_id
LEFT JOIN parents p ON p.id = u.parent_id
WHERE u.id = $1
  AND u.deleted_at IS NULL
`

type GetUserAccountSummaryRow struct {
	ID                 pgtype.UUID        `json:"id"`
	Username           string             `json:"username"`
	DisplayName        string             `json:"display_name"`
	EmployeeID         pgtype.UUID        `json:"employee_id"`
	StudentID          pgtype.UUID        `json:"student_id"`
	ParentID           pgtype.UUID        `json:"parent_id"`
	ProfileType        string             `json:"profile_type"`
	ProfileNama        string             `json:"profile_nama"`
	ContactPhone       string             `json:"contact_phone"`
	ContactEmail       string             `json:"contact_email"`
	ContactAddress     string             `json:"contact_address"`
	PhotoUrl           string             `json:"photo_url"`
	IsActive           bool               `json:"is_active"`
	MustChangePassword bool               `json:"must_change_password"`
	PasswordChangedAt  pgtype.Timestamptz `json:"password_changed_at"`
	LastLoginAt        pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	Roles              interface{}        `json:"roles"`
}

func (q *Queries) GetUserAccountSummary(ctx context.Context, id pgtype.UUID) (GetUserAccountSummaryRow, error) {
	row := q.db.QueryRow(ctx, getUserAccountSummary, id)
	var i GetUserAccountSummaryRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.EmployeeID,
		&i.StudentID,
		&i.ParentID,
		&i.ProfileType,
		&i.ProfileNama,
		&i.ContactPhone,
		&i.ContactEmail,
		&i.ContactAddress,
		&i.PhotoUrl,
		&i.IsActive,
		&i.MustChangePassword,
		&i.PasswordChangedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.Roles,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT 
    u.id, u.username, u.password_hash,
    u.display_name,
    u.employee_id, u.student_id, u.parent_id,
    u.is_active, u.auth_version, u.must_change_password, u.password_changed_at, u.last_login_at, u.deleted_at, u.created_at, u.updated_at,
    COALESCE(
      (
        SELECT json_agg(r.code ORDER BY r.code)
        FROM rbac_user_roles ur
        JOIN rbac_roles r ON r.id = ur.role_id
        WHERE ur.user_id = u.id
          AND r.is_active = TRUE
      ),
      (SELECT json_agg(role) FROM user_account_roles WHERE user_id = u.id),
      '[]'::json
    ) as roles
FROM users u
WHERE u.id = $1
  AND u.deleted_at IS NULL
`

type GetUserByIDRow struct {
	ID                 pgtype.UUID        `json:"id"`
	Username           string             `json:"username"`
	PasswordHash       string             `json:"password_hash"`
	DisplayName        pgtype.Text        `json:"display_name"`
	EmployeeID         pgtype.UUID        `json:"employee_id"`
	StudentID          pgtype.UUID        `json:"student_id"`
	ParentID           pgtype.UUID        `json:"parent_id"`
	IsActive           bool               `json:"is_active"`
	AuthVersion        int32              `json:"auth_version"`
	MustChangePassword bool               `json:"must_change_password"`
	PasswordChangedAt  pgtype.Timestamptz `json:"password_changed_at"`
	LastLoginAt        pgtype.Timestamptz `json:"last_login_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	Roles              interface{}        `json:"roles"`
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.EmployeeID,
		&i.StudentID,
		&i.ParentID,
		&i.IsActive,
		&i.AuthVersion,
		&i.MustChangePassword,
		&i.PasswordChangedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Roles,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT 
    u.id, u.username, u.password_hash,
    u.display_name,
    u.employee_id, u.student_id, u.parent_id,
    u.is_active, u.auth_version, u.must_change_password, u.password_changed_at, u.last_login_at, u.deleted_at, u.created_at, u.updated_at,
    COALESCE(
      (
        SELECT json_agg(r.code ORDER BY r.code)
        FROM rbac_user_roles ur
        JOIN rbac_roles r ON r.id = ur.role_id
        WHERE ur.user_id = u.id
          AND r.is_active = TRUE
      ),
      (SELECT json_agg(role) FROM user_account_roles WHERE user_id = u.id),
      '[]'::json
    ) as roles
FROM users u
WHERE u.username = $1
  AND u.deleted_at IS NULL
`

type GetUserByUsernameRow struct {
	ID                 pgtype.UUID        `json:"id"`
	Username           string             `json:"username"`
	PasswordHash       string             `json:"password_hash"`
	DisplayName        pgtype.Text        `json:"display_name"`
	EmployeeID         pgtype.UUID        `json:"employee_id"`
	StudentID          pgtype.UUID        `json:"student_id"`
	ParentID           pgtype.UUID        `json:"parent_id"`
	IsActive           bool               `json:"is_active"`
	AuthVersion        int32              `json:"auth_version"`
	MustChangePassword bool               `json:"must_change_password"`
	PasswordChangedAt  pgtype.Timestamptz `json:"password_changed_at"`
	LastLoginAt        pgtype.Timestamptz `json:"last_login_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	Roles              interface{}        `json:"roles"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.EmployeeID,
		&i.StudentID,
		&i.ParentID,
		&i.IsActive,
		&i.AuthVersion,
		&i.MustChangePassword,
		&i.PasswordChangedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Roles,
	)
	return i, err
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT role FROM user_account_roles WHERE user_id = $1
`

func (q *Queries) GetUserRoles(ctx context.Context, userID pgtype.UUID) ([]UserRole, error) {
	rows, err := q.db.Query(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserRole{}
	for rows.Next() {
		var role UserRole
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementUserAuthVersion = `-- name: IncrementUserAuthVersion :one
UPDATE users
SET auth_version = auth_version + 1,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING auth_version
`

func (q *Queries) IncrementUserAuthVersion(ctx context.Context, id pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementUserAuthVersion, id)
	var auth_version int32
	err := row.Scan(&auth_version)
	return auth_version, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT
    a.id,
    a.user_id,
    u.username,
    COALESCE(NULLIF(btrim(u.display_name), ''), ue.nama, us.nama, up.nama, u.username, '')::text AS user_display_name,
    a.action,
    a.entity_type,
    a.entity_id,
    a.metadata,
    a.created_at
FROM audit_logs a
LEFT JOIN users u ON u.id = a.user_id
LEFT JOIN employees ue ON ue.id = u.employee_id
LEFT JOIN students us ON us.id = u.student_id
LEFT JOIN parents up ON up.id = u.parent_id
ORDER BY a.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAuditLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAuditLogsRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Username        pgtype.Text        `json:"username"`
	UserDisplayName string             `json:"user_display_name"`
	Action          string             `json:"action"`
	EntityType      string             `json:"entity_type"`
	EntityID        string             `json:"entity_id"`
	Metadata        []byte             `json:"metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsRow{}
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.UserDisplayName,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeeAccountGenerationCandidates = `-- name: ListEmployeeAccountGenerationCandidates :many
WITH active_employees AS (
    SELECT
        e.id,
        COALESCE(e.nip, '')::text AS nip,
        e.nama,
        e.tanggal_lahir,
        CASE
            WHEN e.tanggal_lahir IS NULL THEN ''::text
            ELSE to_char(e.tanggal_lahir, 'YY')
        END AS birth_year_suffix
    FROM employees e
    WHERE e.is_active = TRUE
), linked_employees AS (
    SELECT
        ae.id, ae.nip, ae.nama, ae.tanggal_lahir, ae.birth_year_suffix,
        linked.id AS existing_user_id
    FROM active_employees ae
    LEFT JOIN users linked ON linked.employee_id = ae.id AND linked.deleted_at IS NULL
), existing_sequences AS (
    SELECT
        substring(u.username FROM length($1::text) + 1 FOR 2) AS birth_year_suffix,
        max(substring(u.username FROM length($1::text) + 3 FOR 3)::int)::int AS max_sequence
    FROM users u
    WHERE u.username ~ ('^' || $1::text || '[0-9]{5}$')
    GROUP BY substring(u.username FROM length($1::text) + 1 FOR 2)
), sequenced_candidates AS (
    SELECT
        le.id AS employee_id,
        le.nip,
        le.nama,
        le.tanggal_lahir,
        le.birth_year_suffix,
        le.existing_user_id,
        CASE
            WHEN le.tanggal_lahir IS NULL OR le.existing_user_id IS NOT NULL THEN 0
            ELSE (COALESCE(es.max_sequence, 0) + sum(CASE WHEN le.tanggal_lahir IS NOT NULL AND le.existing_user_id IS NULL THEN 1 ELSE 0 END) OVER (
                PARTITION BY le.birth_year_suffix
                ORDER BY le.nama ASC, le.id ASC
            ))::int
        END AS nomor_urut
    FROM linked_employees le
    LEFT JOIN existing_sequences es ON es.birth_year_suffix = le.birth_year_suffix
)
SELECT
    sc.employee_id,
    sc.nip,
    sc.nama,
    sc.tanggal_lahir,
    sc.nomor_urut,
    CASE
        WHEN sc.tanggal_lahir IS NULL OR sc.existing_user_id IS NOT NULL THEN ''::text
        ELSE ($1::text || sc.birth_year_suffix || lpad(sc.nomor_urut::text, 3, '0'))::text
    END AS generated_username,
    sc.existing_user_id,
    username_user.id AS username_user_id
FROM sequenced_candidates sc
LEFT JOIN users username_user ON username_user.username = ($1::text || sc.birth_year_suffix || lpad(sc.nomor_urut::text, 3, '0'))
    AND sc.nomor_urut > 0
    AND username_user.deleted_at IS NULL
ORDER BY sc.birth_year_suffix ASC NULLS LAST, sc.nomor_urut ASC, sc.nama ASC, sc.employee_id ASC
`

type ListEmployeeAccountGenerationCandidatesRow struct {
	EmployeeID        pgtype.UUID `json:"employee_id"`
	Nip               string      `json:"nip"`
	Nama              string      `json:"nama"`
	TanggalLahir      pgtype.Date `json:"tanggal_lahir"`
	NomorUrut         int32       `json:"nomor_urut"`
	GeneratedUsername string      `json:"generated_username"`
	ExistingUserID    pgtype.UUID `json:"existing_user_id"`
	UsernameUserID    pgtype.UUID `json:"username_user_id"`
}

func (q *Queries) ListEmployeeAccountGenerationCandidates(ctx context.Context, npsn string) ([]ListEmployeeAccountGenerationCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listEmployeeAccountGenerationCandidates, npsn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeeAccountGenerationCandidatesRow{}
	for rows.Next() {
		var i ListEmployeeAccountGenerationCandidatesRow
		if err := rows.Scan(
			&i.EmployeeID,
			&i.Nip,
			&i.Nama,
			&i.TanggalLahir,
			&i.NomorUrut,
			&i.GeneratedUsername,
			&i.ExistingUserID,
			&i.UsernameUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeeProfileCandidates = `-- name: ListEmployeeProfileCandidates :many
SELECT
    e.id,
    e.nama,
    COALESCE(NULLIF(e.nip, ''), e.pegawai_uid, '')::text AS identifier,
    linked.id AS linked_user_id,
    COALESCE(linked.username, '')::text AS linked_username
FROM employees e
LEFT JOIN LATERAL (
    SELECT u.id, u.username
    FROM users u
    WHERE u.employee_id = e.id
      AND u.deleted_at IS NULL
    ORDER BY u.created_at DESC, u.id DESC
    LIMIT 1
) linked ON TRUE
WHERE e.is_active = TRUE
  AND ($1::boolean OR linked.id IS NULL)
  AND (
    btrim($2::text) = ''
    OR e.nama ILIKE ('%' || btrim($2::text) || '%')
    OR COALESCE(e.nip, '') ILIKE ('%' || btrim($2::text) || '%')
    OR COALESCE(e.pegawai_uid, '') ILIKE ('%' || btrim($2::text) || '%')
  )
ORDER BY e.nama ASC, e.id ASC
LIMIT $3::int
`

type ListEmployeeProfileCandidatesParams struct {
	IncludeLinked bool   `json:"include_linked"`
	Q             string `json:"q"`
	LimitCount    int32  `json:"limit_count"`
}

type ListEmployeeProfileCandidatesRow struct {
	ID             pgtype.UUID `json:"id"`
	Nama           string      `json:"nama"`
	Identifier     string      `json:"identifier"`
	LinkedUserID   pgtype.UUID `json:"linked_user_id"`
	LinkedUsername string      `json:"linked_username"`
}

func (q *Queries) ListEmployeeProfileCandidates(ctx context.Context, arg ListEmployeeProfileCandidatesParams) ([]ListEmployeeProfileCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listEmployeeProfileCandidates, arg.IncludeLinked, arg.Q, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeeProfileCandidatesRow{}
	for rows.Next() {
		var i ListEmployeeProfileCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.Identifier,
			&i.LinkedUserID,
			&i.LinkedUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntityAuditLogs = `-- name: ListEntityAuditLogs :many
SELECT
    a.id,
    a.user_id,
    u.username,
    COALESCE(NULLIF(btrim(u.display_name), ''), ue.nama, us.nama, up.nama, u.username, '')::text AS user_display_name,
    a.action,
    a.entity_type,
    a.entity_id,
    a.metadata,
    a.created_at
FROM audit_logs a
LEFT JOIN users u ON u.id = a.user_id
LEFT JOIN employees ue ON ue.id = u.employee_id
LEFT JOIN students us ON us.id = u.student_id
LEFT JOIN parents up ON up.id = u.parent_id
WHERE (
    a.entity_type = $1
    AND a.entity_id = $2
  )
  OR (
    $1 = 'cbt_session'
    AND a.entity_type = 'cbt_session_room'
    AND a.metadata->>'session_id' = $2
  )
ORDER BY a.created_at DESC
LIMIT $3 OFFSET $4
`

type ListEntityAuditLogsParams struct {
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

type ListEntityAuditLogsRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Username        pgtype.Text        `json:"username"`
	UserDisplayName string             `json:"user_display_name"`
	Action          string             `json:"action"`
	EntityType      string             `json:"entity_type"`
	EntityID        string             `json:"entity_id"`
	Metadata        []byte             `json:"metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListEntityAuditLogs(ctx context.Context, arg ListEntityAuditLogsParams) ([]ListEntityAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listEntityAuditLogs,
		arg.EntityType,
		arg.EntityID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEntityAuditLogsRow{}
	for rows.Next() {
		var i ListEntityAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.UserDisplayName,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnAccountChangeHistory = `-- name: ListOwnAccountChangeHistory :many
WITH relevant_audit AS (
    SELECT a.id, a.user_id, a.action, a.entity_type, a.entity_id, a.metadata, a.created_at
    FROM audit_logs a
    LEFT JOIN profile_change_requests pcr
        ON pcr.id::text = COALESCE(NULLIF(a.metadata->>'request_id', ''), a.entity_id)
    WHERE a.action IN (
        'AUTH_ACCOUNT_CONTACT_UPDATE',
        'AUTH_ACCOUNT_AVATAR_UPDATE',
        'AUTH_ACCOUNT_AVATAR_DELETE',
        'ACCOUNT_CHANGE_REQUEST_CREATED',
        'ACCOUNT_CHANGE_REQUEST_CANCELLED',
        'ACCOUNT_CHANGE_REQUEST_APPROVED',
        'ACCOUNT_CHANGE_REQUEST_REJECTED'
    )
      AND (
        (
            a.action IN (
                'AUTH_ACCOUNT_CONTACT_UPDATE',
                'AUTH_ACCOUNT_AVATAR_UPDATE',
                'AUTH_ACCOUNT_AVATAR_DELETE'
            )
            AND a.user_id = $2
        )
        OR (
            a.action IN (
                'ACCOUNT_CHANGE_REQUEST_CREATED',
                'ACCOUNT_CHANGE_REQUEST_CANCELLED',
                'ACCOUNT_CHANGE_REQUEST_APPROVED',
                'ACCOUNT_CHANGE_REQUEST_REJECTED'
            )
            AND (
                a.metadata->>'requester_user_id' = $2::text
                OR pcr.requester_user_id = $2
            )
        )
      )
)
SELECT
    a.action,
    CASE
        WHEN a.action = 'AUTH_ACCOUNT_CONTACT_UPDATE' THEN 'contact'
        WHEN a.action IN ('AUTH_ACCOUNT_AVATAR_UPDATE', 'AUTH_ACCOUNT_AVATAR_DELETE') THEN 'avatar'
        ELSE COALESCE(NULLIF(a.metadata->>'field_key', ''), pcr.field_key, '')
    END::text AS field_key,
    CASE
        WHEN a.action = 'ACCOUNT_CHANGE_REQUEST_CREATED' THEN 'pending'
        WHEN a.action = 'ACCOUNT_CHANGE_REQUEST_CANCELLED' THEN 'cancelled'
        WHEN a.action = 'ACCOUNT_CHANGE_REQUEST_APPROVED' THEN 'approved'
        WHEN a.action = 'ACCOUNT_CHANGE_REQUEST_REJECTED' THEN 'rejected'
        ELSE 'completed'
    END::text AS status,
    a.created_at,
    CASE
        WHEN a.action IN ('ACCOUNT_CHANGE_REQUEST_APPROVED', 'ACCOUNT_CHANGE_REQUEST_REJECTED') THEN COALESCE(reviewer.username, '')
        ELSE ''
    END::text AS reviewer_username,
    CASE
        WHEN a.action IN ('ACCOUNT_CHANGE_REQUEST_APPROVED', 'ACCOUNT_CHANGE_REQUEST_REJECTED')
            THEN COALESCE(NULLIF(btrim(reviewer.display_name), ''), reviewer_emp.nama, reviewer_student.nama, reviewer_parent.nama, reviewer.username, '')
        ELSE ''
    END::text AS reviewer_display_name,
    CASE
        WHEN a.action IN ('ACCOUNT_CHANGE_REQUEST_APPROVED', 'ACCOUNT_CHANGE_REQUEST_REJECTED') THEN COALESCE(pcr.review_note, '')
        ELSE ''
    END::text AS review_note
FROM relevant_audit a
LEFT JOIN profile_change_requests pcr
    ON pcr.id::text = COALESCE(NULLIF(a.metadata->>'request_id', ''), a.entity_id)
LEFT JOIN users reviewer
    ON reviewer.id = a.user_id
   AND a.action IN ('ACCOUNT_CHANGE_REQUEST_APPROVED', 'ACCOUNT_CHANGE_REQUEST_REJECTED')
LEFT JOIN employees reviewer_emp ON reviewer_emp.id = reviewer.employee_id
LEFT JOIN students reviewer_student ON reviewer_student.id = reviewer.student_id
LEFT JOIN parents reviewer_parent ON reviewer_parent.id = reviewer.parent_id
ORDER BY a.created_at DESC
LIMIT $1::int
`

type ListOwnAccountChangeHistoryParams struct {
	LimitCount int32       `json:"limit_count"`
	UserID     pgtype.UUID `json:"user_id"`
}

type ListOwnAccountChangeHistoryRow struct {
	Action              string             `json:"action"`
	FieldKey            string             `json:"field_key"`
	Status              string             `json:"status"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	ReviewerUsername    string             `json:"reviewer_username"`
	ReviewerDisplayName string             `json:"reviewer_display_name"`
	ReviewNote          string             `json:"review_note"`
}

func (q *Queries) ListOwnAccountChangeHistory(ctx context.Context, arg ListOwnAccountChangeHistoryParams) ([]ListOwnAccountChangeHistoryRow, error) {
	rows, err := q.db.Query(ctx, listOwnAccountChangeHistory, arg.LimitCount, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOwnAccountChangeHistoryRow{}
	for rows.Next() {
		var i ListOwnAccountChangeHistoryRow
		if err := rows.Scan(
			&i.Action,
			&i.FieldKey,
			&i.Status,
			&i.CreatedAt,
			&i.ReviewerUsername,
			&i.ReviewerDisplayName,
			&i.ReviewNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParentAccountGenerationCandidates = `-- name: ListParentAccountGenerationCandidates :many
WITH child_counts AS (
    SELECT
        ps.parent_id,
        count(*)::int AS child_count
    FROM parent_students ps
    GROUP BY ps.parent_id
), basis_children AS (
    SELECT DISTINCT ON (ps.parent_id)
        ps.parent_id,
        s.id AS basis_student_id,
        COALESCE(s.nisn, '')::text AS basis_student_nisn
    FROM parent_students ps
    JOIN students s ON s.id = ps.student_id
    ORDER BY
        ps.parent_id,
        ps.is_primary_contact DESC,
        CASE WHEN btrim(COALESCE(s.nisn, '')) <> '' THEN 0 ELSE 1 END,
        s.nama ASC,
        s.id ASC
), parent_candidates AS (
    SELECT
        p.id AS parent_id,
        p.nama,
        COALESCE(p.phone, '')::text AS phone,
        COALESCE(child_counts.child_count, 0)::int AS child_count,
        basis_children.basis_student_id,
        COALESCE(basis_children.basis_student_nisn, '')::text AS basis_student_nisn,
        regexp_replace(COALESCE(p.phone, ''), '\D', '', 'g')::text AS phone_digits
    FROM parents p
    LEFT JOIN child_counts ON child_counts.parent_id = p.id
    LEFT JOIN basis_children ON basis_children.parent_id = p.id
), linked_parents AS (
    SELECT
        parent_candidates.parent_id, parent_candidates.nama, parent_candidates.phone, parent_candidates.child_count, parent_candidates.basis_student_id, parent_candidates.basis_student_nisn, parent_candidates.phone_digits,
        CASE
            WHEN btrim(parent_candidates.basis_student_nisn) <> '' THEN ('ortu' || btrim(parent_candidates.basis_student_nisn))::text
            WHEN parent_candidates.phone_digits <> '' THEN ('ortu' || right(parent_candidates.phone_digits, 8))::text
            ELSE ''::text
        END AS base_username,
        linked.id AS existing_user_id,
        COALESCE(linked.username, '')::text AS existing_username
    FROM parent_candidates
    LEFT JOIN users linked
        ON linked.parent_id = parent_candidates.parent_id
       AND linked.deleted_at IS NULL
)
SELECT
    linked_parents.parent_id,
    linked_parents.nama,
    linked_parents.phone,
    linked_parents.child_count,
    linked_parents.basis_student_id,
    linked_parents.basis_student_nisn,
    linked_parents.base_username,
    linked_parents.existing_user_id,
    linked_parents.existing_username,
    username_user.id AS username_user_id,
    ARRAY(
        SELECT u.username
        FROM users u
        WHERE linked_parents.base_username <> ''
          AND u.deleted_at IS NULL
          AND (
            u.username = linked_parents.base_username
            OR u.username LIKE linked_parents.base_username || '-__'
          )
        ORDER BY u.username ASC
    )::text[] AS username_collisions
FROM linked_parents
LEFT JOIN users username_user
    ON username_user.username = linked_parents.base_username
   AND linked_parents.base_username <> ''
   AND username_user.deleted_at IS NULL
ORDER BY linked_parents.nama ASC, linked_parents.parent_id ASC
`

type ListParentAccountGenerationCandidatesRow struct {
	ParentID           pgtype.UUID `json:"parent_id"`
	Nama               string      `json:"nama"`
	Phone              string      `json:"phone"`
	ChildCount         int32       `json:"child_count"`
	BasisStudentID     pgtype.UUID `json:"basis_student_id"`
	BasisStudentNisn   string      `json:"basis_student_nisn"`
	BaseUsername       string      `json:"base_username"`
	ExistingUserID     pgtype.UUID `json:"existing_user_id"`
	ExistingUsername   string      `json:"existing_username"`
	UsernameUserID     pgtype.UUID `json:"username_user_id"`
	UsernameCollisions []string    `json:"username_collisions"`
}

func (q *Queries) ListParentAccountGenerationCandidates(ctx context.Context) ([]ListParentAccountGenerationCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listParentAccountGenerationCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListParentAccountGenerationCandidatesRow{}
	for rows.Next() {
		var i ListParentAccountGenerationCandidatesRow
		if err := rows.Scan(
			&i.ParentID,
			&i.Nama,
			&i.Phone,
			&i.ChildCount,
			&i.BasisStudentID,
			&i.BasisStudentNisn,
			&i.BaseUsername,
			&i.ExistingUserID,
			&i.ExistingUsername,
			&i.UsernameUserID,
			&i.UsernameCollisions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParentProfileCandidatesByChildClass = `-- name: ListParentProfileCandidatesByChildClass :many
WITH matching_parents AS (
    SELECT
        p.id,
        p.nama,
        COALESCE(p.phone, '')::text AS identifier,
        linked.id AS linked_user_id,
        COALESCE(linked.username, '')::text AS linked_username
    FROM parents p
    JOIN parent_students ps
        ON ps.parent_id = p.id
    JOIN students s
        ON s.id = ps.student_id
    LEFT JOIN LATERAL (
        SELECT u.id, u.username
        FROM users u
        WHERE u.parent_id = p.id
          AND u.deleted_at IS NULL
        ORDER BY u.created_at DESC, u.id DESC
        LIMIT 1
    ) linked ON TRUE
    WHERE s.is_active = TRUE
      AND s.status = 'active'
      AND s.class_id = $1
      AND ($2::boolean OR linked.id IS NULL)
      AND (
        btrim($3::text) = ''
        OR p.nama ILIKE ('%' || btrim($3::text) || '%')
        OR COALESCE(p.phone, '') ILIKE ('%' || btrim($3::text) || '%')
        OR s.nama ILIKE ('%' || btrim($3::text) || '%')
        OR s.nis ILIKE ('%' || btrim($3::text) || '%')
        OR COALESCE(s.nisn, '') ILIKE ('%' || btrim($3::text) || '%')
      )
    GROUP BY p.id, p.nama, p.phone, linked.id, linked.username
    ORDER BY p.nama ASC, p.id ASC
    LIMIT $4::int
)
SELECT
    mp.id,
    mp.nama,
    mp.identifier,
    s.class_id AS class_id,
    COALESCE(NULLIF(c.name, ''), c.code, '')::text AS class_name,
    mp.linked_user_id,
    mp.linked_username,
    s.id AS child_id,
    s.nama AS child_nama
FROM matching_parents mp
JOIN parent_students ps
    ON ps.parent_id = mp.id
JOIN students s
    ON s.id = ps.student_id
JOIN school_classes c
    ON c.id = s.class_id
WHERE s.is_active = TRUE
  AND s.status = 'active'
  AND s.class_id = $1
ORDER BY mp.nama ASC, mp.id ASC, ps.is_primary_contact DESC, s.nama ASC, s.id ASC
`

type ListParentProfileCandidatesByChildClassParams struct {
	ClassID       pgtype.UUID `json:"class_id"`
	IncludeLinked bool        `json:"include_linked"`
	Q             string      `json:"q"`
	LimitCount    int32       `json:"limit_count"`
}

type ListParentProfileCandidatesByChildClassRow struct {
	ID             pgtype.UUID `json:"id"`
	Nama           string      `json:"nama"`
	Identifier     string      `json:"identifier"`
	ClassID        pgtype.UUID `json:"class_id"`
	ClassName      string      `json:"class_name"`
	LinkedUserID   pgtype.UUID `json:"linked_user_id"`
	LinkedUsername string      `json:"linked_username"`
	ChildID        pgtype.UUID `json:"child_id"`
	ChildNama      string      `json:"child_nama"`
}

func (q *Queries) ListParentProfileCandidatesByChildClass(ctx context.Context, arg ListParentProfileCandidatesByChildClassParams) ([]ListParentProfileCandidatesByChildClassRow, error) {
	rows, err := q.db.Query(ctx, listParentProfileCandidatesByChildClass,
		arg.ClassID,
		arg.IncludeLinked,
		arg.Q,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListParentProfileCandidatesByChildClassRow{}
	for rows.Next() {
		var i ListParentProfileCandidatesByChildClassRow
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.Identifier,
			&i.ClassID,
			&i.ClassName,
			&i.LinkedUserID,
			&i.LinkedUsername,
			&i.ChildID,
			&i.ChildNama,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentAccountGenerationCandidates = `-- name: ListStudentAccountGenerationCandidates :many
WITH active_students AS (
    SELECT
        s.id AS student_id,
        COALESCE(s.nis, '')::text AS nis,
        COALESCE(s.nisn, '')::text AS nisn,
        s.nama,
        CASE
            WHEN btrim(COALESCE(s.nisn, '')) <> '' THEN btrim(s.nisn)
            WHEN btrim(COALESCE(s.nis, '')) <> '' THEN ('s' || btrim(s.nis))::text
            ELSE ''::text
        END AS base_username
    FROM students s
    WHERE s.is_active = TRUE
), linked_students AS (
    SELECT
        active_students.student_id, active_students.nis, active_students.nisn, active_students.nama, active_students.base_username,
        linked.id AS existing_user_id,
        COALESCE(linked.username, '')::text AS existing_username
    FROM active_students
    LEFT JOIN users linked
        ON linked.student_id = active_students.student_id
       AND linked.deleted_at IS NULL
)
SELECT
    linked_students.student_id,
    linked_students.nis,
    linked_students.nisn,
    linked_students.nama,
    linked_students.base_username,
    linked_students.existing_user_id,
    linked_students.existing_username,
    username_user.id AS username_user_id,
    ARRAY(
        SELECT u.username
        FROM users u
        WHERE linked_students.base_username <> ''
          AND u.deleted_at IS NULL
          AND (
            u.username = linked_students.base_username
            OR u.username LIKE linked_students.base_username || '-__'
          )
        ORDER BY u.username ASC
    )::text[] AS username_collisions
FROM linked_students
LEFT JOIN users username_user
    ON username_user.username = linked_students.base_username
   AND linked_students.base_username <> ''
   AND username_user.deleted_at IS NULL
ORDER BY linked_students.nama ASC, linked_students.student_id ASC
`

type ListStudentAccountGenerationCandidatesRow struct {
	StudentID          pgtype.UUID `json:"student_id"`
	Nis                string      `json:"nis"`
	Nisn               string      `json:"nisn"`
	Nama               string      `json:"nama"`
	BaseUsername       string      `json:"base_username"`
	ExistingUserID     pgtype.UUID `json:"existing_user_id"`
	ExistingUsername   string      `json:"existing_username"`
	UsernameUserID     pgtype.UUID `json:"username_user_id"`
	UsernameCollisions []string    `json:"username_collisions"`
}

func (q *Queries) ListStudentAccountGenerationCandidates(ctx context.Context) ([]ListStudentAccountGenerationCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listStudentAccountGenerationCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentAccountGenerationCandidatesRow{}
	for rows.Next() {
		var i ListStudentAccountGenerationCandidatesRow
		if err := rows.Scan(
			&i.StudentID,
			&i.Nis,
			&i.Nisn,
			&i.Nama,
			&i.BaseUsername,
			&i.ExistingUserID,
			&i.ExistingUsername,
			&i.UsernameUserID,
			&i.UsernameCollisions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentProfileCandidatesByClass = `-- name: ListStudentProfileCandidatesByClass :many
SELECT
    s.id,
    s.nama,
    COALESCE(NULLIF(s.nisn, ''), s.nis, '')::text AS identifier,
    s.class_id AS class_id,
    COALESCE(NULLIF(c.name, ''), c.code, '')::text AS class_name,
    linked.id AS linked_user_id,
    COALESCE(linked.username, '')::text AS linked_username
FROM students s
JOIN school_classes c
    ON c.id = s.class_id
LEFT JOIN LATERAL (
    SELECT u.id, u.username
    FROM users u
    WHERE u.student_id = s.id
      AND u.deleted_at IS NULL
    ORDER BY u.created_at DESC, u.id DESC
    LIMIT 1
) linked ON TRUE
WHERE s.is_active = TRUE
  AND s.status = 'active'
  AND s.class_id = $1
  AND ($2::boolean OR linked.id IS NULL)
  AND (
    btrim($3::text) = ''
    OR s.nama ILIKE ('%' || btrim($3::text) || '%')
    OR s.nis ILIKE ('%' || btrim($3::text) || '%')
    OR COALESCE(s.nisn, '') ILIKE ('%' || btrim($3::text) || '%')
  )
ORDER BY s.nama ASC, s.id ASC
LIMIT $4::int
`

type ListStudentProfileCandidatesByClassParams struct {
	ClassID       pgtype.UUID `json:"class_id"`
	IncludeLinked bool        `json:"include_linked"`
	Q             string      `json:"q"`
	LimitCount    int32       `json:"limit_count"`
}

type ListStudentProfileCandidatesByClassRow struct {
	ID             pgtype.UUID `json:"id"`
	Nama           string      `json:"nama"`
	Identifier     string      `json:"identifier"`
	ClassID        pgtype.UUID `json:"class_id"`
	ClassName      string      `json:"class_name"`
	LinkedUserID   pgtype.UUID `json:"linked_user_id"`
	LinkedUsername string      `json:"linked_username"`
}

func (q *Queries) ListStudentProfileCandidatesByClass(ctx context.Context, arg ListStudentProfileCandidatesByClassParams) ([]ListStudentProfileCandidatesByClassRow, error) {
	rows, err := q.db.Query(ctx, listStudentProfileCandidatesByClass,
		arg.ClassID,
		arg.IncludeLinked,
		arg.Q,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentProfileCandidatesByClassRow{}
	for rows.Next() {
		var i ListStudentProfileCandidatesByClassRow
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.Identifier,
			&i.ClassID,
			&i.ClassName,
			&i.LinkedUserID,
			&i.LinkedUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT 
    u.id, u.username,
    COALESCE(NULLIF(u.display_name, ''), e.nama, s.nama, p.nama, u.username) AS display_name,
    u.employee_id, u.student_id, u.parent_id,
    COALESCE(e.nama, s.nama, p.nama, '') AS profile_nama,
    u.is_active, u.must_change_password, u.password_changed_at, u.last_login_at, u.deleted_at, u.created_at,
    COALESCE(
      (
        SELECT json_agg(r.code ORDER BY r.code)
        FROM rbac_user_roles ur
        JOIN rbac_roles r ON r.id = ur.role_id
        WHERE ur.user_id = u.id
          AND r.is_active = TRUE
      ),
      (SELECT json_agg(role) FROM user_account_roles WHERE user_id = u.id),
      '[]'::json
    ) as roles
FROM users u
LEFT JOIN employees e ON e.id = u.employee_id
LEFT JOIN students s ON s.id = u.student_id
LEFT JOIN parents p ON p.id = u.parent_id
WHERE u.deleted_at IS NULL
ORDER BY u.username ASC
`

type ListUsersRow struct {
	ID                 pgtype.UUID        `json:"id"`
	Username           string             `json:"username"`
	DisplayName        string             `json:"display_name"`
	EmployeeID         pgtype.UUID        `json:"employee_id"`
	StudentID          pgtype.UUID        `json:"student_id"`
	ParentID           pgtype.UUID        `json:"parent_id"`
	ProfileNama        string             `json:"profile_nama"`
	IsActive           bool               `json:"is_active"`
	MustChangePassword bool               `json:"must_change_password"`
	PasswordChangedAt  pgtype.Timestamptz `json:"password_changed_at"`
	LastLoginAt        pgtype.Timestamptz `json:"last_login_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	Roles              interface{}        `json:"roles"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.EmployeeID,
			&i.StudentID,
			&i.ParentID,
			&i.ProfileNama,
			&i.IsActive,
			&i.MustChangePassword,
			&i.PasswordChangedAt,
			&i.LastLoginAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.Roles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByEmployeeID = `-- name: ListUsersByEmployeeID :many
SELECT id, username, password_hash, display_name, employee_id, created_at, updated_at, student_id, parent_id, is_active, auth_version, must_change_password, password_changed_at, last_login_at, deleted_at
FROM users
WHERE employee_id = $1
  AND deleted_at IS NULL
ORDER BY created_at ASC
`

type ListUsersByEmployeeIDRow struct {
	ID                 pgtype.UUID        `json:"id"`
	Username           string             `json:"username"`
	PasswordHash       string             `json:"password_hash"`
	DisplayName        pgtype.Text        `json:"display_name"`
	EmployeeID         pgtype.UUID        `json:"employee_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	StudentID          pgtype.UUID        `json:"student_id"`
	ParentID           pgtype.UUID        `json:"parent_id"`
	IsActive           bool               `json:"is_active"`
	AuthVersion        int32              `json:"auth_version"`
	MustChangePassword bool               `json:"must_change_password"`
	PasswordChangedAt  pgtype.Timestamptz `json:"password_changed_at"`
	LastLoginAt        pgtype.Timestamptz `json:"last_login_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ListUsersByEmployeeID(ctx context.Context, employeeID pgtype.UUID) ([]ListUsersByEmployeeIDRow, error) {
	rows, err := q.db.Query(ctx, listUsersByEmployeeID, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersByEmployeeIDRow{}
	for rows.Next() {
		var i ListUsersByEmployeeIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.DisplayName,
			&i.EmployeeID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StudentID,
			&i.ParentID,
			&i.IsActive,
			&i.AuthVersion,
			&i.MustChangePassword,
			&i.PasswordChangedAt,
			&i.LastLoginAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByStudentID = `-- name: ListUsersByStudentID :many
SELECT id, username, password_hash, display_name, employee_id, created_at, updated_at, student_id, parent_id, is_active, auth_version, must_change_password, password_changed_at, last_login_at, deleted_at
FROM users
WHERE student_id = $1
  AND deleted_at IS NULL
ORDER BY created_at ASC
`

type ListUsersByStudentIDRow struct {
	ID                 pgtype.UUID        `json:"id"`
	Username           string             `json:"username"`
	PasswordHash       string             `json:"password_hash"`
	DisplayName        pgtype.Text        `json:"display_name"`
	EmployeeID         pgtype.UUID        `json:"employee_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	StudentID          pgtype.UUID        `json:"student_id"`
	ParentID           pgtype.UUID        `json:"parent_id"`
	IsActive           bool               `json:"is_active"`
	AuthVersion        int32              `json:"auth_version"`
	MustChangePassword bool               `json:"must_change_password"`
	PasswordChangedAt  pgtype.Timestamptz `json:"password_changed_at"`
	LastLoginAt        pgtype.Timestamptz `json:"last_login_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ListUsersByStudentID(ctx context.Context, studentID pgtype.UUID) ([]ListUsersByStudentIDRow, error) {
	rows, err := q.db.Query(ctx, listUsersByStudentID, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersByStudentIDRow{}
	for rows.Next() {
		var i ListUsersByStudentIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.DisplayName,
			&i.EmployeeID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StudentID,
			&i.ParentID,
			&i.IsActive,
			&i.AuthVersion,
			&i.MustChangePassword,
			&i.PasswordChangedAt,
			&i.LastLoginAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUserLastLogin = `-- name: MarkUserLastLogin :exec
UPDATE users
SET last_login_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) MarkUserLastLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markUserLastLogin, id)
	return err
}

const markUserMustChangePassword = `-- name: MarkUserMustChangePassword :exec
UPDATE users
SET must_change_password = TRUE,
    password_changed_at = NULL,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) MarkUserMustChangePassword(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markUserMustChangePassword, id)
	return err
}

const markUserPasswordChanged = `-- name: MarkUserPasswordChanged :exec
UPDATE users
SET must_change_password = FALSE,
    password_changed_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) MarkUserPasswordChanged(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markUserPasswordChanged, id)
	return err
}

const removeAllUserRoles = `-- name: RemoveAllUserRoles :exec
DELETE FROM user_account_roles WHERE user_id = $1
`

func (q *Queries) RemoveAllUserRoles(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeAllUserRoles, userID)
	return err
}

const removeUserRole = `-- name: RemoveUserRole :exec
DELETE FROM user_account_roles WHERE user_id = $1 AND role = $2
`

type RemoveUserRoleParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Role   UserRole    `json:"role"`
}

func (q *Queries) RemoveUserRole(ctx context.Context, arg RemoveUserRoleParams) error {
	_, err := q.db.Exec(ctx, removeUserRole, arg.UserID, arg.Role)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET is_active = FALSE,
    deleted_at = COALESCE(deleted_at, NOW()),
    auth_version = auth_version + 1,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const syncLegacyUserRolesFromRbac = `-- name: SyncLegacyUserRolesFromRbac :exec
WITH legacy_roles AS (
  SELECT r.code::user_role AS role
  FROM rbac_user_roles ur
  JOIN rbac_roles r ON r.id = ur.role_id
  WHERE ur.user_id = $1
    AND r.code IN ('admin', 'guru', 'staf', 'kesiswaan', 'siswa', 'ortu')
)
INSERT INTO user_account_roles (user_id, role)
SELECT $1, role
FROM legacy_roles
ON CONFLICT DO NOTHING
`

func (q *Queries) SyncLegacyUserRolesFromRbac(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, syncLegacyUserRolesFromRbac, userID)
	return err
}

const updateOwnedEmployeeAvatar = `-- name: UpdateOwnedEmployeeAvatar :one
UPDATE employees e
SET photo_url = $1,
    updated_at = NOW()
WHERE e.id = (
    SELECT u.employee_id
    FROM users u
    WHERE u.id = $2
      AND u.deleted_at IS NULL
      AND u.employee_id IS NOT NULL
)
RETURNING e.photo_url
`

type UpdateOwnedEmployeeAvatarParams struct {
	PhotoUrl string      `json:"photo_url"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateOwnedEmployeeAvatar(ctx context.Context, arg UpdateOwnedEmployeeAvatarParams) (string, error) {
	row := q.db.QueryRow(ctx, updateOwnedEmployeeAvatar, arg.PhotoUrl, arg.UserID)
	var photo_url string
	err := row.Scan(&photo_url)
	return photo_url, err
}

const updateOwnedEmployeeContact = `-- name: UpdateOwnedEmployeeContact :one
UPDATE employees e
SET phone = $1,
    email = $2,
    address = $3,
    updated_at = NOW()
WHERE e.id = (
    SELECT u.employee_id
    FROM users u
    WHERE u.id = $4
      AND u.deleted_at IS NULL
      AND u.employee_id IS NOT NULL
)
RETURNING e.phone AS contact_phone, e.email AS contact_email, e.address AS contact_address
`

type UpdateOwnedEmployeeContactParams struct {
	Phone   string      `json:"phone"`
	Email   string      `json:"email"`
	Address string      `json:"address"`
	UserID  pgtype.UUID `json:"user_id"`
}

type UpdateOwnedEmployeeContactRow struct {
	ContactPhone   string `json:"contact_phone"`
	ContactEmail   string `json:"contact_email"`
	ContactAddress string `json:"contact_address"`
}

func (q *Queries) UpdateOwnedEmployeeContact(ctx context.Context, arg UpdateOwnedEmployeeContactParams) (UpdateOwnedEmployeeContactRow, error) {
	row := q.db.QueryRow(ctx, updateOwnedEmployeeContact,
		arg.Phone,
		arg.Email,
		arg.Address,
		arg.UserID,
	)
	var i UpdateOwnedEmployeeContactRow
	err := row.Scan(&i.ContactPhone, &i.ContactEmail, &i.ContactAddress)
	return i, err
}

const updateOwnedParentAvatar = `-- name: UpdateOwnedParentAvatar :one
UPDATE parents p
SET photo_url = $1,
    updated_at = NOW()
WHERE p.id = (
    SELECT u.parent_id
    FROM users u
    WHERE u.id = $2
      AND u.deleted_at IS NULL
      AND u.parent_id IS NOT NULL
)
RETURNING p.photo_url
`

type UpdateOwnedParentAvatarParams struct {
	PhotoUrl string      `json:"photo_url"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateOwnedParentAvatar(ctx context.Context, arg UpdateOwnedParentAvatarParams) (string, error) {
	row := q.db.QueryRow(ctx, updateOwnedParentAvatar, arg.PhotoUrl, arg.UserID)
	var photo_url string
	err := row.Scan(&photo_url)
	return photo_url, err
}

const updateOwnedParentContact = `-- name: UpdateOwnedParentContact :one
UPDATE parents p
SET phone = $1,
    address = $2,
    updated_at = NOW()
WHERE p.id = (
    SELECT u.parent_id
    FROM users u
    WHERE u.id = $3
      AND u.deleted_at IS NULL
      AND u.parent_id IS NOT NULL
)
RETURNING p.phone AS contact_phone, ''::text AS contact_email, p.address AS contact_address
`

type UpdateOwnedParentContactParams struct {
	Phone   string      `json:"phone"`
	Address string      `json:"address"`
	UserID  pgtype.UUID `json:"user_id"`
}

type UpdateOwnedParentContactRow struct {
	ContactPhone   string `json:"contact_phone"`
	ContactEmail   string `json:"contact_email"`
	ContactAddress string `json:"contact_address"`
}

func (q *Queries) UpdateOwnedParentContact(ctx context.Context, arg UpdateOwnedParentContactParams) (UpdateOwnedParentContactRow, error) {
	row := q.db.QueryRow(ctx, updateOwnedParentContact, arg.Phone, arg.Address, arg.UserID)
	var i UpdateOwnedParentContactRow
	err := row.Scan(&i.ContactPhone, &i.ContactEmail, &i.ContactAddress)
	return i, err
}

const updateOwnedStudentAvatar = `-- name: UpdateOwnedStudentAvatar :one
UPDATE students s
SET photo_url = $1,
    updated_at = NOW()
WHERE s.id = (
    SELECT u.student_id
    FROM users u
    WHERE u.id = $2
      AND u.deleted_at IS NULL
      AND u.student_id IS NOT NULL
)
RETURNING s.photo_url
`

type UpdateOwnedStudentAvatarParams struct {
	PhotoUrl string      `json:"photo_url"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateOwnedStudentAvatar(ctx context.Context, arg UpdateOwnedStudentAvatarParams) (string, error) {
	row := q.db.QueryRow(ctx, updateOwnedStudentAvatar, arg.PhotoUrl, arg.UserID)
	var photo_url string
	err := row.Scan(&photo_url)
	return photo_url, err
}

const updateOwnedStudentContact = `-- name: UpdateOwnedStudentContact :one
UPDATE students s
SET phone = $1,
    alamat = $2,
    updated_at = NOW()
WHERE s.id = (
    SELECT u.student_id
    FROM users u
    WHERE u.id = $3
      AND u.deleted_at IS NULL
      AND u.student_id IS NOT NULL
)
RETURNING s.phone AS contact_phone, ''::text AS contact_email, s.alamat AS contact_address
`

type UpdateOwnedStudentContactParams struct {
	Phone   string      `json:"phone"`
	Address string      `json:"address"`
	UserID  pgtype.UUID `json:"user_id"`
}

type UpdateOwnedStudentContactRow struct {
	ContactPhone   string `json:"contact_phone"`
	ContactEmail   string `json:"contact_email"`
	ContactAddress string `json:"contact_address"`
}

func (q *Queries) UpdateOwnedStudentContact(ctx context.Context, arg UpdateOwnedStudentContactParams) (UpdateOwnedStudentContactRow, error) {
	row := q.db.QueryRow(ctx, updateOwnedStudentContact, arg.Phone, arg.Address, arg.UserID)
	var i UpdateOwnedStudentContactRow
	err := row.Scan(&i.ContactPhone, &i.ContactEmail, &i.ContactAddress)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2, updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

type UpdateUserPasswordParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserProfileLink = `-- name: UpdateUserProfileLink :exec
UPDATE users
SET employee_id = $2,
    student_id = $3,
    parent_id = $4,
    display_name = COALESCE(NULLIF(display_name, ''), $5),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

type UpdateUserProfileLinkParams struct {
	ID          pgtype.UUID `json:"id"`
	EmployeeID  pgtype.UUID `json:"employee_id"`
	StudentID   pgtype.UUID `json:"student_id"`
	ParentID    pgtype.UUID `json:"parent_id"`
	DisplayName pgtype.Text `json:"display_name"`
}

func (q *Queries) UpdateUserProfileLink(ctx context.Context, arg UpdateUserProfileLinkParams) error {
	_, err := q.db.Exec(ctx, updateUserProfileLink,
		arg.ID,
		arg.EmployeeID,
		arg.StudentID,
		arg.ParentID,
		arg.DisplayName,
	)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE users
SET is_active = $2,
    deleted_at = CASE WHEN $2 = TRUE THEN NULL ELSE deleted_at END,
    auth_version = CASE WHEN is_active = TRUE AND $2 = FALSE THEN auth_version + 1 ELSE auth_version END,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

type UpdateUserStatusParams struct {
	ID       pgtype.UUID `json:"id"`
	IsActive bool        `json:"is_active"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.Exec(ctx, updateUserStatus, arg.ID, arg.IsActive)
	return err
}
