// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUserRole = `-- name: AddUserRole :exec
INSERT INTO user_account_roles (user_id, role) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddUserRoleParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Role   UserRole    `json:"role"`
}

func (q *Queries) AddUserRole(ctx context.Context, arg AddUserRoleParams) error {
	_, err := q.db.Exec(ctx, addUserRole, arg.UserID, arg.Role)
	return err
}

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (user_id, action, entity_type, entity_id, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, action, entity_type, entity_id, metadata, created_at
`

type CreateAuditLogParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	Action     string      `json:"action"`
	EntityType string      `json:"entity_type"`
	EntityID   string      `json:"entity_id"`
	Metadata   []byte      `json:"metadata"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.UserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Metadata,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash, employee_id, student_id, parent_id, is_active)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, username, employee_id, student_id, parent_id, is_active, auth_version, created_at, updated_at
`

type CreateUserParams struct {
	Username     string      `json:"username"`
	PasswordHash string      `json:"password_hash"`
	EmployeeID   pgtype.UUID `json:"employee_id"`
	StudentID    pgtype.UUID `json:"student_id"`
	ParentID     pgtype.UUID `json:"parent_id"`
	IsActive     bool        `json:"is_active"`
}

type CreateUserRow struct {
	ID          pgtype.UUID        `json:"id"`
	Username    string             `json:"username"`
	EmployeeID  pgtype.UUID        `json:"employee_id"`
	StudentID   pgtype.UUID        `json:"student_id"`
	ParentID    pgtype.UUID        `json:"parent_id"`
	IsActive    bool               `json:"is_active"`
	AuthVersion int32              `json:"auth_version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.PasswordHash,
		arg.EmployeeID,
		arg.StudentID,
		arg.ParentID,
		arg.IsActive,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.EmployeeID,
		&i.StudentID,
		&i.ParentID,
		&i.IsActive,
		&i.AuthVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOldAuditLogs = `-- name: DeleteOldAuditLogs :execrows
DELETE FROM audit_logs
WHERE created_at < NOW() - INTERVAL '90 days'
`

func (q *Queries) DeleteOldAuditLogs(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldAuditLogs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT 
    u.id, u.username, u.password_hash, 
    u.employee_id, u.student_id, u.parent_id,
    u.is_active, u.auth_version, u.created_at, u.updated_at,
    (SELECT json_agg(role) FROM user_account_roles WHERE user_id = u.id) as roles
FROM users u
WHERE u.id = $1
`

type GetUserByIDRow struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	EmployeeID   pgtype.UUID        `json:"employee_id"`
	StudentID    pgtype.UUID        `json:"student_id"`
	ParentID     pgtype.UUID        `json:"parent_id"`
	IsActive     bool               `json:"is_active"`
	AuthVersion  int32              `json:"auth_version"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Roles        []byte             `json:"roles"`
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.EmployeeID,
		&i.StudentID,
		&i.ParentID,
		&i.IsActive,
		&i.AuthVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Roles,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT 
    u.id, u.username, u.password_hash, 
    u.employee_id, u.student_id, u.parent_id,
    u.is_active, u.auth_version, u.created_at, u.updated_at,
    (SELECT json_agg(role) FROM user_account_roles WHERE user_id = u.id) as roles
FROM users u
WHERE u.username = $1
`

type GetUserByUsernameRow struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	EmployeeID   pgtype.UUID        `json:"employee_id"`
	StudentID    pgtype.UUID        `json:"student_id"`
	ParentID     pgtype.UUID        `json:"parent_id"`
	IsActive     bool               `json:"is_active"`
	AuthVersion  int32              `json:"auth_version"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Roles        []byte             `json:"roles"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.EmployeeID,
		&i.StudentID,
		&i.ParentID,
		&i.IsActive,
		&i.AuthVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Roles,
	)
	return i, err
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT role FROM user_account_roles WHERE user_id = $1
`

func (q *Queries) GetUserRoles(ctx context.Context, userID pgtype.UUID) ([]UserRole, error) {
	rows, err := q.db.Query(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserRole{}
	for rows.Next() {
		var role UserRole
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementUserAuthVersion = `-- name: IncrementUserAuthVersion :one
UPDATE users
SET auth_version = auth_version + 1,
    updated_at = NOW()
WHERE id = $1
RETURNING auth_version
`

func (q *Queries) IncrementUserAuthVersion(ctx context.Context, id pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementUserAuthVersion, id)
	var auth_version int32
	err := row.Scan(&auth_version)
	return auth_version, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT a.id, a.user_id, u.username, a.action, a.entity_type, a.entity_id, a.metadata, a.created_at
FROM audit_logs a
LEFT JOIN users u ON u.id = a.user_id
ORDER BY a.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAuditLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAuditLogsRow struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Username   pgtype.Text        `json:"username"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   string             `json:"entity_id"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsRow{}
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeeAccountGenerationCandidates = `-- name: ListEmployeeAccountGenerationCandidates :many
WITH active_employees AS (
    SELECT
        e.id,
        e.nip,
        e.nama,
        e.tanggal_lahir,
        row_number() OVER (ORDER BY e.nama ASC, e.id ASC)::int AS nomor_urut
    FROM employees e
    WHERE e.is_active = TRUE
), candidates AS (
    SELECT
        ae.id AS employee_id,
        ae.nip,
        ae.nama,
        ae.tanggal_lahir,
        ae.nomor_urut,
        CASE
            WHEN ae.tanggal_lahir IS NULL THEN ''::text
            ELSE ($1::text || to_char(ae.tanggal_lahir, 'DDMMYY') || lpad(ae.nomor_urut::text, 3, '0'))::text
        END AS generated_username,
        linked.id AS existing_user_id
    FROM active_employees ae
    LEFT JOIN users linked ON linked.employee_id = ae.id
)
SELECT
    c.employee_id,
    c.nip,
    c.nama,
    c.tanggal_lahir,
    c.nomor_urut,
    c.generated_username,
    c.existing_user_id,
    username_user.id AS username_user_id
FROM candidates c
LEFT JOIN users username_user ON username_user.username = c.generated_username AND c.generated_username <> ''
ORDER BY c.nomor_urut ASC
`

type ListEmployeeAccountGenerationCandidatesRow struct {
	EmployeeID        pgtype.UUID `json:"employee_id"`
	Nip               string      `json:"nip"`
	Nama              string      `json:"nama"`
	TanggalLahir      pgtype.Date `json:"tanggal_lahir"`
	NomorUrut         int32       `json:"nomor_urut"`
	GeneratedUsername string      `json:"generated_username"`
	ExistingUserID    pgtype.UUID `json:"existing_user_id"`
	UsernameUserID    pgtype.UUID `json:"username_user_id"`
}

func (q *Queries) ListEmployeeAccountGenerationCandidates(ctx context.Context, npsn string) ([]ListEmployeeAccountGenerationCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listEmployeeAccountGenerationCandidates, npsn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeeAccountGenerationCandidatesRow{}
	for rows.Next() {
		var i ListEmployeeAccountGenerationCandidatesRow
		if err := rows.Scan(
			&i.EmployeeID,
			&i.Nip,
			&i.Nama,
			&i.TanggalLahir,
			&i.NomorUrut,
			&i.GeneratedUsername,
			&i.ExistingUserID,
			&i.UsernameUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntityAuditLogs = `-- name: ListEntityAuditLogs :many
SELECT a.id, a.user_id, u.username, a.action, a.entity_type, a.entity_id, a.metadata, a.created_at
FROM audit_logs a
LEFT JOIN users u ON u.id = a.user_id
WHERE (
    a.entity_type = $1
    AND a.entity_id = $2
  )
  OR (
    $1 = 'cbt_session'
    AND a.entity_type = 'cbt_session_room'
    AND a.metadata->>'session_id' = $2
  )
ORDER BY a.created_at DESC
LIMIT $3 OFFSET $4
`

type ListEntityAuditLogsParams struct {
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

type ListEntityAuditLogsRow struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Username   pgtype.Text        `json:"username"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   string             `json:"entity_id"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListEntityAuditLogs(ctx context.Context, arg ListEntityAuditLogsParams) ([]ListEntityAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listEntityAuditLogs,
		arg.EntityType,
		arg.EntityID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEntityAuditLogsRow{}
	for rows.Next() {
		var i ListEntityAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT 
    u.id, u.username, u.employee_id, u.student_id, u.parent_id,
    COALESCE(e.nama, s.nama, p.nama, '') AS profile_nama,
    u.is_active, u.created_at,
    (SELECT json_agg(role) FROM user_account_roles WHERE user_id = u.id) as roles
FROM users u
LEFT JOIN employees e ON e.id = u.employee_id
LEFT JOIN students s ON s.id = u.student_id
LEFT JOIN parents p ON p.id = u.parent_id
ORDER BY u.username ASC
`

type ListUsersRow struct {
	ID          pgtype.UUID        `json:"id"`
	Username    string             `json:"username"`
	EmployeeID  pgtype.UUID        `json:"employee_id"`
	StudentID   pgtype.UUID        `json:"student_id"`
	ParentID    pgtype.UUID        `json:"parent_id"`
	ProfileNama string             `json:"profile_nama"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Roles       []byte             `json:"roles"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.EmployeeID,
			&i.StudentID,
			&i.ParentID,
			&i.ProfileNama,
			&i.IsActive,
			&i.CreatedAt,
			&i.Roles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByEmployeeID = `-- name: ListUsersByEmployeeID :many
SELECT id, username, password_hash, employee_id, created_at, updated_at, student_id, parent_id, is_active
FROM users
WHERE employee_id = $1
ORDER BY created_at ASC
`

type ListUsersByEmployeeIDRow struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	EmployeeID   pgtype.UUID        `json:"employee_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	StudentID    pgtype.UUID        `json:"student_id"`
	ParentID     pgtype.UUID        `json:"parent_id"`
	IsActive     bool               `json:"is_active"`
}

func (q *Queries) ListUsersByEmployeeID(ctx context.Context, employeeID pgtype.UUID) ([]ListUsersByEmployeeIDRow, error) {
	rows, err := q.db.Query(ctx, listUsersByEmployeeID, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersByEmployeeIDRow{}
	for rows.Next() {
		var i ListUsersByEmployeeIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.EmployeeID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StudentID,
			&i.ParentID,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByStudentID = `-- name: ListUsersByStudentID :many
SELECT id, username, password_hash, employee_id, created_at, updated_at, student_id, parent_id, is_active
FROM users
WHERE student_id = $1
ORDER BY created_at ASC
`

type ListUsersByStudentIDRow struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	EmployeeID   pgtype.UUID        `json:"employee_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	StudentID    pgtype.UUID        `json:"student_id"`
	ParentID     pgtype.UUID        `json:"parent_id"`
	IsActive     bool               `json:"is_active"`
}

func (q *Queries) ListUsersByStudentID(ctx context.Context, studentID pgtype.UUID) ([]ListUsersByStudentIDRow, error) {
	rows, err := q.db.Query(ctx, listUsersByStudentID, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersByStudentIDRow{}
	for rows.Next() {
		var i ListUsersByStudentIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.EmployeeID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StudentID,
			&i.ParentID,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllUserRoles = `-- name: RemoveAllUserRoles :exec
DELETE FROM user_account_roles WHERE user_id = $1
`

func (q *Queries) RemoveAllUserRoles(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeAllUserRoles, userID)
	return err
}

const removeUserRole = `-- name: RemoveUserRole :exec
DELETE FROM user_account_roles WHERE user_id = $1 AND role = $2
`

type RemoveUserRoleParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Role   UserRole    `json:"role"`
}

func (q *Queries) RemoveUserRole(ctx context.Context, arg RemoveUserRoleParams) error {
	_, err := q.db.Exec(ctx, removeUserRole, arg.UserID, arg.Role)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserProfileLink = `-- name: UpdateUserProfileLink :exec
UPDATE users
SET employee_id = $2,
    student_id = $3,
    parent_id = $4,
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserProfileLinkParams struct {
	ID         pgtype.UUID `json:"id"`
	EmployeeID pgtype.UUID `json:"employee_id"`
	StudentID  pgtype.UUID `json:"student_id"`
	ParentID   pgtype.UUID `json:"parent_id"`
}

func (q *Queries) UpdateUserProfileLink(ctx context.Context, arg UpdateUserProfileLinkParams) error {
	_, err := q.db.Exec(ctx, updateUserProfileLink,
		arg.ID,
		arg.EmployeeID,
		arg.StudentID,
		arg.ParentID,
	)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE users
SET is_active = $2,
    auth_version = CASE WHEN is_active = TRUE AND $2 = FALSE THEN auth_version + 1 ELSE auth_version END,
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserStatusParams struct {
	ID       pgtype.UUID `json:"id"`
	IsActive bool        `json:"is_active"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.Exec(ctx, updateUserStatus, arg.ID, arg.IsActive)
	return err
}
