ALTER TABLE auth_sessions
ADD COLUMN IF NOT EXISTS ip_address TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS user_agent TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS device_label TEXT NOT NULL DEFAULT '';
