ALTER TABLE subjects
  ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT 'intrakurikuler',
  ADD COLUMN IF NOT EXISTS is_assessment_subject BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS is_report_subject BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS is_schedule_activity BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS default_weekly_hours INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS display_order INTEGER NOT NULL DEFAULT 0;
